[[ats_record-collection]]

//[cols="1,4",width="90%"]
//|===
//2+|*Conformance Class*
//2+|http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-colection
//|Target type |Web API
//|Requirements class |<<rc_record-collection,Requirements Class "Record Collection">>
//|===

[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-collection
target:: http://www.opengis.net/spec/ogcapi-records-1/1.0/req/record-collection
classification:: Target Type:Web API
abstract-test:: /conf/record-collection/mandatory-properties-collection
abstract-test:: /conf/record-collection/itemType
abstract-test:: /conf/record-collection/contact
abstract-test:: /conf/record-collection/license
abstract-test:: /conf/record-collection/links
abstract-test:: /conf/record-collection/links-catalog-hierarchy
abstract-test:: /conf/record-collection/links-catalog-related
abstract-test:: /conf/record-collection/links-catalog-series
abstract-test:: /conf/record-collection/links-record
abstract-test:: /conf/record-collection/links-records
abstract-test:: /conf/record-collection/records-array-name
abstract-test:: /conf/record-collection/records
abstract-test:: /conf/record-collection/default-mediatype
====

==== Catalog properties

include::record-collection/ATS_mandatory-properties.adoc[]

include::record-collection/ATS_itemType.adoc[]

include::record-collection/ATS_contact.adoc[]

include::record-collection/ATS_license.adoc[]

==== Catalog links

include::record-collection/ATS_links.adoc[]

include::record-collection/ATS_links-catalog-hierarchy.adoc[]

include::record-collection/ATS_links-catalog-related.adoc[]

include::record-collection/ATS_links-catalog-series.adoc[]

include::record-collection/ATS_links-record.adoc[]

include::record-collection/ATS_links-records.adoc[]

==== Catalog records

include::record-collection/ATS_records-array-name.adoc[]

include::record-collection/ATS_records.adoc[]

==== Media type

include::record-collection/ATS_default-mediatype.adoc[]
