[[ats_record-core]]

//[cols="1,4",width="90%"]
//|===
//2+|*Conformance Class*
//2+|http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core
//|Target type |Web API
//|Requirements class |<<rc_record-core,Requirements Class "Record Core">>
//|===

[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core
target:: http://www.opengis.net/spec/ogcapi-records-1/1.0/req/record-core
classification:: Target Type:Web API
abstract-test:: /conf/record-core/mandatory-properties-record
abstract-test:: /conf/record-core/links
abstract-test:: /conf/record-core/templated-link
abstract-test:: /conf/record-core/templated-link-header
abstract-test:: /conf/record-core/license
abstract-test:: /conf/record-core/contact
abstract-test:: /conf/record-core/time-instant-interval
abstract-test:: /conf/record-core/time-instant
abstract-test:: /conf/record-core/time-interval
abstract-test:: /conf/record-core/time-zone
abstract-test:: /conf/record-core/default-mediatype
====

==== Mandatory properties

include::record-core/ATS_mandatory-properties-record.adoc[]

==== Links

include::record-core/ATS_record-links.adoc[]

==== Link templates

include::record-core/ATS_templated-link.adoc[]

include::record-core/ATS_templated-link-header.adoc[]

==== License

include::record-core/ATS_record-license.adoc[]

==== Contacts

include::record-core/ATS_contact.adoc[]

==== Time

include::record-core/ATS_time-instant-interval.adoc[]

include::record-core/ATS_time-instant.adoc[]

include::record-core/ATS_time-interval.adoc[]

include::record-core/ATS_time-zone.adoc[]


==== Default media type

include::record-core/ATS_default-mediatype.adoc[]
