[[overview]]
== Overview

[[general-overview]]
=== General

The OGC API family of standards enable access to resources using the HTTP protocol and its' associated operations (GET, PUT, POST, etc.). OGC API-Common defines a set of features which are applicable to all OGC APIs. Other OGC standards extend API-Common with features specific to a resource type. This OGC API-Records standard defines an API with two goals:

. { __TBD__}
. Provide functionality comparable to that of the <<web-coverage-service-overview,OGC WCS standard>>.

Resources exposed through an OGC API may be accessed through a Universal Resource Identifier <<rfc3986,(URI).>> URIs are composed of three sections:

* Service Offering: The service endpoint (subsequently referred to as Base URI or {root})
* Access Paths: Unique paths to Resources
* Query: Parameters to adjust the representation of a Resource or Resources like encoding format or subsetting

Some resources are also accessible through links on previously accessed resources. Unique relation types are used for each resource.

<<records-paths>> summarizes the access paths and relation types defined in this standard.

[#records-paths,reftext='{table-caption} {counter:table-num}']
.Record API Paths
[width="90%",cols="2,^1,4",options="header"]
|===
^|**Path Template** ^|**Relation** ^|**Resource** 
3+^|**Common**
|<<landing-page,{root}/>> |none |Landing page
|<<api-definition,{root}/api>> |`service-desc` +
or +
`service-doc` |API Description (optional)
|<<conformance-classes,{root}/conformance>> |`conformance` |Conformance Classes
|<<collections,{root}/collections>> |`data` |Metadata describing the spatial collections available from this API.
|<<collectionInfo,{root}/collections/{coverageid}>> | |Metadata describing the collection which has the unique identifier `{collectionid}`
3+^|**Records**
|<<record-clause,{root}/collections/{coverageid}/record>> |`items` |TBD.
|===

Where:

* {root} = Base URI for the API server
* {collectionid} = an identifier for a specific collection

[[record-schema-overview]]
=== Record Schema

NOTE: insert a _Discussion of the Record resource_

[[api-behavior-model-overview]]
=== API Behavior Model

The Record API is designed to be compatible but not conformant with the OGC Catalogue Service for the Web (CS-W). This allows API-Record and CS-W implementations to co-exist in a single processing environment.

NOTE: Replace the following with a discussion of CS-W and API-Record

https://www.opengeospatial.org/standards/wcs[OGC Web Coverage Service standard version 2] has an internal model of its storage organization based on which the classic operations GetCapabilities, DescribeCoverage, and GetCoverage can be explained naturally. This model consists of a single CoverageOffering resembling the complete WCS data store. It holds some service metadata describing service qualities (such as WCS extensions, encodings, CRSs, and interpolations supported, etc.). At its heart, this offering holds any number of OfferedCoverages. These contain the coverage payload to be served, but in addition can hold coverage-specific service-related metadata (such as the coverage's Native CRS).

Discussion has shown that the API model also assumes underlying service and object descriptions, so a convergence seems possible. In any case, it will be advantageous to have a similar "mental model" of the server store organization on hand to explain the various functionalities introduced below.

[[dependencies-overview]]
=== Dependencies

The OGC API-Records standard is an extension of the OGC API-Common standard. Therefore, an implementation of API-Records must first satisfy the appropriate Requirements Classes from API-Common. <<mapping-to-common>> Identifies the API-Common Requirements Classes which are applicable to each section of this Standard. Instructions on when and how to apply these Requirements Classes are provided in each section.

[#mapping-to-common,reftext='{table-caption} {counter:table-num}']
.Mapping API-Records Sections to API-Common Requirements Classes
[width="90%",cols="2,6"]
|====
^|*API-Record Section* ^|*API-Common Requirements Class*
|<<landing-page,API Landing Page>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<api-definition,API Definition>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<conformance-classes,Declaration of Conformance Classes>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<collection-access-section,Collections>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|<<requirements-class-openapi_3_0-clause,OpenAPI 3.0>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/oas30
|<<requirements-class-json-clause,JSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/geojson
|<<requirements-class-html-clause,HTML>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/html
|====

