[[req_record-filter_filter-param]]

//[width="90%",cols="2,6a"]
//|===
//^|*Requirement {counter:req-id}* |*/req/features-filter/filter-param*
//^|A |The HTTP GET operation SHALL support the `filter` parameter as defined in https://portal.ogc.org/files/96288#filter-param[Parameter filter].
//^|B |For searchable catalogs, the path for which this parameter is supported SHALL be `/collections/{collectionId}/items`.
//^|C |For local resources catalogs, the path for which this parameter is supported SHALL be whichever path is being extended for catalog-like search capabilities (e.g., `/collections`).
//|===


[requirement]
====
[%metadata]
identifier:: /req/features-filter/filter-param
part:: The HTTP GET operation SHALL support the `filter` parameter as defined in https://portal.ogc.org/files/96288#filter-param[Parameter filter].
part:: For searchable catalogs, the path for which this parameter is supported SHALL be `/collections/{collectionId}/items`.
part:: For local resources catalogs, the path for which this parameter is supported SHALL be whichever path is being extended for catalog-like search capabilities (e.g., `/collections`).
====