[[req_record-filter_response]]

//[width="90%",cols="2,6a"]
//|===
//^|*Requirement {counter:req-id}* |*/req/record-filter/response*
//^|A |A filter expression SHALL be evaluated for each record of a collection.  
//^|B |All other filtering parameters specified (i.e. zero or more of <<core-query-parameters-bbox,bbox>>, <<core-query-parameters-datetime,datetime>>, <<core-query-parameters-q,q>>, <<core-query-parameters-type,type>>, <<core-query-parameters-externalIds,externalIds>> and any <<additional-query-parameters,additional query parameters>>) SHALL be evaluated for each record of a collection.
//^|C |If the filter expression AND all other specified filtering parameters (i.e. zero or more of <<core-query-parameters-bbox,bbox>>, <<core-query-parameters-datetime,datetime>>, <<core-query-parameters-q,q>>, <<core-query-parameters-type,type>>, <<core-query-parameters-externalIds,externalIds>> and any <<additional-query-parameters,additional query parameters>>) evaluate to `TRUE` then the record SHALL be included in the result set.
//^|D |If the filter expression OR any other specified filtering parameter (i.e. zero or more of <<core-query-parameters-bbox,bbox>>, <<core-query-parameters-datetime,datetime>>, <<core-query-parameters-q,q>>, <<core-query-parameters-type,type>>, <<core-query-parameters-externalIds,externalIds>> and any <<additional-query-parameters,additional query parameters>>) evaluates to `FALSE` then the record SHALL be excluded from the result set.
//|===


[requirement]
====
[%metadata]
identifier:: /req/record-filter/response
part:: A filter expression SHALL be evaluated for each record of a collection.  
part:: All other filtering parameters specified (i.e. zero or more of <<core-query-parameters-bbox,bbox>>, <<core-query-parameters-datetime,datetime>>, <<core-query-parameters-q,q>>, <<core-query-parameters-type,type>>, <<core-query-parameters-externalIds,externalIds>> and any <<additional-query-parameters,additional query parameters>>) SHALL be evaluated for each record of a collection.
part:: If the filter expression AND all other specified filtering parameters (i.e. zero or more of <<core-query-parameters-bbox,bbox>>, <<core-query-parameters-datetime,datetime>>, <<core-query-parameters-q,q>>, <<core-query-parameters-type,type>>, <<core-query-parameters-externalIds,externalIds>> and any <<additional-query-parameters,additional query parameters>>) evaluate to `TRUE` then the record SHALL be included in the result set.
part:: If the filter expression OR any other specified filtering parameter (i.e. zero or more of <<core-query-parameters-bbox,bbox>>, <<core-query-parameters-datetime,datetime>>, <<core-query-parameters-q,q>>, <<core-query-parameters-type,type>>, <<core-query-parameters-externalIds,externalIds>> and any <<additional-query-parameters,additional query parameters>>) evaluates to `FALSE` then the record SHALL be excluded from the result set.
====