== Conventions and background

=== General remarks

See <<OARec-1,OGC API - Records - Part 1: Core>>, Clauses 5 and 6.

=== Identifiers

The normative provisions in this standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-records-2/1.0`.

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Sequence diagrams

This document uses sequence diagrams to illustrate the flow of requests and responses 
between client and server.

The token `<resources endpoint>` is used for an endpoint that accesses
resources from a collection. 

EXAMPLE 1: For features, these endpoints are described by the 
URI template `{landingPageUri}/collections/{collectionId}/items`. See <<OAFeat-1,OGC API - Features - Part 1: Core>>.

The token `<resource endpoint>` is used for the endpoint that accesses a specific 
resource from a collection.

EXAMPLE 3: For features, these endpoints are described by the 
URI template `{landingPageUri}/collections/{collectionId}/items/{featureId}`. See <<OAFeat-1,OGC API - Features - Part 1: Core>>.
