= OGC API - Catalogues Standards Working Group Charter, OGC 19-060

* *Author Name(s):* Panagiotis (Peter) A. Vretanos, Tom Kralidis, Clemens Portele
* *Email:* pvretano@cubewerx.com, tom.kralidis@canada.ca, portele@interactive-instruments.de
* *DATE:* 28-JUN-2019
* *CATEGORY:* SWG Charter

To:  OGC members & interested parties

A new OGC Standards Working Group (SWG) is being formed. The OGC members listed below have proposed the "OGC API - Catalogues SWG".  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

The purpose of this Standards Working Group is to:

   * Design, discuss and document a new version of Catalogue Service standard
     (the HTTP Protocol Binding) as a Web API.
   * Develop new parts for the OGC API Catalogues multipart standard.
   * Develop corrigenda for previous versions of the OGC Catalogue
     standard(s).

== Business Value Proposition

In order to be able to better exploit geospatial resources (e.g., feature
collections, coverages, etc.) and other related resources (code lists,
definitions, etc.), end-users must be able to discover, filter and fetch
those resources. The proposed Web API will define the methods and apparatus
to support:

* Discovery of geospatial resources by standardizing the way collections of descriptive information about the resources (metadata) are exposed;

* Discovery and sharing of related resources that may be referenced from geospatial resources or their metadata by standardizing the way all kinds of records are exposed and managed.

For providers of geospatial resources who need to catalogue their holdings,
a catalogue provides a uniform means for indexing those resources as
metadata records. The Catalogue service API provides a uniform interface
for these catalogues.  The same uniform interface may be used for managing and
sharing the related resources.

For developers building infrastructures to host, harvest and/or manage
collections of geospatial resources, this proposed standard will define:

* A light-weight, but extensible, common core record schema for describing resources of all kinds including geospatial resources.
* A light-weight, but extensible, core API for searching collections of these
descriptive records.

Finally, users of geospatial resources are often in a position of having to
construct specialized processing flows for each different collection of
geospatial resources that they consume. The Catalogue API will be defined
to reduce such complexity and encourage the use of common tooling.

== Scope of Work

The current versions of the catalogue standards (i.e. CAT 2.0, CAT 3.0) -- developed in the early 2000s -- use a Remote-Procedure-Call-over-HTTP architectural style using XML for any payloads.  This was considered state-of-the art at the time but this legacy is now badly outdated and does not conform to current web development practices.

The definition of an "OGC API - Catalogues" standard is intended to break free of this legacy and will specify a modernized service that aligns with the current architecture of the Web and the Spatial Data on the Web Best Practices (https://www.w3.org/TR/sdw-bp/). The key changes are as follows.

* Name: +
The proposed name of the new standard is "OGC API - Catalogues - Part 1: Core".  However, one of the first actions of the SWG will be to settle on a name.  Other proposed names include "OGC API - Metadata" and "OGC API - Records".

* Scope: +
Catalogue interfaces have, in the geospatial domain, traditionally been used
to access collections of formal metadata such as FGDC, ISO19115 or ISO19119
metadata documents.  While the intent of the CAT4.0 SWG is to preserve this
functionality going forward, there is also a desire to broaden the scope so
that a catalogue can also act as a registry of other types of descriptive
metadata about resources such as code lists.

* Architecture: +
The definition of the "OGC API - Catalogues" will be consistent with HTTP and HTTPS. In previous versions, HTTP has been used mainly as a tunnel for RPC-like request messages. In addition, the resources provided by the service may include hypermedia controls in their representations to guide the user accessing a catalogue.

* Encodings: +
Previous versions of the OGC catalogue standards were strongly tied to XML (Capabilities documents, XML schemas, Filter Encoding expressions, etc.).  The definition of the "OGC API - Catalogues" standard will not define mandatory encodings and will allow clients and servers to negotiate a mutually agreeable output formats using standard HTTP content negotiation rules.  Because they are in common use today, the definition of the "OGC API - Catalogues" standard will include conformance classes for JSON, HTML and XML encodings.  Other encodings may also be defined as extensions in future parts of the standard.

* Basic information model: +
Previous versions of the OGC Catalogue Standard used the Dublin Core set of metadata (encoded as XML) as the basic, cross-platform, information model or set of queryables that all implementations needed to support.  "OGC API - Catalogues" will review the use of this model and strongly consider using DCAT (https://www.w3.org/TR/vocab-dcat/) or GeoDCAT (https://inspire.ec.europa.eu/good-practice/geodcat-ap), which are extensions to the Dublin Core model, for this purpose.

* Reuse: +
The use of OGC Catalogue-specific resources or components will be minimized and, where available, existing industry-standards that are commonly used by developers will be considered instead. The most important example for this is the use of an OpenAPI definition instead of OGC-specific "Capabilities" documents.

* Modularization: +
The OGC Catalogue Services 3.0 Specification - HTTP Protocol Binding standard, together with the OGC Filter Encoding 2.0 Encoding Standard, specifies a powerful, but complex service interface.  In order to better support implementations that only need a relatively simple service or client, the intent is to modularize the next version of the standard into multiple parts.  The first part (the "core") will specify a simple interface to search collections of catalogue records that is sufficient for use cases that do not require support for transactions, complex data structures, rich queries, etc. Additional parts will specify extensions to this part to meet the needs of use cases that require such capabilities.

* Security: +
The OGC Catalogue Services 3.0 Specification - HTTP Protocol Binding standard, like many other OGC web standards, does not specify how services may be secured and some requirements are incompatible with secured services that still conform to the standard. The use of OpenAPI would address this issue, too. Catalogues Services may be secured using security schemes that are commonly used on the Web today (e.g., OAuth2) and that developers are familiar with.

As a result of the planned modernization, "OGC API - Catalogues" implementations will not be backwards compatible with implementations of the OGC Catalogue Services 3.0 Specification - HTTP Protocol Binding. However, a design goal is to define "OGC API - Catalogues" in a way so that the interface can be mapped as a facade on top of existing OGC catalogue implementations - at least for the capabilities that were already in scope for those standards.

"OGC API - Catalogues" is intended to be simpler and more modern, but still be an evolution from the previous versions and their implementations.

The goal is to develop part 1 of "OGC API - Catalogues", the foundation for the new version, as quickly as possible and work on additional parts after that, driven by community interest.

An important aspect is to ensure that implementing the standard will lead to efficient implementations, happy developers of both server and client components, and satisfied users of such components.

This has several aspects:

Before finalizing the first version of "OGC API - Catalogues", the SWG needs to verify that the following objectives are met:

  * Working implementations for all capabilities defined in the proposed API must be available and tested and;

  * Implementation feedback must be considered.

A consequence of this approach is that the period between the availability of what is considered a mature draft and the finalization of the catalogue API standard may take longer than in the past, depending on the availability of evidence about the suitability of the candidate Standard based on implementations.

Developers, including those that are not active in OGC or ISO/TC 211, should be encouraged as early as possible to implement the draft standard and provide feedback. An aspect of this outreach is public access to in work draft documents.

To this end, the SWG intends to use GitHub in the development of this standard as this is the environment may developer are familiar with and user on a daily basis.

== Statement of relationship of planned work to the current OGC standards baseline

This standard is intended to be a major revision to the Catalogue Services standards published by OGC. This revision will take advantage of Web API patterns identified in the OGC API standards efforts (e.g., OGC API - Features, AKA WFS 3.0) to better align with current and emerging IT practices. "OGC API - Catalogues" does overlap in scope with the existing OGC Catalogue Services standards.

== What is Out of Scope?

Standards are important for interoperability. At the same time, it is important
that standards only state requirements that are important for a significantly
large group of users.  Proposals for new parts of OGC API Catalogues or change
requests to existing parts must identify the user group that will benefit from
the proposal and include the commitment for three independent implementations
for each proposed conformance class; otherwise the proposal will be considered
out-of-scope. 

OGC API Catalogues will be a modular, multi-part standard. Developing profiles
of OGC API Catalogues should not be necessary and is, therefore, out-of-scope
for the SWG. If a community has a need to develop a profile, the profile should
be specified and governed by that community.

== Specific Existing Work Used as Starting Point

The starting point for the work will be the "OGC® Catalogue Services 3.0 Specification - HTTP Protocol Binding", OGC 12-176r7.  The work will also be informed by the following documents and by recommendations found in:

   * OGC/W3C Spatial Data Working Group on the Web Best Practices (https://www.w3.org/TR/sdw-bp/);

   * OGC Geospatial API White Paper (OGC 16-019r4);

   * OGC API - Features - Part 1: Core candidate standard, OGC 17-069r2; and

   * SpatioTemporal Asset Catalog API Specification (https://github.com/radiantearth/stac-spec).

Each of these documents recommends an emphasis on resource oriented APIs in future OGC standards development including use of tools such as OpenAPI.

In addition, the following metadata standards will be reviewed:

   * Data Catalogue Vocabulary (DCAT) (https://www.w3.org/TR/vocab-dcat/);

   * GeoDCAT-AP (https://inspire.ec.europa.eu/good-practice/geodcat-ap)

   * https://www.w3.org/2017/dxwg/wiki/Main_Page

   * https://inspire.ec.europa.eu/good-practice/geodcat-ap

   * ebXML Registry Information Model, Version 3.0 (http://docs.oasis-open.org/regrep/regrep-rim/v3.0/regrep-rim-3.0-os.pdf).

   * ISO 19115-1:2014 Geographic Information -- Metadata -- Part 1: Fundamentals

   * ISO 19115-2:2019 Geographic Information -- Metadata -- Part 2: Extensions for Acquisition and Processing

   * ISO 19115-3:2016 Geographic Information -- Metadata -- Part 3: XML Schema Implementation for Fundamental Concepts

   * CDB SWG Metadata Analysis Spreadsheet (https://portal.opengeospatial.org/files/?artifact_id=73769)

   * DRAFT OGC CDB Metadata Enhancements: Background and Recommendations (https://portal.opengeospatial.org/files/?artifact_id=73767)

   * Security in your OpenAPI Specification (https://hackernoon.com/security-in-your-openapi-specification-94d081603950)

== Is This a Persistent SWG

YES

== When can the SWG be Inactivated

The SWG can be inactivated once the final multipart standard has been developed and change requests become minimal or not applicable for consideration. The SWG can be re-activated at any time.

== Description of deliverables

The following deliverables will result from the work of this SWG:

   * A final version of the "OGC API - Catalogue - Part 1: Core" document for
     submission to the TC; and

   * At least three prototype implementations of the core based on the standard -- although more would be preferred.

   * Zero or more additional parts as time and desire permits.

Part 1 will cover read-only access to records and simple query capabilities.

Capabilities for richer queries or to create, update or delete records will
be specified in additional parts.

== IPR Policy for this SWG

RAND-Royalty Free

== Anticipated Audience / Participants

Since we want implementations to proliferate the primary audience for the "OGC API - Catalogues" suite of standards will be developers implementing servers. Additionally, target audiences of the standard will include:

   * Deployers of catalogue services profiles; and

   * Users of catalogue services.

== Domain Working Group Endorsement

// The SWG will list all Domain Working Groups (DWGs) in which the SWG formation was discussed and/or chartered. If a DWG has specifically endorsed the formation of the SWG, then a statement of endorsement should be included.


== Other informative information about the work of this SWG

=== Collaboration

The SWG intends to use the following GitHub repository for the development of the new standard: https://github.com/opengeospatial/CAT4.0.

Like the work done by the WFS/FES SWG, the GitHub repository will be open to
the public to solicit participation and feedback from OGC and non-OGC members.

It should be noted that all votes on any issues or motions need to be cast by
SWG members only; this includes votes on making things public.  While the
GitHub repo is open to the public, the day-to-day work of the SWG is restricted
to OGC SWG members.

Additional collaboration resources include periodic teleconferences, email
and/or a gitter channel.

=== Similar or Applicable Standards Work (OGC and Elsewhere)

The following similar standards work may be applicable to the work of the
proposed SWG:

   * OpenGIS Catalogue Service Implementation Specification	 07-006r1
   * OGC® Catalogue Services 3.0 - General Model	12-168r6
   * OGC® OpenSearch Geo and Time Extensions	 10-032r8
   * OGC OpenSearch Extension for Earth Observation	 13-026r8

=== Details of first meeting

The first meeting of the SWG will be within four weeks of approval of the SWG.

=== Projected on-going meeting schedule

The work of this SWG will be carried out primarily on github and via email, conference calls, with potential face-to-face meetings at OGC TC meetings as agreed to by the SWG members. The teleconference calls will be scheduled as-needed and posted to the OGC portal.

=== Supporters of this Charter

The following persons support this SWG and are committed to the Charter and projected meeting schedule.

|===
|Name |Organization
|Roger Bracklin |Envitia
|Paul van Genuchten |Geocat
|Chris Holmes |Planet Labs
|Frederic Houbie |Hexagon
|Tom Kralidis |Environment and Climate Change Canada, Meteorological Service of Canada
|Clemens Portele |interactive instruments
|Angelos Tzotsos |Open Source Geospatial Foundation
|Panagiotis (Peter) A. Vretanos |CubeWerx Inc.
|===

=== Convener

   * Panagiotis (Peter) A. Vretanos
