[appendix]
:appendix-caption: Annex
[[annex_common]]
== Common building blocks (Normative)

[[common-overview]]
=== Overview

This annex describes the components of the OGC API - Records that are derived from OGC API - Common.

[[core-dependencies-section]]
=== Dependencies

This standard standard is an extension of the OGC API - Common standard. Therefore, an implementation of OGC API - Records must first satisfy the appropriate Requirements Classes from OGC API - Common.

include::requirements/record-api/REQ_api-common.adoc[]

[[api-platform-section]]
=== API Platform

OGC API - Common defines a set of shared capabilities which are applicable to any OGC Web API. Those capabilities provide the platform upon which resource-specific APIs can be built. This section describes those capabilities and any modifications needed to properly support Record resources.

[[landing-page]]
==== API landing page

The landing page provides a list of qualified links to begin exploration of the resources offered by an API. Links required by OGC API - Common are sufficient for this standard.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

The `Landing Page` operation is defined in the `Core` conformance class of OGC API - Common. No modifications are needed to support `Record` resources. The `Core` conformance class specifies only one way of performing this operation:

. Issue a `GET` request on the `{root}/` path

Support for `GET` on the `{root}/` path is required by OGC API - Common.

===== Response

A successful response to the `Landing Page` operation is defined in OGC API - Common. The schema for this resource is provided in <<landingPage-schema>>.

[#landingPage-schema,reftext='Landing Page Response Schema']
.Landing Page Response Schema
[source,yaml]
----
include::../openapi/schemas/common/landingPage.yaml[]
----

The following JSON fragment is an example of a response to an OGC API - Records Landing Page operation.

[#landingPage-example,reftext=`Landing Page Example`]
.Landing Page Example
[source,json]
----
include::../examples/json/landingPage.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[api-definition]]
==== API definition

Every API is required to provide a definition document that describes the capabilities of that API. This definition document can be used by developers to better understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of OGC API - Common. No modifications are needed to support `Records` resources. The `Core` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{root}/api` path
. Follow the `service-desc` or `service-doc` links on the landing page

Only the link is required by OGC API - Common.

===== Response

A successful response to the API Definition request is a resource which documents the design of the API. OGC API - Common leaves the selection of format for the API Definition response to the implementation. However, the options are limited to those which have been defined in the OGC API - Common standard. At this time, OpenAPI 3.0 is the only option provided.

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[conformance-classes]]
==== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API must declare the conformance classes it claims to have implemented.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of API - Common. No
modifications are needed to support `Records` resources. The `Core` conformance
class describes two ways of performing this operation:

. Issue a `GET` request on the `{root}/conformance` path
. Follow the `conformance` link on the landing page

Both techniques are required by API - Common.

===== Response

A successful response to the Conformance operation is a list of URLs. Each URL identifies an OGC Conformance Class for which this API claims conformance. The schema for this resource is defined in OGC API - Common and provided for reference in <<conformance-schema>>.

[#conformance-schema,reftext='Conformance Response Schema']
.Conformance Response Schema
[source,yaml]
----
include::../openapi/schemas/common/confClasses.yaml[]
----

The following JSON payload is an example of a response to an OGC API - Records conformance operation.

[#conformance-example,reftext=`Conformance Information Example`]
.Conformance Information Example
[source,json]
----
include::../examples/json/conformance.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[collections-access]]
=== Collections access

OGC API - Common assumes that spatial resources are organized into collections.
An API will expose one or more those collections. The OGC API - Common
Collections Conformance Class defines how to organize and provide access to a
collection of collections.

This standard extends the OGC API - Common `Collections` conformance class to
support collections of records, then extends that class to support capabilities
specific to the `Record` concept.

[[collections-metadata]]
==== Collections Metadata

The `Collections` operation returns a metadata document that describes the
collections available from this API.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|====

[[collections-meta-operation]]
===== Operation

This operation is defined in the `Collections` conformance class of OGC API - Common.
No modifications are required to support `Record` resources. The `Collections`
conformance class describes two ways of performing this operation:

. Issue a `GET` request on `{root}/collections` path
. Follow the `rel=data` link on the landing page

Support for both the `{root}/collections` path and the `rel=data` link is
required by API - Common.

[[collections-meta-response]]
===== Response

A successful response to the <<collections-meta-operation,Collections Operation>>
 is a document that contains summary metadata for each collection accessible though the API.

In a typical API deployment, the <<collection-meta-operation,collections response>>
will list collections of all offered resource types.  The collections where
the value of the `itemType` property (JSONPath: `$.collections[*].itemType`)
is `record` are collections of records (i.e. catalogs).

[#collections-schema,reftext='Collections Response Schema']
.Collections Response Schema
[source,yaml]
----
include::../openapi/schemas/common/collections.yaml[]
----

The following JSON payload is an example of a response to an OGC API - Records
<<collections-meta-operation,Collections>> operation.

[#collections-example,reftext=`Collections Example`]
.Collections Example
[source,json]
----
include::../examples/json/collections.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[collection-information]]
==== Collection Information

Collection Information is the set of metadata that describes a single
collection. An abbreviated copy of this information is returned for each
Collection in the <<collections-metadata,`/collections`>> response.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|====

[[collection-info-operation]]
===== Operation

This operation is defined in the `Collections` conformance class of API - Common.
No modifications are required to support `Records` resources.

. Issue a `GET` request on the `{root}/collections/{collectionId}` path

[[collection-identifier]]
The {collectionId} parameter is the unique identifier for a single collection 
offered by the API. The list of valid values for `{collectionId}` is provided
in the <<collections-metadata,`/collections`>> response.

Support for the `/collections/{collectionId}` path is required by OGC API - Common.

[[collection-info-response]]
===== Response

A successful response to the <<collection-info-operation,Collection>> operation
is a set of metadata that describes the collection identified by the
<<collection-identifier,`{collectionId}`>> parameter.

[#collectionInfo-schema,reftext='Collection Information Response Schema']
.Collection Information Response Schema
[source,yaml]
----
include::../openapi/schemas/common/collectionInfo.yaml[]
----

The following JSON payload is an example of a response to an OGC API - Records
Collection Information operation.

[#collection-info-example,reftext=`Collection Information Example`]
.Collection Information Example
[source,json]
----
include::../examples/json/collection.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[general-requirements-section]]
=== General requirements

The following requirements and recommendations are applicable to all OGC Records APIs.

[[http-protocol]]
==== HTTP 1.1

This standard uses the https://tools.ietf.org/rfc/rfc2616.txt[HTTP protocol]. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/record-api/REQ_http.adoc[]

[[http-status-codes]]
==== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`302` |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
|`303` |The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed.
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not changed since the previous request.
|`307` |The target resource resides temporarily under a different URI and the user agent MUST NOT change the request method if it performs an automatic redirection to that URI.
|`308` |Indicates that the target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

The return status codes described in <<status-codes>> do not cover all possible conditions. 

include::recommendations/record-api/PER_additional-status-codes.adoc[]

When a server encounters an error in the processing of a request, it may wish to include information in addition to the status code in the response. Since Web API interactions are often machine-to-machine, a machine-readable report is preferred. <<rfc7807,IETF RFC 7807>> addresses this need by providing "Problem Details" response schemas for both JSON and XML.

include::recommendations/record-api/REC_problem-details.adoc[]

[[query-parameter-requirements]]
==== Query parameters

include::requirements/record-api/REQ_query-param-unknown.adoc[]

include::requirements/record-api/REQ_query-param-invalid.adoc[]

The criteria for a parameter to be "specified" in the API definition depends on the API definition language used, the complexity of the resources exposed, and the ability of the API server to tolerate errors. 

A service implementer should endeavour to provide as much detail in the server's API definition as the API definition language allows. However, there is no requirement for it to list every endpoint for which there is a non-404 behaviour, for it to list every possible query parameter that might affect the behaviour of an endpoint, or for it to list every possible value that each query parameter might accept.

include::recommendations/record-api/PER_query-param-specified.adoc[]

include::recommendations/record-api/PER_query-param-tolerance.adoc[]

[[web-caching-section]]
==== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc7232,HTTP/1.1 (RFC 7232)>>.

include::recommendations/record-api/REC_etag.adoc[]

[[cross-origin-section]]
==== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/record-api/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

[[parameter-encoding-section]]
==== Parameter Encoding

The following sections provide the requirements and guidelines for encoding parameters for use in an OGC Web API request. 

OGC Web API requests are issued using a Uniform Resource Identifier (URI). The URI syntax is defined in <<rfc3986,IETF RFC 3986>>. Rules for building URI Templates can be found in <<rfc6570,IETF RFC 6570>>. 

The Backus-Naur Form (BNF) definition of a URI is provided in <<uri-bnf-annex,Annex F>>. 

===== Capitalization

<<rfc3986,IETF RFC 3986>> sections 6.2.2.1 and 2.1 provide the requirements for capitalization in URIs.

include::requirements/record-api/REQ_query-param-capitalization.adoc[]

===== Parameter Value Lists

Parameters may pass more than one value. These lists of parameter values may be passed in two ways.

. Repeated name:value pairs where the parameter name is repeated for each value in the list
. A parameter name followed by a delimited list of values.

The following requirements define how to encode a delimited list (case 2) of parameter values. They do not apply if replication (case 1) is used.

include::requirements/record-api/REQ_query-param-list-delimiter.adoc[]

include::requirements/record-api/REQ_query-param-list-escape.adoc[]

include::requirements/record-api/REQ_query-param-list-empty.adoc[]

Thus, two successive commas indicates an empty item, as does a leading comma or a trailing comma. An empty list ("") can either be interpreted as a list containing no items or as a list containing a single empty item, depending on the context.

===== Numeric and Boolean Values

Geospatial is a mathematical discipline. The clear and accurate exchange of mathematical values is essential. The encoding rules in this section standardize the encoding of numeric and boolean primitives when included in a URL. These rules are based on the computer science basic data types identified by <<k-and-r-1978,Kernighan and Ritchie>>.   

Boolean values conform to the following requirement.

include::requirements/record-api/REQ_query-param-value-boolean.adoc[]

Integer values conform to the following requirement.

include::requirements/record-api/REQ_query-param-value-integer.adoc[]

Real numbers can be represented using either the decimal or double (exponential) format. The decimal format is typically used except for very large or small values.

Decimal values conform to the following requirement. 

include::requirements/record-api/REQ_query-param-value-decimal.adoc[]

Double values conform to the following requirement. 

include::requirements/record-api/REQ_query-param-value-double.adoc[]

Special values conform to the following requirement. 

include::requirements/record-api/REQ_query-param-value-special.adoc[]
