[[clause-local-resources-catalogue]]
== Requirements Class "Local Resources Catalogue"

[[local-resources-catalogue-overview]]
=== Overview

include::requirements/requirements_class_local-resources-catalogue.adoc[]

This conformance class specifies requirements for a _local resources catalogue_.

The OGC API defines a number of resource endpoints that provide lists of
sub-resources.  These endpoints are referred to as _local resources catalogues_ in this standard because they provide metadata about resources offered locally by an OGC API deployment.

NOTE: The term _local resources endpoint_ is used to reference to the resource path of the _local resources catalogue_.  The term _local resources object_ is used to refer to an instance of the object or resource that can be retrieved from the _local resources endpoint_.

The `/collections` endpoint is an example of a _local resources endpoint_.  This endpoint provides a list of objects describing the collections of items offered by an OGC API deployment.  Each offered collection (path `/collections/{collectionId}`) is described by a _local resources object_ containing a small number of properties.  A common set of properties is defined in  https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] and can be extended by resource-specific specifications (e.g. http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Feature - Part 1: Core]).  In this respect, the `/collections` endpoint is a catalogue of records (i.e. `/collections/{collectionId}` objects) describing the collections of items offered by the OGC API deployment.

Other _local resources catalogues_ available in the OGC API resource tree include the `/processes` endpoint which provides a list of offered processes and the `/collections/{collectionId}/scenes` endpoint which provides a list of source images of a coverage.

In order to enable catalogue-like searching at these local resources endpoints, this conformance class defines requirements and recommendations that:

1. enhance the information content of each local resources object  (e.g. the `/collection/{collectionId}` object) with additional members from the list of <<core-queryables,core queryables>> defined for a catalogue <<clause-records-core,record>>,

2. define or extend the set of query parameters available at the local resources endpoint (e.g. `/collections`) to enhance it searchability.

This conformance class does not define the specific endpoints in the OGC API resource tree that should be enabled with catalogue-like query capabilities.  It only defines how those endpoints should be enhanced should the requirement for catalogue-line searching be identified by the responsible OGC standard.

=== Resource Description

=== Overview

The clause defines requirements and recommendations for the information content of a local resources object that can be retrieved from local resources endpoint.

As an example of a local resources endpoint, consider the `/collections` endpoint.  The object that can be retrieved from this endpoint is defined in https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_collections_[OGC API - Features].  The following table cross-walks the information content of the collection object with the <<core-queryables,core queryables>> defined for the <<clause-record-core,record>> building block:

[[record-collection-crosswalk]]
[reftext='{table-caption} {counter:table-num}']
.Crosswalk of core queryables with collection information object properties
[cols="25,25,25,25",options="header"]
|===
|Collection property |Requirement |Core Queryable |Requirement
|id                  |M           |id             |M
|title               |O           |title          |M
|description         |O           |description    |M
|itemType            |O           |--             |--
|extent              |O           |extent         |O
|links               |M           |links          |O
|crs                 |O           |--             |--
|===

It is evident that there is significant overlap of the properties of each resource.  This standard defines the following requirements and recommendations with regard to information content of a local resources object such as the collection object that is retrievable from the `/collections` endpoint.

=== Property `title`

include::requirements/local-resources-catalogue/REQ_property-title.adoc[]

=== Property `description`

include::requirements/local-resources-catalogue/REQ_property-description.adoc[]

=== Property `extent`

include::recommendations/local-resources-catalogue/REC_property-extent.adoc[]

=== Property `links`

include::recommendations/local-resources-catalogue/REC_property-links.adoc[]

=== Property `type`

include::requirements/local-resources-catalogue/REQ_property-type.adoc[]

=== Property `created`

include::requirements/local-resources-catalogue/REQ_property-created.adoc[]

=== Property `updated`

include::requirements/local-resources-catalogue/REQ_property-updated.adoc[]

NOTE: Adding, modifying, or deleting items from a collection are all examples of changes that may occur that would require an update of the collection object that can be retrieved from the `/collections` endpoint.

=== Property `keywords`

include::requirements/local-resources-catalogue/REQ_property-keywords.adoc[]

=== Additional properties

include::recommendations/local-resources-catalogue/PER_additional-properties.adoc[]

[[collection-additional-properties]]
[reftext='{table-caption} {counter:table-num}']
.Additional collection information properties
[cols="30,70",options="header"]
|===
|Property |Description
|language |The natural language used for textual values (i.e. titles, descriptions, etc) of a resource.
|publisher |The entity making the resource available.
|themes |A knowledge organization system used to classify the resource.
|formats |A list of available distributions for the resource.
|contactpoint |An entity to contact about the resource.
|license |A legal document under which the resource is made available.
|rights |A statement that concerns all rights not addressed by the license such as a copyright statement.
|===

=== Example

The following JSON-Schema fragment illustrates how the feature collections object (path: `/collection/{collectionId}`) can be extended to include properties required and recommended by this conformance class:

[source,yaml]
----
    allOf:
      $ref: "http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml"
      type: object
      required:
        - type
        - created
        - updated
        - keywords
      properties:
        type:
          description: the nature or genre of the items of the collections (e.g. feature, coverage)
          type: string
        created:
          description: the date this collection was created in the server
          type: string
          format: date-time
        updated:
          description: the most recent date on which the collection was updated
          type: string
          format: date-time
        keywords:
          description: A list of free-form keywords or tag associated with the collection
          type: array
          items:
           type: string
        language:
          description: the natural language used for textual values (i.e. titles, descriptions, etc) of items in the collection
          type: string
        publisher:
          description: the entity making the collection available
          type: string
        themes:
          description: list of classifications association with the collection from a knowledge organization system
          type: array
          items:
             type: string
             format: uri
        contactpoint:
          description: entity to contact about the collection
          type: object
        license:
          description: legal document under which the collection is made available.
          type: string
        rights:
          description: a statement that concerns all rights not addressed by the license such as a copyright statement.
          type: string
----

T.D.B.  Should add an instance example of a collection object.

=== Query parameters

==== Overview

To enable search capabilities at local resource endpoints, this conformance class defines a set of requirements and recommendations around query parameters that can be implemented at the endpoint.

==== Parameter bbox

include::requirements/local-resources-catalogue/REQ_param-bbox-def.adoc[]

include::requirements/local-resources-catalogue/REQ_param-bbox-response.adoc[]

==== Parameter datetime

include::requirements/local-resources-catalogue/REQ_param-datetime-def.adoc[]

include::requirements/local-resources-catalogue/REQ_param-datetime-response.adoc[]

==== Parameter limit

include::requirements/local-resources-catalogue/REQ_param-limit-def.adoc[]

include::requirements/local-resources-catalogue/REQ_param-limit-response.adoc[]

See all the discussion about the `limit` parameter in the http://docs.ogc.org/is/17-069r3/17-069r3.html#_response_6[Feature response] clause of the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

==== Parameter q

include::requirements/local-resources-catalogue/REQ_param-q-def.adoc[]

include::recommendations/local-resources-catalogue/REC_param-q.adoc[]

==== Parameter type

include::requirements/local-resources-catalogue/REQ_param-type-def.adoc[]

include::recommendations/local-resources-catalogue/REC_param-type.adoc[]

include::requirements/local-resources-catalogue/REQ_param-type-response.adoc[]

==== Additional query parameters

include::recommendations/local-resources-catalogue/REC_additional-query-parameters.adoc[]



[[clause-local-resources-catalogue_sorting]]
=== Requirements Class "Local Resources Catalogue, Sorting"

include::requirements/requirements_class_local-resources-catalogue_sorting.adoc[]

This conformance class specifies requirements and recommendations for supporting sorting of responses at _local resource catalogue_ endpoints.

==== Operation

include::requirements/local-resources-catalogue_sorting/REQ_param-sortby-def.adoc[]

==== Response 

include::requirements/local-resources-catalogue_sorting/REQ_param-sortby-response.adoc[]

See also: <<req_sorting_get-sortables-op,/req/sorting/get-sortables-op>>, <<req_sorting_get-sortables-success,/req/sorting/get-sortables-success>>.

=== Examples

Example 1: List all the collections that lie within a specific bounding box and contain the keyword `weather`.

----
   Client                                                          Server
     |                                                               |
     |   GET /collections?bbox=41.875315,-96.767601,56.732861,-73.476|
     |   586&q=weather   HTTP/1.1                                    |
     |   Accept: application/json                                    |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 200 OK                                             | 
     |   Content-Type: application/json                              |
     |                                                               |
     |   T.B.D. Need example output here...                          |
     |<--------------------------------------------------------------|
----



[[clause-local-resources-catalogue_cql2-filter]]
=== Requirements Class "Local Resources Catalogue - CQL2 Filter"

include::requirements/requirements_class_local-resources-catalogue_cql2-filter.adoc[]

This conformance class specifies requirements and recommendations for supporting advanced filtering using CQL2 at _local resource catalogue_ endpoints.

==== Operation

include::requirements/local-resources-catalogue_cql2-filter/REQ_filter-param.adoc[]

include::requirements/local-resources-catalogue_cql2-filter/REQ_filter-lang-param.adoc[]

include::recommendations/local-resources-catalogue_cql2-filter/REC_text-encoding.adoc[]

include::recommendations/local-resources-catalogue_cql2-filter/REC_json-encoding.adoc[]

include::requirements/local-resources-catalogue_cql2-filter/REQ_filter-crs-param.adoc[]

include::requirements/local-resources-catalogue_cql2-filter/REQ_queryables-link.adoc[]

==== Response

include::requirements/local-resources-catalogue_cql2-filter/REQ_filter-response.adoc[]
