[big]*i.     Abstract*

Blah, blah, blah, simple access API, blah, blah, blah, making resources discoveryable , blah, blah, blah, associations, blah, blah, blah, core queryables, blah, blah, core query prameters, blah, blah, blah, OpenAPI to support developers, blah, blah, blah.

[#tldr,reftext='{table-caption} {counter:table-num}']
.Overview of resources, applicable HTTP methods and links to the document sections[[table_1]][[tldnr]]
[cols="25,35,10,20",options="header"]
|===
|Resource |Path |HTTP method |Document reference
|Landing page |`/` |GET |<<landing_page,API landing page>>
|Conformance declaration |`/conformance` |GET |<<conformance_classes,Declaration of Conformance Classes>>
|Record collections |`/collections` |GET |<<collections-access,Collection Access>>
|Record collection |`/collections/{catalogueId}` |GET |<<collectionInfo,Collection Information>>
|Records |`/collections/{catalogueId}/items` |GET |<<records-access,Records Access>>
|Record |`/collections/{catalogueId}/items/{recordId}` |GET |<<record-access,Record Access>>
|===

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document,  <tags separated by commas>

[big]*iii.   Preface*

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

Organization name(s)

* CubeWerx Inc.

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

|===
^|Name  ^|Affiliation
| Panagiotis (Peter) A. Vretanos (editor) | CubeWerx Inc.
| Tom Kralidis (editor) | Meteorological Service of Canada
|===
