.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[abstract]
== Abstract

The OGC API family of Standards is being developed to make it easy for anyone to provide geospatial data over the web. These Standards build upon the legacy of the OGC Web Service Standards (WMS, WFS, WCS, WPS, CSW, etc.), but define resource-centric APIs that take advantage of modern web development practices.

This document defines the OGC API - Records - Part 1: Core Standard.  In this document "Records API" refers to the OGC API - Records - Part 1: Core Standard.

The content of a Record makes a resource discoverable by providing summary information (metadata) about the resource. In this context, resources are things that would be useful to a user or developer, such as features, coverages, tiles / maps, styles, assets, machine models, services, processes, widgets, notebooks etc.

An implementation of the OGC API - Records Standard provides a way to browse or search a curated collection of records known as a catalog.  The Records API Standard envisions deploying a catalog using one of the following patterns:

* a collection of static files,
* a collection of records accessed via an API.

A catalog can be deployed as a static collection of records stored in web-accessible files and typically co-located with the resources each record is describing.  Such a deployment is amenable to browsing using a web browser, being crawled by a search engine crawler, or traversed by automated tools.

A catalog can also be deployed as an implementation of a Web API consisting of well-known endpoints for retrieving information about the catalog, retrieving records from the catalog and searching the catalog for subsets of records that satisfy user-defined search criteria (area of interest, temporal extent, keywords, etc.).

To enable this kind of flexible deployment of a collection of records, the Records API Standard defines the following set of common components:

* a record,
* a catalog (a collection of records),
* a set of common query parameters,
* the requirements and characteristics for implementation instances of a Records search API (hereafter termed the "search API").

A record is the atomic unit of information in a catalog. It contains descriptive information (metadata) about a resource such as:

* a title,
* a human readable description of the resource,
* the nature or genre of the resource,
* keywords associated with the resource,
* information about the publisher or provider of the resource,
* links to access the resource,
* etc.

This information is generic and can be used to describe a wide variety of resources.  The Records API Standard expects and encourages implementations to enrich the information content of a record to suit specific use cases, requirements, domains, or communities of interest.

A collection of records is itself described by a record that provides descriptive information about the catalog.  The collection also provides access to the records of the collection either by explicitly linking to each record that is an item of the collection or by providing a search endpoint that allows the collection of records to be searched.

An implementation of a search API allows collections of records to be searched using logically connected spatial, temporal and scalar predicates.  This Standard uses the https://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] Standard for specifying requirements of the core of the Records search API.  Additional parts from the https://ogcapi.ogc.org/features/[OGC API - Features] suite of standards can also be implemented to enhance the capabilities of the search API.  The following table lists the endpoints of the core OGC API - Records API that allow a collection of records to be searched:

[api-path-table]
[reftext='{table-caption} {counter:table-num}']
.Overview of resources, applicable HTTP methods and links to the document sections[[table_1]][[tldnr]]
[cols="25,35,10,20",options="header"]
|===
|Resource |Path |HTTP method |Document reference
|Landing page |`/` |GET |https://docs.ogc.org/is/17-069r3/17-069r3.html#_api_landing_page[API landing page]
|Conformance declaration |`/conformance` |GET |<<conformance_class,Conformance>>
|Record collections |`/collections` |GET |<<record-collections,Record collections>>
|Record collection |`/collections/{collectionId}` |GET |<<clause-record-collection,Record collection>>
|Records |`/collections/{collectionId}/items` |GET |<<records-access,Records access>>
|Record |`/collections/{collectionId}/items/{recordId}` |GET |<<clause-record-core,Record Core>>
|===

A special use case of a catalog deployed as an implementation of a Web API is the _local resources catalog_.  A local resources catalog is a catalog deployed as an implementation of a Web API that makes local resources offered by a provider searchable using the catalog information model and accessed via the API.  An example of a local resources catalog is the `/collections` endpoint of http://docs.opengeospatial.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial data] or http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core].  Adding catalog capabilities to this endpoint enables a client to search for collections that satisfy a specified filter expression.  Any API endpoint defined in an OGC API Standard whose function is to provide descriptive metadata about other sub-resources accessible via the API can be extended to behave as a local resources catalog.  The `/collections` endpoint is an examples of such an endpoint.  The `/collections` endpoint provides metadata about the collections that a server offers.  One can well imagine the benefits of being able to search for a specific subset of collection descriptions on a server that offers thousands of data collections.


== Security considerations

Given the dependencies on the <<OACommon,OGC API - Common>> and <<OAFeat-1,OGC API - Features>> Standard, aspects of security are discussed in those Standards.

Metadata record encryption is out of scope for this Standard. However communities who wish to implement record encryption are free to do so as needed.



[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
^|Name  ^|Affiliation
| Panagiotis (Peter) A. Vretanos (editor) | CubeWerx Inc.
| Tom Kralidis (editor) | Meteorological Service of Canada
| Angelos Tzotsos (editor) | Open Source Geospatial Foundation
| Charles Heazel (editor) | HeazelTech
| Linda van den Brink | Geonovum
|===

[.preface]
== Acknowledgements

This specification acknowledges and remembers Douglas Nebert. As part of USGS and FGDC, Doug was internationally recognized as a champion of metadata, discovery and interoperability. He was one of the editors of the OGC Catalogue Services specification and a longtime champion of spatial data infrastructure initiatives including the US data.gov efforts, GEOSS and beyond. Doug’s vision and expertise will always be remembered and appreciated by the specification editors and community.
