[[conformance_class]]
== Conformance

=== Overview

Conformance with this Standard shall be checked using the tests specified in <<annex_ats,Annex A (normative)>> of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance, are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The standardization target of the conformance classes:

* <<clause-record-core,Record Core>>
* <<clause-record-collection,Record collection>>

is "Document model".

The standardization target of the conformance classes:

* <<clause-record-core-query-parameters,Record query parameters>>
* <<clause-records-api,Records API>>
* <<clause-sorting,Sorting>>
* <<clause-filtering,Filtering>>
* <<clause-searchable-catalog,Searchable Catalog>>
* <<clause-searchable-catalog_filtering,Searchable Catalog - Filtering>>
* <<clause-searchable-catalog_sorting,Searchable Catalog - Sorting>>
* <<clause-crawlable-catalog,Crawlable Catalog>>
* <<clause-local-resources-catalog,Local Resources Catalog>>
* <<clause-local-resources-catalog_filtering,Local Resources Catalog - Filtering>>
* <<clause-local-resources-catalog_sorting,Local Resources Catalog - Sorting>>
* <<clause-autodiscovery,Autodiscovery>>
* <<clause-oas30,OpenAPI 3.0>>

is "Web APIs".

The standardization target of the conformance classes:

* <<requirements-class-json-clause,JSON>>
* <<requirements-class-html-clause,HTML>>

is "Document encoding".


The Conformance Classes implemented in an API are advertised through the <<conformance-classes,`/conformance`>> path on the https://docs.ogc.org/is/17-069r3/17-069r3.html#_api_landing_page[landing page]. Each Conformance Class has an associated Requirements Class. The Requirements Classes define the functional requirements which will be tested through the associated Conformance Test.

[[building-block-requirements-classes]]
=== Building blocks

This standard also identifies ten (10) building block requirements classes:

* <<clause-record-core,Record Core>>
* <<clause-record-collection,Record collection>>
* <<clause-record-core-query-parameters,Record query parameters>>
* <<clause-records-api,Records API>>
* <<clause-sorting,Sorting>>
* <<clause-filtering,Filtering>>
* <<requirements-class-json-clause,JSON>>
* <<requirements-class-html-clause,HTML>>
* <<clause-oas30,OpenAPI 3.0>>
* <<clause-autodiscovery,Autodiscovery>>

The <<clause-record-core,_Record Core_>> conformance class defines the requirements for the core schema of a catalog record which is a set of properties (<<core-properties,core properties>>) that can be used to make any resource discoverable via a catalog.  This core set of properties can be extended as required by specific communities of interest and/or use cases.

The <<clause-record-collection,_Record Collection_>> conformance class defines requirements for the metadata used to describe a collection of related records.

The <<clause-record-core-query-parameters,_Record query parameters_>> conformance class defines a minimum set of query parameters that all queryable catalogs should provide.

The <<clause-records-api,_Records API_>> conformance class defines the requirements for an API implementation for searching collections of records based on logically connected predicates that can include spatial and/or temporal predicates.  The Records API Standard is based on http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Feature - Part 1: Core] with <<records-access,extensions>> specific to OGC API - Records.  https://docs.opengeospatial.org/is/17-069r4/17-069r4.html[OGC API - Features] provides a common foundation for other OGC API Standards for feature access. Therefore, this conformance class should be viewed as an extension to OGC API - Features. Conformance to this class requires demonstrated conformance to the applicable Conformance Classes define in the of https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#_conformance[OGC API - Features] Standard.

The <<clause-sorting,_Sorting_>> conformance class defines the requirements to support sorting of records in a query response.

The <<clause-filtering,_Filtering_>> conformance class defines the requirements to support record filtering using https://docs.ogc.org/DRAFTS/19-079r1.html[CQL2].

The <<requirements-class-json-clause,_JSON_>> conformance class defines the requirements for a JSON representation of a catalog object and a GeoJSON (see RFC 7946) representation of a standard catalog record.

The <<requirements-class-html-clause,_HTML_>> conformance class defines the requirements for an HTML representation of a standard catalog record.

The <<<<clause-oas30,OpenAPI 3.0>> conformance class defines the requirements for server that use an http://spec.openapis.org/oas/v3.0.3#openapi-document[OpenAPI 3.0] document to define their API.

The <<clause-autodiscovery,Autodiscovery>> conformance class defines requirements that allow catalogs that conform to this Standard and are associated with a web page or web site to be automatically discovered. 

[[catalog-requirements-classes]]
=== Catalog deployments

Using the above-mentioned building blocks, this Standard identifies the following catalog requirements classes:

* <<clause-crawlable-catalog,Crawlable Catalog>>
* <<clause-searchable-catalog,Searchable Catalog>>
** <<clause-searchable-catalog_sorting,Searchable Catalog - Sorting>>
** <<clause-searchable-catalog_filtering,Searchable Catalog - Filtering>>

* <<clause-local-resources-catalog,Local Resources Catalog>>
** <<clause-local-resources-catalog_sorting,Local Resources Catalog - Sorting>>
** <<clause-local-resources-catalog_filtering,Local Resources Catalog - Filtering>>

The <<clause-crawlable-catalog,Crawlable Catalog>> conformance class defines the core requirements for a catalog composed of a collection of web-accessible static files.

The <<clause-searchable-catalog,Searchable Catalog>>, <<clause-searchable-catalog_sorting,Searchable Catalog - Sorting>>, <<clause-searchable-catalog_filtering,Searchable Catalog - Filtering>> conformance classes define the requirements for a catalog composed of a collection of records that is searchable via an API.

The <<clause-local-resources-catalog,Local Resources Catalog>>, <<clause-local-resources-catalog_sorting,Local Resources Catalog - Sorting>>, <<clause-local-resources-catalog_filtering,Local Resources Catalog - Filtering>> conformance classes define the requirements for a local resources catalog which is a catalog composed of a list of resources offered by an OGC API deployment.  The `/collections` endpoint is an example of a local resources catalog but other endpoints may exist in an OGC API deployment as well.

[#required_building_blocks,reftext='{table-caption} {counter:table-num}']
.Required building blocks by catalog deployment type
[cols="<25,^25,^25,^25",options="header"]
|===
|Building block 3+|Catalog requirements class
| |<<clause-crawlable-catalog,_**Crawlable**_>> |<<clause-searchable-catalog,_**Searchable**_>> |<<clause-local-resources-catalog,_**Local Resources catalog**_>>
|<<clause-record-core,Record Core>> |Mandatory |Mandatory |Mandatory
|<<clause-record-collection,Record collection>> |_Optional_ |Mandatory |N/A
|<<clause-record-core-query-parameters,Record query parameters>> |N/A |_Mandatory_ |_Mandatory_
|<<clause-records-api,Records API>> |N/A |Mandatory |N/A
|<<clause-sorting,Sorting>> |N/A |_Optional_ |_Optional_
|<<clause-filtering,Filtering>> |N/A |_Optional_ |_Optional_
|<<requirements-class-json-clause,JSON>> |_Optional_ |_Optional_ |_Optional_
|<<requirements-class-html-clause,HTML>> |_Optional_ |_Optional_ |_Optional_
|<<clause-oas30,OpenAPI 3.0>> |N/A |_Optional_ |_Optional_
|===

=== Implementations

Implementors of this Standard select one or more of the <<catalog-requirements-classes,catalog deployment requirements classes>> they wish to implement and then implement the required building block requirements classes.

=== Conformance testing

Conformance with this Standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#deployment_conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Catalog Deployment Conformance class URIs
[cols="30,70",options="header"]
|===
|Conformance class |URI
|<<ats_crawlable_catalog,Crawlable Catalog>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/crawlable-catalog
|<<ats_searchable-catalog,Searchable Catalog>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/searchable-catalog
|<<ats_searchable_catalog_filtering,Searchable Catalog - Filtering>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/searchable-catalog-filtering
|<<ats_searchable-catalog_sorting,Searchable Catalog - Sorting>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/searchable-catalog-sorting
|<<ats_local-resources-catalog,Local Resources Catalog>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog
|<<ats_local-resources-catalog_filtering,Local Resources Catalog - Filtering>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog-filtering
|<<ats_local-resources-catalog_sorting,Local Resources Catalog - Sorting>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog-sorting
|===

[#building_block_conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Building Block Conformance class URIs
[cols="30,70",options="header"]
|===
|Conformance class |URI
|<<ats_record-core,Record Core>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core
|<<ats_record-collection,Record Collection>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-collection
|<<ats_record-core-query-parameters,Record query parameters>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core-query-parameters
|<<ats_records-api,Records API>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-api
|<<ats_sorting,Sorting>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/sorting
|<<ats_cql-filter,Filtering>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/filtering
|<<ats_json,JSON>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/json
|<<ats_html,HTML>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/html
|<<ats_oas30,OpenAPI 3.0>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/oas30
|<<ats_autodiscovery,Autodiscovery>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/autodiscovery
|===
