[[overview]]
== Overview

[[records-role]]
=== Role of OGC API - Records

Historically, catalogs have been used as large repositories of formal metadata such as ISO 19115, ISO 19119, FGDC, etc. More recently, catalogs are migrating to a more distributed model where the metadata is closely coupled with the resource that it describes. A current example is https://stacspec.org/en[STAC] which relies on well-defined common components that can be integrated in different ways.

Although OGC API - Records is built upon the legacy of the OGC Catalog Service Web (CSW) Standard, which was primarily focused on accessing a large repository of metadata documents, the Records API Standard can also support catalogs composed of a distributed set of static records.

In the modern scenario, the catalog records can be distributed and linked together so that they can be crawled, or they can be harvested into a service endpoint to make them searchable. In addition, a searchable catalog can harvest not only a metadata document describing the resource but in some cases the resource itself (e.g. harvesting the collections object from an OGC API). The implications of this are subtle yet important. In the traditional cataloging approach (e.g. based on CSW) a client could find the record and the record might include binding information to access the resource. Using the new approach, a client interacts more intimately with the catalog and the catalog becomes integral accessing the resource. An example is the cloud native ecosystem: HTTP range requests to Cloud Optimized GeoTIFF (COG) data cannot be used properly unless there is a STAC item telling the client in what ranges the bands exists. Therefore the catalog becomes an integral component (discovery, evaluation) in the process of accessing a resource.

[[general-overview]]
=== General

The atomic unit of information in a catalog is the _record_.

A _catalog_ is a collection of related _records_.  The terms **collection of records** and **catalog** are used interchangeably in this Standard.

A record provides a summary description (metadata) of a resource that the provider of the resource wishes to make discoverable.  The record schema defined in this Standard includes a small number of properties that can be used to provide a summary description of any resource.  It is anticipated, and encouraged, that this list of properties be extended to enhance the information content of a record as required by specific communities of interest and/or use cases.

=== Common components

The Records API Standard defines the following common components that may be used to deploy a catalog:

. The _core_ schema of a record.
. The definition of a _collection_ resource that groups and describes a set of related records (i.e. a catalog).
. The definition of a core set of query parameters for searchable catalogs.
. An API that allows a catalog to be searched using logically connected predicates that can include spatial and/or temporal predicates.

Using these common components a catalog can be deployed as:

* A set of web-accessible records that can be crawled by a search engine crawler, using (for example) a web browser, or by using automated tools.
* A searchable catalog with records accessible through an API endpoint.

A special use case of the _searchable catalog_ is the _**local resources catalog**_.  The <<ogc-api-resource-tree,OGC API resource tree>> has several endpoints that provide lists of resources.  Examples of such endpoints include the `/collections` and the `/processes` endpoints.  One can readily imagine a large deployment of APIs implementing https://ogcapi.ogc.org/[OGC API building blocks] with thousands of collections where the ability to search would enhance the client's interaction with the server.  Using the common components defined in this Standard, these endpoints can be extended to support catalog-like searching using filter expressions that may also include spatial and/or temporal predicates.  Implementations of OGC API endpoints extended in this way behave like a catalog of local resources.

[[record-schema-overview]]
=== Record Schema

The core set of record properties that may be used to describe a resource
include the  _id_, _type_, _title_, _description_ and _geometry_.
A complete definition of a record can be found in clause <<core-properties,Core properties>>.

The choice of which properties to include in the set of core properties was primarily informed by the following record models:

* The http://docs.opengeospatial.org/is/12-168r6/12-168r6.html#17[core catalog schema] from the https://www.ogc.org/standards/cat[OGC® Catalogue Services 3.0] suite of standards,
* The https://www.w3.org/TR/vocab-dcat/[Data Catalog Vocabulary (DCAT) - Version 2] and the https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.58/2017/mtg3/2017-UNECE-topic-i-EC-GeoDCAT-ap-paper.pdf[GeoDCAT-AP] specifications.

It is expected that the information necessary to populate this core set of properties is readily available for any resource that is being made discoverable by a record.

The expectation is that this _core_ set of properties will be extended to describe specific resource types (e.g. datasets, dataset series, Earth observation products, machine models, services, etc.).  The core can also be extended by information communities wishing to enrich the information content of the record to suit their needs.  Extending the information content of a record to suit specific needs is allowed, expected, and encouraged by this Specification.

Although the Records API Standard does not mandate any particular encoding for a record, the Standard does define conformance classes for two encodings:

* A <<requirements-class-geojson-clause,GeoJSON>> record encoding, and
* An <<requirements-class-html-clause,HTML>> encoding.

Other encodings are allowed but are not described in this Standard.

Accessing a catalog deployed as static files is described in the <<clause-crawlable-catalog,Crawlable records deployment>> clause.

Accessing a catalog through an implementations of the Records API is described in the <<records-access,Records access>> clause.

[[sc_record-collection-overview]]
=== Record collection (catalog)

A record collection or catalog is an object that groups and describes a set of related <<record-schema-overview,records>>.  The catalog is the primary access point from which a deployed set of records can be accessed.  Having found a catalog a client can, by following the appropriate hypermedia controls contained therein, navigate to the records of the collection.  

Depending on the deployment pattern, the catalog may provide a link to each individual record of the collection or a link to a search access point for retrieving subsets of records.

The core set of properties that may be used to describe a catalog include _id_, _type_, _title_, _description_, _extent_ and _links_.  A complete definition of a catalog can be found in clause <<clause-record-collection,Record collection>>.  It should be noted that this list of properties is very similar to the list of properties defined for a <<record-schema-overview,catalog record>>.  This is intentional since the catalog can be considered a _record_ that describes a related set of records.

It is anticipated that this set of properties will be extended to enrich the information content of the collection metadata to suit specific needs.

[[sc_record_api]]
=== Records API

==== Overview 

An implementation of the Records API Standard enables retrieving a subset of records from a catalog using a logically connected set of predicates that may include spatial and/or temporal predicates.

The Records API extends the http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] Standard to:

. Provide API patterns and encodings to facilitate further lowering the barrier to finding the existence of spatial resources on the Web.
. Provide functionality comparable to that of the http://docs.opengeospatial.org/is/12-176r7/12-176r7.html[OGC Catalogue Service (CSW)] Standard so that a facade can be created over legacy services thus allowing them to participate in the new OGC API Standards ecosystem.

To facilitate access to records in a catalog, the https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Feature - Part 1: Core] Standard has been:

* Extended with <<clause-record-core-query-parameters,additional parameters>> at the `/collections/{collectionId}/items` endpoint, 
* Constrained to a single information model (i.e. the <<record-model,record>>).

<<record-api-paths>> summarizes the access paths and relation types defined in this Standard.

[[records-paths]]
[#record-api-paths,reftext='{table-caption} {counter:table-num}']
.Records API Paths
[width="90%",cols="40,^20,40",options="header"]
|===
^|**Path Template** ^|**Relation** ^|**Resource** 
3+^|**Common**
|https://docs.ogc.org/is/17-069r4/17-069r4.html#_api_landing_page[/] ||Landing page
|https://docs.ogc.org/is/17-069r4/17-069r4.html#_api_definition_2[/api] |`service-desc` or `service-doc` |API Description (optional)
|https://docs.ogc.org/is/17-069r4/17-069r4.html#_declaration_of_conformance_classes[/conformance] | `conformance` |Conformance Classes
|https://docs.ogc.org/is/17-069r4/17-069r4.html#_collections_[/collections] | `data` |Metadata describing the catalogs available from this API implementation instance.
|<<clause-record-collection,/collections/{catalogId}>> |`collection` |Metadata describing a catalog which has the unique identifier `{catalogId}`
3+^|**Records**
|<<records-access,/collections/{catalogId}/items>> |`items` |Search results based on querying the service for records satisfying 0..n query parameters.
|<<record-access,/collections/{catalogId}/items/{recordId}>> |`item` |Record of metadata which has the unique identifier `{recordId}`.
|===

Where:

* `{catalogId}` = An identifier for a specific catalog.
* `{recordId}` = An identifier for a specific record within a collection.

[[api-behavior-model-overview]]
==== API Behaviour Model

The Records API Standard is designed to be compatible but not conformant with the http://docs.opengeospatial.org/is/12-176r7/12-176r7.html[OGC Catalogue Service for the Web (CSW)] Standard. This allows OGC API - Records implementations and CSW implementations to co-exist in a single processing environment.

The https://www.opengeospatial.org/standards/cat[OGC Catalogue Service Standard version 3] provides an abstract core model of metadata (data about data) describing a number of different information types (datasets, services, styles, processes, etc.) on which the classic operations (GetCapabilities, DescribeRecord, GetRecords, and GetRecordById) can be explained naturally. This model consists of 1 .. n catalog collections residing in a CSW backend repository. The model holds service metadata describing service qualities (identification, contact, operations, filtering capabilities, etc.). In principle, a catalog may provide discovery services to any number of metadata repositories. The core catalog model is based on an extension of Dublin Core (CSW Record). Application profiles can be developed to target specific metadata information models (such as ISO 19115/19139, etc.).

Discussion has shown that the Records API model also assumes underlying service and object descriptions, so a convergence seems possible. In any case, it will be advantageous to have a similar "mental model" of the server store organization on hand to explain the various functionalities introduced below.

==== Search

This Standard defines three levels of search capability of increasing complexity and capability.

The first or core level of search capability is based on <<OAFeat-1,OGC API - Features>> and thus supports:

* bounding box searches,
* time instant or time period searches, and
* equality predicates (i.e. _property_=_value_).

The Records API Standard extends these core search capabilities to include:

* keyword searches,
* searches based on the type of resource,
* searches based on one or more record identifiers, and
* searches based on one or more external identifiers of a resource.

The second level of search capability extends the search API so that it is compatible with the https://portal.opengeospatial.org/files/?artifact_id=56866[OGC OpenSearch Geo and Time Extensions] (OpenSearch Geo).  OpenSearch Geo gives the user more control over the kinds of geometries, beyond a bounding box, that can be used to define an area of interest.  https://fix.me[OGC API - Records - Part 2: OpenSearch] will define the requirements for a catalog that supports OpenSearch.

The third level of search capability, defined by the <<clause-filtering,_Filtering_>> requirements class, supports complex filter expressions using a rich set of logically connected query predicates.

[[dependencies-overview]]
==== Dependencies

The search API requirements and conformance classes defined in this Standard for accessing records from a searchable catalog is an extension of the https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Features - Part 1: Core Standard].  An implementation of a searchable catalog API must first satisfy the appropriate Requirements Classes from https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Features - Part 1: Core].  <<req-mappings>>, identifies these requirements. 

[#records-to-features,reftext='{table-caption} {counter:table-num}']
.Required OGC API - Features - Part 1: Core Requirements Classes for Records Access
[width="90%"]
|====
|*API - Features Requirements Classes*
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-op
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-bbox-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-bbox-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-limit-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-limit-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-time-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-time-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/query-param-invalid
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/query-param-unknown
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-links/req/core/fc-rel-type
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-timeStamp
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-numberMatches
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-numberReturned,
|====

[#record-to-features,reftext='{table-caption} {counter:table-num}']
.Required OGC API - Features - Part 1: Core Requirements Classes for Record Access
[width="90%"]
|====
|*API - Features Requirements Classes*
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/f-op
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/f-success
|====
