[[clause-core]]
== Requirements Class "Core"

[[core-overview]]
=== Overview

include::requirements/requirements_class_core.adoc[]

The `Core` Requirements Class defines the requirements for locating, understanding, and accessing Record resources. The `Core` Requirements Class is presented in five sections:

. <<api-platform-section,API Platform>>: a set of common capabilities
. <<collection-access,Collection Access>>: operations for accessing information about collections of records
. <<records-access,Records Access>>: operations for accessing record resources
. <<record-access,Record Access>>: operations for accessing a single record
. <<general-section,General>>: general principles for use with this standard

[[core-dependencies-section]]
=== Dependencies

This standard standard is an extension of the OGC API - Common standard. Therefore, an implementation of OGC API - Records must first satisfy the appropriate Requirements Classes from OGC API - Common.

include::requirements/core/REQ_api-common.adoc[]

[[api-platform-section]]
=== Platform

OGC API - Common defines a set of shared capabilities which are applicable to any OGC Web API. Those capabilities provide the platform upon which resource-specific APIs can be built. This section describes those capabilities and any modifications needed to properly support Record resources.

[[landing-page]]
==== API landing page

The landing page provides a list of qualified links to begin exploration of the resources offered by an API. Links required by OGC API - Common are sufficient for this standard.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

The `Landing Page` operation is defined in the `Core` conformance class of OGC API - Common. No modifications are needed to support `Record` resources. The `Core` conformance class specifies only one way of performing this operation:

. Issue a `GET` request on the `{root}/` path

Support for `GET` on the `{root}/` path is required by OGC API - Common.

===== Response

A successful response to the `Landing Page` operation is defined in OGC API - Common. The schema for this resource is provided in <<landingPage-schema>>.

[#landingPage-schema,reftext='Landing Page Response Schema']
.Landing Page Response Schema
[source,yaml]
----
include::../openapi/schemas/common/landingPage.yaml[]
----

The following JSON fragment is an example of a response to an OGC API - Records Landing Page operation.

[#landingPage-example,reftext=`Landing Page Example`]
.Landing Page Example
[source,json]
----
include::../examples/json/landingPage.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[api-definition]]
==== API definition

Every API is required to provide a definition document that describes the capabilities of that API. This definition document can be used by developers to better understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of OGC API - Common. No modifications are needed to support `Records` resources. The `Core` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{root}/api` path
. Follow the `service-desc` or `service-doc` links on the landing page

Only the link is required by OGC API - Common.

===== Response

A successful response to the API Definition request is a resource which documents the design of the API. OGC API - Common leaves the selection of format for the API Definition response to the implementation. However, the options are limited to those which have been defined in the OGC API - Common standard. At this time, OpenAPI 3.0 is the only option provided.

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[conformance-classes]]
==== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API must declare the conformance classes it claims to have implemented.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of API - Common. No
modifications are needed to support `Records` resources. The `Core` conformance
class describes two ways of performing this operation:

. Issue a `GET` request on the `{root}/conformance` path
. Follow the `conformance` link on the landing page

Both techniques are required by API - Common.

===== Response

A successful response to the Conformance operation is a list of URLs. Each URL identifies an OGC Conformance Class for which this API claims conformance. The schema for this resource is defined in OGC API - Common and provided for reference in <<conformance-schema>>.

include::requirements/core/REQ_conformance.adoc[]

include::recommendations/core/PER_additional-conformance.adoc[]

[#conformance-schema,reftext='Conformance Response Schema']
.Conformance Response Schema
[source,yaml]
----
include::../openapi/schemas/common/confClasses.yaml[]
----

The following JSON payload is an example of a response to an OGC API - Records conformance operation.

[#conformance-example,reftext=`Conformance Information Example`]
.Conformance Information Example
[source,json]
----
include::../examples/json/conformance.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[collection-access]]
=== Collection access

OGC API - Common assumes that spatial resources are organized into collections.
An API will expose one or more those collections. The OGC API - Common
Collections Conformance Class defines how to organize and provide access to a
collection of collections.

This standard extends the OGC API - Common `Collections` conformance class to
support collections of records, then extends that class to support capabilities
specific to the `Record` concept.

[[collections-metadata]]
==== Collections Metadata

The `Collections` operation returns a metadata document that describes the
collections available from this API.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|====

[[collections-meta-operation]]
===== Operation

This operation is defined in the `Collections` conformance class of OGC API - Common.
No modifications are required to support `Record` resources. The `Collections`
conformance class describes two ways of performing this operation:

. Issue a `GET` request on `{root}/collections` path
. Follow the `rel=data` link on the landing page

Support for both the `{root}/collections` path and the `rel=data` link is
required by API - Common.

[[collections-meta-response]]
===== Response

A successful response to the <<collections-meta-operation,Collections Operation>>
 is a document that contains summary metadata for each collection accessible though the API.

In a typical API deployment, the <<collection-meta-operation,collections response>>
will list collections of all offered resource types.  The collections where
the value of the `itemType` property (JSONPath: `$.collections[*].itemType`)
is `record` are collections of records (i.e. catalogues).

[#collections-schema,reftext='Collections Response Schema']
.Collections Response Schema
[source,yaml]
----
include::../openapi/schemas/common/collections.yaml[]
----

The following JSON payload is an example of a response to an OGC API - Records
<<collections-meta-operation,Collections>> operation.

[#conllections-example,reftext=`Collections Example`]
.Collections Example
[source,json]
----
include::../examples/json/collections.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[collection-information]]
==== Collection Information

Collection Information is the set of metadata that describes a single
collection. An abbreviated copy of this information is returned for each
Collection in the <<collections-metadata,`/collections`>> response.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|====

[[collection-info-operation]]
===== Operation

This operation is defined in the `Collections` conformance class of API - Common.
No modifications are required to support `Records` resources.

. Issue a `GET` request on the `{root}/collections/{collectionId}` path

[[collection-identifier]]
The {collectionId} parameter is the unique identifier for a single collection 
offered by the API. The list of valid values for `{collectionId}` is provided
in the <<collections-metadata,`/collections`>> response.

Support for the `/collections/{collectionId}` path is required by OGC API - Common.

[[collection-info-response]]
===== Response

A successful response to the <<collection-info-operation,Collection>> operation
is a set of metadata that describes the collection identified by the
<<collection-identifier,`{collectionId}`>> parameter.

[#collectionInfo-schema,reftext='Collection Information Response Schema']
.Collection Information Response Schema
[source,yaml]
----
include::../openapi/schemas/common/collectionInfo.yaml[]
----

The following JSON payload is an example of a response to an OGC API - Records
Collection Information operation.

[#collection-info-example,reftext=`Collection Information Example`]
.Collection Information Example
[source,json]
----
include::../examples/json/collection.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[records-access]]
=== Records access

==== Overview

The primary unit of information in a catalogue is a record. Tables <<core-queryables-record-table>> and <<core-queryables-resource-table>> in this clause present a generic set of properties, called _**core queryables**_, that may be included in a catalogue record.  The choice of which properties to include in the set of core queryables was primarily informed by the following record models:

* The https://docs.ogc.org/is/12-168r6/12-168r6.html#17[core catalogue schema] from the https://www.ogc.org/standards/cat[OGC® Catalogue Services 3.0] suite of standards,
* the https://www.w3.org/TR/vocab-dcat/[Data Catalog Vocabulary (DCAT) - Version 2] specification.
* and the https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.58/2017/mtg3/2017-UNECE-topic-i-EC-GeoDCAT-ap-paper.pdf[GeoDCAT-AP] specification.

It is expected that the information necessary to populate the core queryables is readily available for any resource that is being registered in the catalogue.  

This basic set of properties can be extended by information communities wishing to enrich the information content of the record to suit their needs.

Although this document does not mandate any particular encoding for a record, the document does define conformance classes for three encodings:

* A <<record_json_encoding,GeoJSON>> record encoding,
* an <<record_atom_encoding,ATOM>> record encoding,
* and an <<record_html_encoding,HTML>> encoding.

Other encodings are allowed but are not described in this document (i.e. they can be implemented as
part of separate Requirements Classes).

This clause describes how to search a catalogue to retreive a subset of records that satsify zero or more query criteria.

==== Operation

Catalogue records are  accessed at the `/collections/{collectionId}/items`
endpoint.

include::requirements/core/REQ_record-collection-op.adoc[]

[[parameters-section]]
==== Parameters

===== Overview

The following tables list the set mandatory query parameters that must be 
supported at the `/collections/{collectionId}/items` endpoint.

[[core-query-parameters-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of Query Parameters
[cols="15,85",options="header"]
|===
|Parameter name |Description
|`bbox` |A bounding box. If the spatial extent of the record intersects the specified bounding box then the record shall be presented in the response document.
|`datetime` |A time instance or time period. If the temporal extent of the record intersects the specified data/time value then the record shall be presented in the response document.
|`limit` |The number of records to be presented in a response document.
|`q` |A comma-separated list of search terms. If any server-chosen text field in the record contains 1 or more of the terms listed then this records shall appear in the response set.
|`type` |An equality predicate consistent of a comma-separated list of resource types.  Only records of the listed type shall appear in the resource set.
|`externalId` |An equality predicate consistent of a comma-separated list of external resource identifiers. Only records with the specified external identifiers shall appear in the response set.
|===

The query parameters https://docs.ogc.org/DRAFTS/20-024.html#bbox-parameter-requirements[`bbox`], https://docs.ogc.org/DRAFTS/20-024.html#datetime-parameter-requirements[`datetime`] and https://docs.ogc.org/DRAFTS/20-024.html#limit-parameter-requirements[`limit`] are inherited from OGC API - Common.  All requirements and recommendations in OGC API - Common regarding these parameters also apply for this standard.

The query parameters `q`, `type` and `externalId` are specific to this standard.

[[core-query-parameters-bbox]]
===== Parameter bbox

The Bounding Box (`bbox`) parameter is defined in OGC API - Common. The following requirement governs use of that parameter in this standard.

include::requirements/core/REQ_query-param-bbox.adoc[]

[[core-query-parameters-datetime]]
===== Parameter datetime

The DateTime (`datetime`) parameter is defined in OGC API - Common. The following requirement governs use of that parameter in this standard.

include::requirements/core/REQ_query-param-datetime.adoc[]

[[core-query-parameters-limit]]
===== Parameter limit

The limit (`limit`) parameter is defined in OGC API - Common. The following requirement governs use of that parameter in this standard.

include::requirements/core/REQ_query-param-limit.adoc[]

[[core-query-parameters-q]]
===== Parameter q

include::requirements/core/REQ_query-param-q-definition.adoc[]

include::recommendations/core/REC_param-q.adoc[]

include::requirements/core/REQ_query-param-q-response.adoc[]

[[core-query-parameters-type]]
===== Parameter type

include::requirements/core/REQ_query-param-type-definition.adoc[]

include::requirements/core/REQ_query-param-type-response.adoc[]

[[core-query-parameters-externalid]]
===== Parameter externalId

include::requirements/core/REQ_query-param-externalid-definition.adoc[]

include::requirements/core/REQ_query-param-externalid-response.adoc[]

[[additional-query-parameters]]
===== Additional query parameters

This standard defines the following URL query parameters based on the set of
<<core-queryables-record-table,core queryables>> to support record selection
based on the resource type and/or an external identifier associated with the
resource.

* <<core-query-parameters-type,type>>
* <<core-query-parameters-externalid,externalId>>

include::recommendations/core/REC_additional-query-parameters.adoc[]

===== Combinations of Filtering Parameters

Any combination of query parameters from the <<core-query-parameters-table,Table of Query Parameters>> and any <<additional-query-parameters,additional query parameters>> may be specified for filtering. Note that the requirements on these parameters imply that only records matching all the predicates are in the result set; i.e., the logical operator between the predicates is **AND** (exclusive).

[[query-response]]
==== Response

include::requirements/core/REQ_record-collection-response.adoc[]

include::requirements/core/REQ_record-collection-links.adoc[]

include::recommendations/core/REC_record-collection-next-1.adoc[]

include::recommendations/core/REC_record-collection-next-2.adoc[]

include::recommendations/core/REC_record-collection-next-3.adoc[]

This document does not mandate any specific implementation approach for `next` links.

An implementation could use opaque links that are managed by the server. It is
up to the server to determine how long these links can be de-referenced.
Clients should be prepared to receive a 404 response.

Another implementation approach is to use an implementation-specific parameter that specifies the index within the result set from which the server begins presenting results in the response, like the `startIndex` parameter that was used in <<WFS20,WFS 2.0>> (and which may be added again in additional parts of the OGC API - Features series).

The API will return no `next` link, if it has returned all selected record, and the server knows that. However, the server may not be aware that it has already returned all selected records. For example, if the request states `limit=10` and the query to the backend datastore returns 10 records, the server may not know, if there are more records or not (in most cases there will be more records), unless the total number of matches is also computed, which may be too costly. The server will then add the next link, and if there are no more records, dereferencing the next link will return am empty feature collection and no next link. This behavior is consistent with the statements above.

Clients should not assume that paging is safe against changes to dataset while a client iterates through `next` links. If a server provides opaque links these could be safe and maintain the dataset state during the original request. Using a parameter for the start index, however, will not be safe.

NOTE: Additional requirements classes for safe paging or an index parameter
may be added in extensions to this specification.

include::recommendations/core/PER_record-collection-prev.adoc[]

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

include::requirements/core/REQ_record-collection-rel-type.adoc[]

include::requirements/core/REQ_record-collection-timeStamp.adoc[]

include::requirements/core/REQ_record-collection-numberMatched.adoc[]

include::requirements/core/REQ_record-collection-numberReturned.adoc[]

NOTE: The representation of the links and the other properties in the payload depends on the encoding of the feature collection.

include::recommendations/core/PER_additional-properties.adoc[]

[[core-queryables-record-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the catalogue record
[cols="20,5,55,20",options="header"]
|===
|Queryables |Requirement |Description |GeoJSON key
|recordId |M |A unique record identifier assigned by the server. |`id`
|recordCreated |O |The date this record was created in the server. |`properties.recordCreated`
|recordUpdated |O |The most recent date on which the record was changed. |`properties.recordUpdated`
|links |O |A list of links for navigating the API (e.g. link to previous or next pages; links to alternative representations, etc.) |`links`
|===

[[core-queryables-resource-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the resource
[cols="20,5,55,20",options="header"]
|===
|Queryables |Requirement |Description |GeoJSON key
|type |M |The nature or genre of the resource. |`properties.type`
|title |M |A human-readable name given to the resource. |`properties.title`
|description |O |A free-text description of the resource. |`properties.description`
|keywords |O |A list of keywords or tag associated with the resource. |`properties.keyword`
|keywordsCodespace |O |A reference to a controlled vocabulary used for the keywords property. |`properties.keyword-codespace`
|language |O |This refers to the natural language used for textual values (i.e. titles, descriptions, etc) of a resource. |`properties.language`
|externalId |O |An identifier for the resource assigned by an external entity. |`properties.externalId`
|created |O |The date the resource was created. |`properties.created`
|updated |O |The more recent date on which the resource was changed. |`properties.updated`
|publisher |O |The entity making the resource available. |`properties.publisher`
|themes |O |A knowledge orgnaization system used to classify the resource. |`properties.themes`
|formats |O |A list of available distributions for the resource. |`properties.formats`
|contactPoint |O |An entity to contact about the resource. |`properties.contactpoint`
|license |O |A legal document under which the resource is made available. |`properties.license`
|rights |O |A statement that concerns all rights not addressed by the license such as a copyright statement. |`properties.rights`
|extent |O |The spatio-temporal coverage of the resource. |`properties.extent`
|associations |O |A list of links for accessing the resource, links to other resources associated with this resource, etc. |`properties.associations`
|===

The following YAML fragment defines the schema of a single record in a query response.

[#record-schema,reftext='Record Response Schema']
.Record Response Schema
[source,yaml]
----
include::../openapi/schemas/recordGeoJSON.yaml[]
----

==== Keywords and Themes

A record allows for one ``properties.keywords`` and 0..n ``properties.themes``
properties.  The following provides an example of using keywords for free
form terms (e.g. tags) as well as themes to articulate terms from formal
vocabularies.

[#keywords-themes-example,reftext=`Keywords and themes Example`]
.Keywords and themes Example
[source,json]
----
include::../examples/json/keywords-themes.json[]
----

The following recommendations provide clarification on where and how to use
these properties in a record.

include::recommendations/core/REC_record-keywords-themes.adoc[]

==== Associations and Links

A record contains both `links` and `properties.associations` properties which
serve different purposes.  The following provides an example of using
associations for related resources of a record, as both traditional link
relations as well as API resources via URI templates.

[#associations-simple-and-uri-template-example,reftext=`Associations simple and URI Template Example`]
.Associations simple and URI Template Example
[source,json]
----
include::../examples/json/associations-simple-and-uri-template.json[]
----

The following recommendations provide clarification on where and how to use
these properties in a record.

include::recommendations/core/REC_record-links.adoc[]

include::recommendations/core/REC_record-associations.adoc[]

NOTE: The representation of links in the payload will depend on the encoding of the record.

[[example_11]]
.Links in a record payload
====
The links in a record could be (in this example represented as link headers):

[source]
----
Link: <https://example.org/collections/mycat/items/record_123.json>; rel="self"; type="application/geo+json"
Link: <https://example.org/collections/mycat/items/record_123.html>; rel="alternate"; type="text/html"
Link: <https://example.org/collections/mycat.json>; rel="collection"; type="application/json"
Link: <https://example.org/collections/mycat:html>; rel="collection"; type="text/html"
----
====

==== Language negotiation

Two kinds of languages are handled in this specification.  The language
associated with the resource and the language associated with the record
that describes the resource in the catalogue.

The language associated with the resource is specified using the <<core-queryables-resource-table,language>> property of a catalogue record.  This indicates the language associated with the resource that the record described.

The language for the record itself is negotiated between a client and the servers using the https://tools.ietf.org/html/rfc7231#section-5.3.5[Accept-Language] header of https://tools.ietf.org/html/rfc7231[HTTP].  Records in a response document can only be presented in a single negotiated language.  There is no provision in the record schema to allow a response containing text fields simultaneously presented in multiple languages (e.g. multiple titles in different languages).  To obtain a record in multiple lanugages would require multiple requests to the server each nagotiating to a desired language.

==== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

==== Examples

The following is an example of a response to an OGC API - Records query
operation (path: `/collections/{collectionId}/items`).  This example shows
a JSON response and the response container is a GeoJSON feature collection.
Specific records are not presented in this example in order to illustrate
the structure of the response container in GeoJSON.

[#records-example,reftext=`Records Example`]
.Records Example in GeoJSON
[source,json]
----
include::../examples/json/record-collection.json[]
----

See <<record-example>> for an example of a single catalogue record.

[[record-access]]
=== Record access

==== Operation

include::requirements/core/REQ_record-op.adoc[]

==== Response

include::requirements/core/REQ_record-success.adoc[]

==== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

==== Examples

The following is an example of a single catalogue record encoded in GeoJSON.
Such a record might appears in the `features` array of a
<<records-example,query response>> or it may be the response when a specific,
single record is accessed (path: `/collections/{collectionId}/items/{recordId}`).

[#record-example,reftext=`Record Example`]
.Record Example in GeoJSON
[source,json]
----
include::../examples/json/record.json[]
----

[[general-requirements-section]]
=== General requirements

The following requirements and recommentations are applicable to all OGC Records APIs.

[[http-protocol]]
==== HTTP 1.1

This standard uses the https://tools.ietf.org/rfc/rfc2616.txt[HTTP protocol]. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/core/REQ_http.adoc[]

[[http-status-codes]]
==== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`302` |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
|`303` |The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed.
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not changed since the previous request.
|`307` |The target resource resides temporarily under a different URI and the user agent MUST NOT change the request method if it performs an automatic redirection to that URI.
|`308` |Indicates that the target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

The return status codes described in <<status-codes>> do not cover all possible conditions. 

include::recommendations/core/PER_additional-status-codes.adoc[]

When a server encounters an error in the processing of a request, it may wish to include information in addition to the status code in the response. Since Web API interactions are often machine-to-machine, a machine-readable report is preferred. <<rfc7807,IETF RFC 7807>> addresses this need by providing "Problem Details" response schemas for both JSON and XML.

include::recommendations/core/REC_problem-details.adoc[]

[[query-parameter-requirements]]
==== Query parameters

include::requirements/core/REQ_query-param-unknown.adoc[]

include::requirements/core/REQ_query-param-invalid.adoc[]

The criteria for a parameter to be "specified" in the API definition depends on the API definition language used, the complexity of the resources exposed, and the abilty of the API server to tolerate errors. 

A service implementer should endeavour to provide as much detail in the server's API definition as the API definition language allows. However, there is no requirement for it to list every endpoint for which there is a non-404 behaviour, for it to list every possible query parameter that might affect the behaviour of an endpoint, or for it to list every possible value that each query parameter might accept.

include::recommendations/core/PER_query-param-specified.adoc[]

include::recommendations/core/PER_query-param-tolerance.adoc[]

[[web-caching-section]]
==== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc7232,HTTP/1.1 (RFC 7232)>>.

include::recommendations/core/REC_etag.adoc[]

[[cross-origin-section]]
==== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/core/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

[[parameter-encoding-section]]
==== Parameter Encoding

The following sections provide the requirements and guidelines for encoding parameters for use in an OGC Web API request. 

OGC Web API requests are issued using a Uniform Resource Identifier (URI). The URI syntax is defined in <<rfc3986,IETF RFC 3986>>. Rules for building URI Templates can be found in <<rfc6570,IETF RFC 6570>>. 

The Backus-Naur Form (BNF) definition of a URI is provided in <<uri-bnf-annex,Annex F>>. 

===== Capitalization

<<rfc3986,IETF RFC 3986>> sections 6.2.2.1 and 2.1 provide the requirements for capitalization in URIs.

include::requirements/core/REQ_query-param-capitalization.adoc[]

===== Parameter Value Lists

Parameters may pass more than one value. These lists of parameter values may be passed in two ways.

. Repeated name:value pairs where the parameter name is repeated for each value in the list
. A parameter name followed by a delimited list of values.

The folowing requirements define how to encode a delimited list (case 2) of parameter values. They do not apply if replication (case 1) is used.

include::requirements/core/REQ_query-param-list-delimiter.adoc[]

include::requirements/core/REQ_query-param-list-escape.adoc[]

include::requirements/core/REQ_query-param-list-empty.adoc[]

Thus, two successive commas indicates an empty item, as does a leading comma or a trailing comma. An empty list ("") can either be interpreted as a list containing no items or as a list containing a single empty item, depending on the context.

===== Numeric and Boolean Values

Geospatial is a mathematical discipline. The clear and accurate exchange of mathematical values is essential. The encoding rules in this section standarize the encoding of numeric and boolean primitives when included in a URL. These rules are based on the computer science basic data types identified by <<k-and-r-1978,Kernighan and Ritchie>>.   

Boolean values conform to the following requirement.

include::requirements/core/REQ_query-param-value-boolean.adoc[]

Integer values conform to the following requirement.

include::requirements/core/REQ_query-param-value-integer.adoc[]

Real numbers can be represented using either the decimal or double (exponential) format. The decimal format is typically used except for very large or small values.

Decimal values conform to the following requirement. 

include::requirements/core/REQ_query-param-value-decimal.adoc[]

Double values conform to the following requirement. 

include::requirements/core/REQ_query-param-value-double.adoc[]

Special values conform to the following requirement. 

include::requirements/core/REQ_query-param-value-special.adoc[]

