== Scope

The OGC Records API Standard specifies requirements classes for a set of common components that can be assembled in various ways to deploy a collection of related descriptive information (metadata) about resources called a catalog.  The atomic unit of information in a catalog is the record.

This Standard specifies the information content of a record.  A record contains summary descriptive information (metadata) about a resource that a provider wishes to make discoverable.  A record represents resource characteristics that can be presented for evaluation and further processing by both humans and software.  Examples of resources include a data collection, a service, a process, a style, an Earth observation asset, a machine learning model, a code list and so on.

Records are organized into collections called _catalogs_.  The Records API Standard describes how catalogs can be crawled or searched.  Crawling a collection of records involves following embedded links from one record in a catalog to the next.  Searching a collection of records involves specifying query predicates that define a subset of records.
