== Conventions

The following conventions will be used in this document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers

The normative provisions in this standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-records-1/1.0`.

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Examples

Most of the examples provided in this standard are encoded in JSON. JSON is chosen because it is widely understood by implementers and easy to include in a text document. This convention should NOT be interpreted as a requirement that JSON must be used. Implementors are free to use any format they desire as long as there is a Conformance Class for that format and the API advertises its support for the associated Conformance Class.

=== Schema

JSON Schema is used throughout this standard to define the structure of resources. These schema are typically represented using YAML encoding. This convention is for the ease of the user. It does not prohibit the use of another schema language or encoding. Nor does it indicate that JSON Schema is required. Implementations should use a schema language and encoding appropriate for the format of the resource.

=== UML Notation

Diagrams using the Unified Modeling Language (UML) adhere to the following conventions:

* UML elements having a package name of “GML” are those defined in the UML model of GML 3.2.1
* UML elements having a package name of “SWE Common” are those defined in the UML model of SWE Common 2.0
* UML elements not qualified with a package name, or with “CIS”, are those defined in this standard.

Further, in any class where an attribute name or association role name is identical to a name in some superclass the local definition overrides the superclass definition.

[[namespace-prefixes]]
=== Namespace Prefix Conventions

UML diagrams and XML code fragments adhere to the namespace conventions shown in <<namespace-mapping-conventions>>. The namespace prefixes used in this document are not normative and are merely chosen for convenience. The namespaces to which the prefixes correspond are normative, however.

[reftext='{table-caption} {counter:table-num}']
.Namespace mapping conventions
[width="90%",cols="^2,^2,6,6",options="header"]
|====
|*GML/XML prefix* ^|*Namespace URL* ^|*Description*

|atom |http://www.w3.org/2005/Atom |ATOM namespace
|core |http://www.opengis.net/ogcapi-record-1/1.0 |OGC API - Records core elements
|dc |http://purl.org/dc/elements/1.1/ |Dublin core elements
|dcat |http://www.w3.org/ns/dcat# |DCAT vocabulary
|dct |http://purl.org/dc/terms/ |Dublin core terms
|gml |http://www.opengis.net/gml/3.2 |GML 3.2.1
|gml33 |http://www.opengis.net/gml/3.3 |GML 3.3
|os |http://a9.com/-/spec/opensearch/1.1/ |OpenSearach namespace
|xlink |http://www.w3.org/1999/xlink |XLink namespace
|====
