[[clause-record-core]]
== Requirements Class "Record Core"

[[record-core-overview]]
=== Overview

include::requirements/requirements_class_record-core.adoc[]

The `Record` Requirements Class defines the requirements for a catalogue record.

[[record-model]]
=== Record

The atomic unit of information in a catalogue is a **_record_** which is defined in this clause.

It is expected that the information necessary to populate the fields/properties of a catalogue record is readily available for any resource that is being registered in the catalogue.

It is anticipated that the schema of a record will be extended to describe specific resource types (e.g. datasets, services, etc.) and also extended by information communities wishing to enrich the information content of the record to suit their needs.

Although this document does not mandate any particular encoding for a record, this document does define conformance classes for two encodings:

* a <<record_json_encoding,GeoJSON>> record encoding,
* and an <<record_html_encoding,HTML>> encoding.

Other encoding are allowed but are not described in this document.

==== Overview

[[core-queryables]]
==== Core queryables

<<core-queryables-record-table>> and <<core-queryables-resource-table>> define the set of properties, called the _core queryables_, that may be included in a record.

[#core-queryables-record-table,reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the catalogue record
[cols="20,5,55,20",options="header"]
|===
|Queryables |Requirement |Description |GeoJSON key
|recordId |**required** |A unique record identifier assigned by the server. |id
|created |optional |The date this record was created in the server. |properties.created
|updated |optional |The most recent date on which the record was changed. |properties.updated
|conformsTo |optional |The extensions/conformance classes used in this record. |conformsTo
|===

[#core-queryables-resource-table,reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the resource
[cols="20,5,55,20",options="header"]
|===
|Queryables |Requirement |Description |GeoJSON key
|geometry |**required** |A geometry associated with the resource that is used for discovery.  Can be null if there is no associated geometry. |geometry
|time |**required** |The temporal extent of the resource. Can be null if there is no associated temporal extent. |time
|type |**required** |The nature or genre of the resource. |properties.type
|title |**required** |A human-readable name given to the resource. |properties.title
|description |optional |A free-text description of the resource. |properties.description
|keywords |optional |A list of free-form keywords or tags associated with the resource. |properties.keywords
|language |optional |The language used for textual values (i.e. titles, descriptions, etc) of this record. |properties.language
|languages |optional |The list of other languages in which this record is available. |properties.languages
|resourceLanguages |optional |The list of languages in which the resource described by this record can be retrieved. |properties.resourceLanguages
|externalIds |optional |One or more identifiers for the resource assigned by an external entity. |properties.externalIds
|themes |optional |A knowledge organization system used to classify the resource. |properties.themes
|formats |optional |A list of available distributions for the resource. |properties.formats
|contacts |optional |A list of contacts qualified by their role(s) in association to the record or resource. |properties.contacts
|license |optional |A legal document under which the resource is made available. |properties.license
|rights |optional |A statement that concerns all rights not addressed by the license such as a copyright statement. |properties.rights
|links |**required** |A list of links for accessing the resource (e.g. download link, access link, etc.) in one of the supported distribution formats and/or links to other resources associated with this resource.  Also, a list of links for navigating the API (e.g. prev, next, alternate, etc.). |links
|===

include::requirements/record-core/REQ_mandatory-queryables-record.adoc[]

include::recommendations/record-core/PER_common-mark.adoc[]

include::recommendations/record-core/PER_additional-queryables-record.adoc[]


[[sc_record_extensions]]
==== Record extensions

In tables <<core-queryables-record-table>> and <<core-queryables-resource-table>> this standard defines a set of core properties for describing discoverable resources.  It is anticipated that this set of core properties will be extended to suite specific use cases or requirements.  For example, a catalogue record may be extended to include additional properties from the https://semiceu.github.io/GeoDCAT-AP/releases/[GeoDCAT] vocabulary.  The fact that a catalogue record has been extended in this way can be advertised using the `conformsTo` member.  The `conformsTo` member is a list of identifiers that indicate each extension used in a record.  This specification does not define the specific identifiers that are used to identify specific extensions; it simply provides a place where these identifiers can be listed.

include::recommendations/record-core/REC_record-extensions.adoc[]

In the case where all the records of a catalogue use the same set of extensions, and to prevent unnecessary duplication, there is also a `conformsTo` member at the https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/catalogue.yaml[collection or catalogue level] that may be used to declare which extensions are used in all records of the catalogue.  Extensions listed at the catalogue and record levels are cumulative.

[[sc_temporal_information]]
==== Temporal information

===== Instants

include::requirements/record-core/REQ_time-instant.adoc[]

===== Intervals

include::requirements/record-core/REQ_time-interval.adoc[]

===== Instants and intervals

include::requirements/record-core/REQ_time-instant-interval.adoc[]

===== Time zones

include::requirements/record-core/REQ_time-zone.adoc[]

[[sc_keywords_and_themes]]
==== Keywords and Themes

A record allows for one `properties.keywords` and zero to many `properties.themes` properties.  Keywords are free form terms or tags associated with the resource(s) that the record describes.  Themes are concepts associated with the resource(s) that a record describes taken from one or more formal knowledge organization systems or schemes.  The list of knowledge organization systems or schemes used in a <<clause-searchable-catalogue,searchable>> or <<clause-local-resources-catalogue,local resources>> catalogue can be determined by inspecting the server's OpenAPI document or, if the server implements CQL2, by exposing a queryable (e.g. named `scheme`) and enumerating the list of schemes used in the queryable's schema definition.

include::recommendations/record-core/REC_record-keywords-themes.adoc[]

The following provides an example of using keywords for free form terms (e.g. tags) as well as themes to articulate terms from formal vocabularies or classification systems.

[#keywords-themes-example,reftext=`Keywords and themes Example`]
.Keywords and themes Example
[source,json]
----
include::../examples/json/keywords-themes.json[]
----

[[sc_contacts]]
==== Contacts

include::requirements/record-core/REQ_contact.adoc[]

[[sc_type_and_licenses]]
==== Type and Licenses

A record has one `properties.type` property. The value of this property should be a code, convenient for filtering records. 

include::recommendations/record-core/REC_record-type.adoc[]

include::recommendations/record-core/PER_record-type.adoc[]

In addition, links to external resources describing the record type vocabulary used to populate the `properties.type` member are recommended, as described in <<sc_associations_and_links,Associations and Links>>.

[[sc_license_vocabulary]]
==== License vocabulary

A record may have one `properties.license` property. If present, the value of this property should be a code, convenient for filtering records.

include::recommendations/record-core/REC_record-license.adoc[]

[[sc_associations_and_links]]
==== Associations and Links

A record must contain a `links` section and may contain a <<sc_templated_links_with_variables,`linkTemplates`>> section.  These sections contain navigation links and/or association links.

Navigation links are meant to encode relationships between catalogue entities (i.e. <<clause-core-record-collection,collections>> and <<clause-record-core,records>>).  Navigation links in the `links` section can include links to the collection (`rel="collection`) of which a record is a member, alternative representations (`rel="alternate"`) of the record, and navigation links to previous (`rel="prev"`) or next (`rel="next"`) records in a chain of records.  Links in the `links` section may also be used to organize records in a hierarchy (e.g. `rel="root"`, `rel="parent"`, `rel="child`).

include::requirements/record-core/REQ_record-links.adoc[]

Links in the `links` section may also encode canoncial URIs for record properties such as `type` and `license`.

include::recommendations/record-core/REC_record-links_type.adoc[]

include::recommendations/record-core/REC_record-links_iana.adoc[]

Association links point to the resource(s) being described by a record. Such links allow binding to a resource once it has been discovered by searching a catalogue.  Depending on how the target resource of a record is represented and how it may be accessed, there may be one or more association links.  For example, if the target resource is an Earth observation imagery file, links may point to the indivdually accessible bands of the image file.

Association links are also meant to point to other records related to the containing record.  For example, consider a record that describes a set of vector features and another record that describes a rendering style for that feature set.  These two records may, in their respective `links` sections point to each other to encode this "styles"/"styled-by" relationship.

Finally, association links are meant to point to other resources external to the catalogue that are related to the containing record or the resource(s) that the record describes.

include::recommendations/record-core/REC_record-associations_relate.adoc[]

In some instances additional context may be desirable or required in order to access (or bind to) the resource(s) being described by a record.  This is the case when, for example, access to the resource is through a service interface that requires mandatory parameters to be provided.  The OGC Web Map Service (WMS) is an example of such a service.  It may also be the case that efficient access to the resource would be facilitated by providing additional context.  Accessing data from a large data repository such as a data cube would be more efficient if the context of the query used to discover the resource (e.g. bbox, datetime) were passed down to the link used to access the data.

include::recommendations/record-core/REC_record-associations_templated.adoc[]

NOTE: This specification does not define any specific link relations that should be used for links in the `links` or <<sc_templated_links_with_variables,`linkTemplates`>> sections.  Such relationships are typically domain specific and so it is left to communities of interest to standardize the links that relations should use.

The following provides an example of using association links for related resources of a record, as both traditional link relations as well as API resources via URI templates.

[#associations-simple-and-uri-template-example,reftext=`Associations simple and URI Template Example`]
.Associations simple and URI Template Example
[source,json]
----
include::../examples/json/associations-simple-and-uri-template.json[]
----

[#links-in-https-headers,reftext=`Example of links in HTTP headers`]
.Example of links and link templates in HTTP headers
[source]
----
Link: <https://woudc.org/data/stations>; rel="search"; type="text/html"
Link-Template: <https://geo.woudc.org/ows?service=WMS&version=1.3.0&request=GetMap&crs={crs}&bbox={bbox}&layers=stations&width={width}&height={height}&format=image/png>; rel="item"; type="image/png"; varBase="https://geo.woudc.org/variables/"
----

[[sc_templated_links_with_variables]]
==== Templated links with variables

OGC API - Records uses links to express associations between resources including links that bind to the resource(s) being described by a record.  In some situations, a static link does not adequately express all the information necessary to retrieve the referenced resource OR does not allow for the resource to be retrieved in an efficient manner.

Consider the case where a record describing a coverage resource is discovered by searching the catalogue using a spatial constraint (e.g. a bbox).  Further consider that the found record contains a link to retrieve the coverage.  Using a static link would only allow for retrieval of the entire coverage or a subset unrelated to the user's original catalogue query.  Using a templated link, however, would allow the context of the catalogue query (i.e. the bbox) to be passed to the retrieval link as a substitution variable.  The templated link with all substitution variables resolved would thus retrieve the subset of the coverage that corresponds to the spatial contraint used to discover the record in the first place which presumably represents the area of interest.

Templated links may also be used to bind to resources that may require additional information in order to access the resources.  For example, simply knowing the URL of a legacy OGC service such as https://portal.ogc.org/files/?artifact_id=14416[WMS] or https://docs.ogc.org/is/09-025r2/09-025r2.html[WFS] is not sufficient to access resources offered by those services.  Additional information in the form of request parameters and values are required in order to have a complete link to a resource.  A templated link with variables can provide this additional context.

This specification defines a new schema, https://github.com/opengeospatial/ogcapi-common/blob/master/core/openapi/schemas/linkTemplate.yaml[linkTemplate.yaml],  based on the https://github.com/opengeospatial/ogcapi-common/blob/master/core/openapi/schemas/link.json[schema for a link] that includes substitution variables who's values are filled in at runtime prior to resolving the link.  

Information about the substitution variables can be obtained in one of two ways.  The `variable` property may be used to encode the definitions of substitution variables in-line in the link.  Alternatively, the `varBase` property can be used to specify a base URI to which a variable name may be appended in order to retrieve the definition of the specified substitution variable.

include::requirements/record-core/REQ_templated-link.adoc[]

include::recommendations/record-core/REC_templated-link.adoc[]

The following example illustrates a link template to a legacy OGC Web service.  The example includes both an in-line and referenced dictionaries of substitution variables.

[#templated-link-with-variables-inline,reftext=`Templated link example 1`]
.Templated link with in-line dictionary of substitution variables
[source,json]
----
include::../examples/json/templated-link-inline.json[]
----

[#templated-link-with-variables-ref,reftext=`Templated link example 2`]
.Templated link with `varBase` URI for retrieving substitution variable definitions
[source,json]
----
include::../examples/json/templated-link-ref.json[]
----

[#variable-def,reftext=`Variable definition example`]
.Using `varBase` to retrieve the definition of the variable bbox
----
   CLIENT                                                     SERVER
     |                                                           |
     |   GET variables/bbox HTTP/1.1                             |
     |   Host: www.someserver.com                                |
     |   Accept: application/json                                |
     |---------------------------------------------------------->|
     |                                                           |
     |   HTTP/1.1 200 OK                                         |
     |   Content-Type: application/json                          |
     |                                                           |
     |   {                                                       |
     |     "bbox": {                                             |
     |       "description": "...",                               |
     |       "type": "array",                                    |
     |       "items": {                                          |
     |         "type": "number",                                 |
     |         "format": "double"                                |
     |       },                                                  |
     |       "minItems": 4,                                      |
     |       "maxItems": 4                                       |
     |     }                                                     |
     |   }                                                       |
     |<----------------------------------------------------------|
----

==== Resource timestamps

A <<core-queryables,record>> contains information, encoded in the links and link templates sections, for accessing one or more resources described by the record.  Since a resource may have multiple representations there may be multiple links pointing to each represention of a resource.  Furthermore, representations of a resource may be created and updated at different times.  In order to capture this life cycle information of resource representations, the https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/common/link.yaml[link schema] is extended with the addition of two properties named `created` and `updated`.  The values of these properties are used to indicate the creation and last updated dates of the resource representation pointed to by the link.

[[sc_record_language_handling]]
==== Language handling

===== Overview

A catalogue record can include language information about:

* the resource that the record describes,
* the language used for text values in the current record representation,
* and alternate languages in which the current record can be represented.

===== Language of the record

include::recommendations/record-core/REC_record-lang.adoc[]

The https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/common/link.yaml[link object] and the https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/common/linkTemplated.yaml[templated link object] are based on https://docs.ogc.org/is/17-069r4/17-069r4.html#rfc8228[RFC 8288 (Web Linking)] includes a `hreflang` attribute that can be used to state the language of a referenced resource.  This can be used to include links to the same record in different languges.  

[[minting-language-specific-uris]]
A server that wants to use language-specific links will have to support a mechanism to mint language-specific URIs in order to express links to the same record in other languages or to express links to the resource described by record in multiple languages.  This document does not mandate any particular approach how such a capability is supported by a server. 

[NOTE]
=====================================================================
Two common approaches are:

* an additional path element for each language-specific encoding of a record or resource (this can be expressed, for example, using a language-specific path element like `.../en-ca/...`);

* an additional query parameter (for example, https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/parameter/language.yaml["language"] or "l") that overrides the Accept-Language header of the HTTP request.
=====================================================================

[NOTE]
=====================================================================
There is no provision in the record schema to allow a response containing text fields simultaneously presented in multiple languages (e.g. multiple titles in different languages).  To obtain a record in multiple languages would require multiple requests to the server each negotiating to a desired language.
=====================================================================

===== Language of the resource

include::recommendations/record-core/REC_resource-langs.adoc[]
