[[overview]]
== Overview

[[records-role]]
=== Role of OGC API - Records

Historically, catalogues have been used as large repositories of formal metadata like ISO 19119, ISO 19115, FGDC, etc. More recently, catalogues are migrating to a more distributed model where the metadata is intimately associated with the resource that it describes. A current example is STAC which relies on well-defined building blocks that can be integrated in different ways.

Although OGC API - Records is built upon the legacy of CSW, its role in a modern SDI can be both: a large repository of metadata documents or a distributed catalogue, with the ability to provide a static or dynamic capability.

In the modern scenario, the catalogue records can be distributed and linked together so that they can be crawled or they can be harvested into a service endpoint to make them searchable. In addition, a searchable catalogue can harvest not only a metadata document describing the resource but in some cases the resource itself (e.g. harvesting the collections object from an OGC API). The implications of this are subtle yet important. In the traditional cataloguing approach (e.g. based on CSW) a client could find the record and the record might include binding information to access the resource but that is pretty much it. Using the new approach, a client interacts more intimately with the catalogue and the catalogue becomes integral to the access to the resource. An example is the cloud native ecosystem: HTTP range requests to Cloud Optimized GeoTIFF (COG) data cannot be used properly unless there is a STAC item telling the client in what ranges the bands exists, thus the catalogue becomes an integral component in the process of accessing a resource.

[[general-overview]]
=== General

The atomic unit of information in a catalogue is the _record_.

A _catalogue_ is a collection of _records_.  The terms **collection of records** and **catalogue** are used interchangeably in this specification.

A record provides a summary description (metadata) of a resource that the provider of the resource wishes to make discoverable.  The record schema defined in this specification includes a small number of properties that can be used to provide a summary description of any resource.  It is anticipated, and encouranged, that this list of properties be extended to enhance the information content of a record as required by specific communities of interest and/or use cases.

=== Building blocks

This standard defines three building blocks that may be used to deploy a catalogue:

. The _core_ schema of a record.
. The definition of a _collection_ resource that groups and describes a set of related records (i.e. a catalogue).
. An API that allows collections of records (i.e. a catalogue) to be searched using logically connected predicates that can include spatial and/or temporal predicates.

Using these building blocks a catalogue can be deployed as:

* a set of web-accessible records that can be crawled by a search engine crawler or by using (for example) a web browser
* a searchable catalogue with records accessible through an API

A special use case of the _searchable catalogue_ is the _**local resources catalogue**_.  The OGC API resource tree has a number of endpoints that provide lists of resources.  Examples of such endpoints include the `/collections` and the `/processes` endpoints.  One can readily imagine a large OGC API deployment with thousands of collections where the ability to search would enhance the client's interaction with the server.  Using the building blocks defined in this specification these endpoints can be extended to support catalogue-like searching using filter expressions that may also include spatial and/or temporal predicates.  OGC API endpoints extended in this way behave like a catalogue of local resources.

[[record-schema-overview]]
=== Record Schema

The core set of record properties that may be used to describe a resource
include the  _recordId_, _time_, _type_, _title_, _description_ and _geometry_.
A complete definition of a record can be found in clause <<core-queryables,Core queryables>>.

The choice of which properties to include in the set of core queryables was primarily informed by the following record models:

* The http://docs.opengeospatial.org/is/12-168r6/12-168r6.html#17[core catalogue schema] from the https://www.ogc.org/standards/cat[OGC® Catalogue Services 3.0] suite of standards,
* the https://www.w3.org/TR/vocab-dcat/[Data Catalog Vocabulary (DCAT) - Version 2] and the https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.58/2017/mtg3/2017-UNECE-topic-i-EC-GeoDCAT-ap-paper.pdf[GeoDCAT-AP] specifications.

It is expected that the information necessary to populate this core set of properties is readily available for any resource that is being made discoverable by the record.

It is anticipated that this _core_ set of properties will be extended to describe specific resource types (e.g. datasets, dataset series, Earth observation products, machine models, services, etc.) and also extended by information communities wishing to enrich the information content of the record to suit their needs.  Extending the information content of a record to suite specific needs is allowed and encouraged by this specification.

Although this document does not mandate any particular encoding for a record, the document does define conformance classes for two encodings:

* A <<requirements-class-geojson-clause,GeoJSON>> record encoding,
* and an <<requirements-class-html-clause,HTML>> encoding.

Other encodings are allowed but are not described in this document.

Accessing collections of records deployed as static files is described in the <<clause-crawlable-catalogue,Crawlable records deployment>> clause.

Accessing collections of records through the API defined in this document is described in the <<records-access,Records access>> and <<record-access,Record access>> sections.

[[sc_record-collection-overview]]
=== Record collection (catalogue)

A record collection or catalogue is an object that groups and describes a set of related <<record-schema-overview,records>>.  The collection resource is the primary access point from which a deployed set of records can be accessed.  Having found the collection resource (i.e. the catalogue) a client can, by following the appropriate hypermedia controls contained therein, navigate to the records of the collection.  

Depending on the deployment pattern, the collection may provide a link to each individual record of the collection or a link to a search access point for retrieving sub-sets of records.

The core set of properties that may be used to describe a record collection or catalogue include _id_, _type_, _title_, _description_, _extent_ and _links_.  A complete definition of a record can be found in clause<<clause-record-collection,Record collection>>.  It should be noted that this list of properties is very similar to the list of core properties defined for a <<record-schema-overview,catalogue record>>.  This is intentional since the record collection object can be considered a _record_ that describes a catalogue.

It is anticipated that this set of properties will be extended to enrich the information content of the collection metadata to suit specific needs.

[[sc_record_api]]
=== Records API

==== Overview 

The Records API allows a subset of records to be retrieved from a catalogue using a logically connected set of predicates that may include spatial and/or temporal predicates.

The Records API extends https://github.com/opengeospatial/ogcapi-common[OGC API - Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Core: Part 1] to:

. Provide modern API patterns and encodings to facilitate further lowering the barrier to finding the existence of spatial resources on the Web.
. Provide functionality comparable to that of the <<api-behaviour-model-overview,OGC Catalogue Service (CSW) standard>> so that a facade can be created over legacy services thus allowing them to participate in the new OGC API ecosystem.

Collections of records exposed though this OGC API may be accessed through an https://www.ogc.org/standards/ogcapi-features[OGC API - Features API] that has been:

* extended with <<records-access,additional parameters>> at the `/collections/{collectionId}/items` endpoint,
* and constrained to a single <<record-overview,information model>> (i.e. the <<record-overview,record>>).

<<record-api-paths>> summarizes the access paths and relation types defined in this standard.

[[records-paths]]
[#record-api-paths,reftext='{table-caption} {counter:table-num}']
.Record API Paths
[width="90%",cols="40,^20,40",options="header"]
|===
^|**Path Template** ^|**Relation** ^|**Resource** 
3+^|**Common**
|<<landing-page,{root}/>> |none |Landing page
|<<api-definition,{root}/api>> |`service-desc` or `service-doc` |API Description (optional)
|<<conformance-classes,{root}/conformance>> | `conformance` |Conformance Classes
|<<collections,{root}/collections>> | `data` |Metadata describing the spatial collections available from this API.
|<<collectionInfo,{root}/collections/{collectionId}>> | |Metadata describing the collection which has the unique identifier `{collectionId}`
3+^|**Records**
|<<records-access,{root}/collections/{collectionId}/items>> |`items` |Search results based on querying the service for records satisfying 0..n query parameters.
|<<record-access,{root}/collections/{collectionId}/items/{recordId}>> |`item` |Record of metadata which has the unique identifier `{recordId}`.
|===

Where:

* {collectionId} = an identifier for a specific record collection (i.e. catalogue identifier)
* {recordId} = an identifier for a specific record within a collection

[[api-behaviour-model-overview]]
==== API Behaviour Model

The Records API is designed to be compatible but not conformant with the http://docs.opengeospatial.org/is/12-176r7/12-176r7.html[OGC Catalogue Service for the Web (CSW)]. This allows OGC API - Records implementations and CSW implementations to co-exist in a single processing environment.

The https://www.opengeospatial.org/standards/cat[OGC Catalogue Service standard version 3] provides an abstract core model of metadata (data about data) describing a number of different information types (datasets, services, styles, processes, etc.) on which the classic operations GetCapabilities, DescribeRecord, GetRecords, and GetRecordById can be explained naturally. This model consists of a 1..n catalogue collections residing in a CSW backend repository. It holds service metadata describing service qualities (identification, contact, operations, filtering capabilities, etc.). At its heart, a catalogue may provide discovery services to any number of metadata repositories. The core catalogue model is based on an extension of Dublin Core (CSW Record). Application profiles can be developed to target specific metadata information models (such as ISO 19115/19139, etc.).

Discussion has shown that the API model also assumes underlying service and object descriptions, so a convergence seems possible. In any case, it will be advantageous to have a similar "mental model" of the server store organization on hand to explain the various functionalities introduced below.

==== Search

This specification defines three levels of search capability of increasing complexity and capability.

The first or core level of search capability is based on <<OAFeat-1,OGC API - Features>> and thus supports:

* bounding box searches,
* time instant or time period searches,
* and equality predicates (i.e. _property_=_value_).

OGC API - Record extends these core search capabilities to include:

* searches based on a subset of core queryables (e.g. by resource type, by external identifier).
* keyword searches

The second level of search capability extends the search API so that it is compatible with the https://portal.opengeospatial.org/files/?artifact_id=56866[OGC OpenSearch Geo and Time Extensions] (OpenSearch Geo).  OpenSearch Geo gives the user more control over the kinds of geometries, beyond a bounding box, that can be used to define an area of interest.  https://fix.me[OGC API - Records - Part 2: OpenSearch] defines the requirements for a catalogue that supports OpenSearch.

The third level of search capability, defined by the <<clause-record-filter,_Filter using the Common Query Language_ Requirements Class>>, supports complex filter expressions using a rich set of logically connected query predicates.

[[dependencies-overview]]
==== Dependencies

The OGC API - Records standard is an extension of the https://github.com/opengeospatial/ogcapi-common[OGC API - Common] and the https://www.ogc.org/standards/ogcapi-features[OGC API - Features] standards.

An implementation of OGC API - Records must first satisfy the appropriate Requirements Classes from API - Common and OGC API - Features.  <<req-mappings>>, identifies the OGC API - Common and OGC API - Features Requirements Classes which are applicable to each section of this Standard. Instructions on when and how to apply these Requirements Classes are provided in each section.

[#req-mappings,reftext='{table-caption} {counter:table-num}']
.Required OGC API - Common and OGC API - Features Requirements Classes
[width="90%",cols="2,6"]
|====
^|*API - Record Section* ^|*OGC API - Common, OGC API - Features Requirements Class*
|<<landing-page,API Landing Page>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<api-definition,API Definition>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<conformance-classes,Declaration of Conformance Classes>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<collection-access-section,Collections>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|<<records-access,Records>>|<<records-to-features>>
|<<record-access,Record>>|<<record-to-features>>
|<<requirements-class-openapi_3_0-clause,OpenAPI 3.0>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/oas30
|<<requirements-class-json-clause,JSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/geojson
|<<requirements-class-html-clause,HTML>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/html
|====

[#records-to-features,reftext='{table-caption} {counter:table-num}']
.Required OGC API - Features Requirements Classes for Records Access
[width="90%"]
|====
|*API - Features Requirements Classes*
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-op
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-bbox-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-bbox-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-limit-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-limit-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-time-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-time-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/query-param-invalid
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/query-param-unknown
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-links/req/core/fc-rel-type
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-timeStamp
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-numberMatches
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-numberReturned,
|====

[#record-to-features,reftext='{table-caption} {counter:table-num}']
.Required OGC API - Features Requirements Classes for Record Access
[width="90%"]
|====
|*API - Features Requirements Classes*
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/f-op
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/f-success
|====
