[[clause-crawlable-catalogue]]
== Requirements Class "Crawlable Catalogue"

[[crawlable-catalogue-overview]]
=== Overview

include::requirements/requirements_class_crawlable-catalogue.adoc[]

The `Crawlable Catalogue` Requirements Class defines the requirements for a catalogue composed of static, web-accessible files.

The goal of a crawlable catalogue is to expose metadata about resources online with as low an entry barrier as possible, thus making those resource more easily discoverable.

A crawlable catalogue is a deployment pattern that uses the <<clause-core-record-collection,collection>> and <<clause-record-core,record>> building blocks defined in this standard.  It is simply a set of files deployed on the web that encode, usually in HTML or JSON, the <<clause-record-collection,collection>> and <<clause-record-core,record schema>> defined in this standard.  The files contain embedded links to enable navigation from one to another.  Any HTTP server or cloud storage service, for example, could be used to expose the files of a crawlable catalogue.

A crawlable catalogue is not searchable and does not respond to query requests.  As the name implies, it can only be crawled (or harvested) by following the embedded links; typically by search engines and other active catalogues or browsed using a web browser.  However, due to its simplicity, a crawlable catalogue is easy to deploy and maintain, and is very reliable.

[[crawlable-catalogue-record]]
=== Making a resource discoverable

include::requirements/crawlable-catalogue/REQ_record.adoc[]

Attention is drawn to requirement <<per_core_additional-properties-record,/per/core/additional-properties-record>> that allows the information content of the record to be enriched as required to describe the resource being made discoverable.

include::requirements/crawlable-catalogue/REQ_record-links.adoc[]

include::requirements/crawlable-catalogue/REQ_record-file-location.adoc[]

include::recommendations/crawlable-catalogue/REC_record-file-name.adoc[]

include::recommendations/crawlable-catalogue/REC_record-file-location.adoc[]

For example, the record file could be placed in the same web-accessible directory or object store as the resource(s) that the record describes.

[[crawlable-catalogue]]
=== Grouping a collection of records into a catalogue

include::requirements/crawlable-catalogue/REQ_collection.adoc[]

include::requirements/crawlable-catalogue/REQ_collection-location.adoc[]

include::requirements/crawlable-catalogue/REQ_collection-links.adoc[]

=== Collections of catalogue resources

In order to provide flexibility with regard to how crawlable catalogues can be organized (e.g. a hierarchy) a _collections object_ is defined that may be used as a common entry point for crawling to multiple, related, sub-collections, catalogues, records and other resources.

<<collections-properties-table>> defines the set of properties for a collections object.

[#collections-properties-table,reftext='{table-caption} {counter:table-num}']
.Table of properties for a collections object
[cols="30,5,65",options="header"]
|===
|Queryables |Requirement |Description
|_**id**_ |**required** |A unique identifier for this collections object.
|_**title**_ |**required** |A human-readable name given to this collections object.
|_**description**_ |optional |A free-text description of this collections object.
|_**links**_ |**required** |A list of links for navigating to the resources (i.e. collections, catalogues, items, other resources) of this collections  object.
|_**extent**_ |optional |The spatio-temporal coverage of this collections object.
|_**crs**_ |optional |A list of coordinate reference systems used for spatial-temporal values.
|type |**required** |The nature or genre of this resource. Fixed to "Collection".
|keywords |optional |A list of free-form keywords or tags associated with this collections object.
|language |optional |The natural language used for textual values (i.e. titles, descriptions, etc) of this collections object.
|created |optional |The date this collections object was created.
|updated |optional |The more recent date on which this collections object was changed.
|contacts |optional |A list of contacts qualified by their role(s).
|themes |optional |A knowledge organization system used to classify this collections object.
|license |optional |A legal document under which this collections object is made available.
|rights |optional |A statement that concerns all rights not addressed by the license such as a copyright statement.
|===

include::requirements/crawlable-catalogue/REQ_collections.adoc[]

include::recommendations/crawlable-catalogue/PER_additions-collections-properties.adoc[]

include::requirements/crawlable-catalogue/REQ_collections-links.adoc[]

include::recommendations/crawlable-catalogue/REC_collections-links.adoc[]
