== Requirements Class "Core"

[[core-overview]]
=== Overview

include::requirements/requirements_class_core.adoc[]

The `Core` Requirements Class defines the requirements for locating, understanding, and accessing Record resources. The `Core` Requirements Class is presented in five sections:

. <<api-platform-section,API Platform>>: a set of common capabilities
. <<collection-access,Collection Access>>: operations for accessing information about collections of records
. <<records-access,Records Access>>: operations for accessing record resources
. <<record-access,Record Access>>: operations for accessing a single record
. <<general-section,General>>: general principles for use with this standard

[[core-dependencies-section]]
=== Dependencies

The OGC API - Records standard is an extension of the OGC API - Common standard. Therefore, an implementation of API - Records must first satisfy the appropriate Requirements Classes from API - Common.

include::requirements/core/REQ_api-common.adoc[]

[[api-platform-section]]
=== Platform

API - Common defines a set of common capabilities which are applicable to any OGC Web API. Those capabilities provide the platform upon which resource-specific APIs can be built. This section describes those capabilities and any modifications needed to better support Record resources.

[[landing-page]]
==== API landing page

The landing page provides links to start exploration of the resources offered by an API. Its most important component is a list of links. OGC API - Common already requires some common links. Those links are sufficient for this standard.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

The `Landing Page` operation is defined in the `Core` conformance class of API - Common. No modifications are needed to support `Record` resources. The `Core` conformance class specifies only one way of performing this operation:

. Issue a `GET` request on the `{root}/` path

Support for `GET` on the `{root}/` path is required by API - Common.

===== Response

A successful response to the `Landing Page` operation is defined in API - Common. The schema for this resource is provided in <<landingPage-schema>>.

[#landingPage-schema,reftext='Landing Page Response Schema']
.Landing Page Response Schema
[source,yaml]
----
include::../openapi/schemas/common/landingPage.yaml[]
----

The following JSON fragment is an example of a response to an OGC API - Records Landing Page operation.

[#landingPage-example,reftext=`Landing Page Example`]
.Landing Page Example
[source,json]
----
include::../examples/json/landingPage.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[api-definition]]
==== API definition

Every API is required to provide a definition document that describes the capabilities of that API. This definition document can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of API - Common. No modifications are needed to support `Records` resources. The `Core` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{root}/api` path
. Follow the `service-desc` or `service-doc` link on the landing page

Only the link is required by API - Common.

===== Response

A successful response to the API Definition request is a resource which documents the design of the API. API - Common leaves the selection of format for the API Definition response to the API implementor. However, the options are limited to those which have been defined in the API - Common standard. At this time OpenAPI 3.0 is the only option provided.

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[conformance-classes]]
==== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the conformance classes it claims to have implemented.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of API - Common. No modifications are needed to support `Records` resources. The `Core` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{root}/conformance` path
. Follow the `conformance` link on the landing page

Both techniques are required by API - Common.

===== Response

A successful response to the Conformance operation is a list of URLs. Each URL identifies an OGC Conformance Class for which this API claims conformance. The schema for this resource is defined in API - Common and provided for reference in <<conformance-schema>>.

include::requirements/core/REQ_conformance.adoc[]

include::recommendations/core/PER_additional-conformance.adoc[]

[#conformance-schema,reftext='Conformance Response Schema']
.Conformance Response Schema
[source,yaml]
----
include::../openapi/schemas/common/confClasses.yaml[]
----

The following JSON fragment is an example of a response to an OGC API - Records conformance operation.

[#conformance-example,reftext=`Conformance Information Example`]
.Conformance Information Example
[source,json]
----
include::../examples/json/conformance.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[collection-access]]
=== Collection Access

API - Common starts with the assumption that spatial resources are organized into collections. An API will expose one or more collections. The API - Common Collections Conformance Class defines how to organize and provide access to a collection of collections.

This standard extends the API - Common `Collections` conformance class to support collections of records, then extends that class to support `Record` unique capabilities.

[[collections]]
==== Record Collections

The `Collections` operation returns a set of metadata which describes the collections available from this API.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|====

===== Operation

This operation is defined in the `Collections` conformance class of API - Common. No modifications are needed to support `Record` resources. The `Collections` conformance class describes two ways of performing this operation:

. Issue a `GET` request on `{root}/collections` path
. Follow the `data` link on the landing page

Support for both the `{root}/collections` path and the `data` link is required by API - Common.

===== Response

A successful response to the `Collections Operation` is a document which includes summary metadata for each collection accessible though the API.

In a typical deployment the collections response will list collections of all offered resource types.  The collections labeled with an `itemType` of `record` are catalogues (i.e. collections of records).

[#collections-schema,reftext='Collections Response Schema']
.Collections Response Schema
[source,yaml]
----
include::../openapi/schemas/common/collections.yaml[]
----

The following JSON fragment is an example of a response to an OGC API - Records Collections operation.

[#conllections-example,reftext=`Collections Example`]
.Collections Example
[source,json]
----
include::../examples/json/collections.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[collectionInfo]]
==== Collection Information

Collection Information is the set of metadata which describes a single collection. An abbreviated copy of this information is returned for each Collection in the `/collections` response.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|====

===== Operation

This operation is defined in the `Collections` conformance class of API - Common. No modifications are required to support `Records` resources.

. Issue a `GET` request on the `{root}/collections/{collectionid}` path

The {collectionid} parameter is the unique identifier for a single collection on the API. The list of valid values for {collectionid} is provided in the /collections response.

Support for the `/collections/{collectionid}` path is required by API - Common.

===== Response

A successful response to the Collection Operation is a set of metadata which describes the collection identified by the {collectionid} parameter.

[#collectionInfo-schema,reftext='Collection Information Response Schema']
.Collection Information Response Schema
[source,yaml]
----
include::../openapi/schemas/common/collectionInfo.yaml[]
----

The following JSON fragment is an example of a response to an OGC API - Records Collection Information operation.

[#collection-info-example,reftext=`Collection Information Example`]
.Collection Information Example
[source,json]
----
include::../examples/json/collection.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[records-access]]
=== Records Access

==== Operation

include::requirements/core/REQ_rc-op.adoc[]

[[parameters-section]]
==== Parameters

===== Overview

The following tables list the set mandatory query parameters.

[[core-query-parameters-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of Query Parameters
[cols="15,85",options="header"]
|===
|Parameter name |Description
|bbox |A bounding box. If the spatial extent of the record intersects the specified bounding box then the record shall be presented in the response document.
|datetime |A time instance or time period. If the temporal extent of the record intersects the specified data/time value then the record shall be presented in the response document.
|limit |The number of records to be presented in a response document.
|q |A comma-separated list of search terms. If any server-chosen text field in the record contains 1 or more of the terms listed then this records shall appear in the response set.
|type |An equality predicate consistent of a comma-separated list of resource types.  Only records of the listed type shall appear in the resource set.
|externalid |An equality predicate consistent of a comma-separated list of external resource identifiers. Only records with the specified external identifiers shall appear in the response set.
|===

The query parameters `bbox`, `datetime` and `limit` are inherited from API -Common.  All requirements and recommendations in API - Common regarding these parameters also apply for API - Records.

The query parameters `q`, `type` and `externalid` are specific to API - Records.
This clause provides a brief description of the query parameters inherited from API - Common and requirements for the API - Records-specific parameters.

[[core-query-parameters-bbox]]
===== Parameter bbox

The Bounding Box (bbox) parameter is defined in API - Common. The following requirement governs use of that parameter in a Records API.

include::requirements/core/REQ_param-bbox.adoc[]

[[core-query-parameters-datetime]]
===== Parameter datetime

The Date-Time (datetime) parameter is defined in API - Common. The following requirement governs use of that parameter in a Records API.

include::requirements/core/REQ_param-datetime.adoc[]

[[core-query-parameters-limit]]
===== Parameter limit

The limit parameter is defined in API - Common. The following requirement governs use of that parameter in a Records API.

include::requirements/core/REQ_param-limit.adoc[]

[[core-query-parameters-q]]
===== Parameter q

include::requirements/core/REQ_param-q-definition.adoc[]

include::requirements/core/REQ_param-q-response.adoc[]

[[core-query-parameters-type]]
===== Parameter type

include::requirements/core/REQ_param-type-definition.adoc[]

include::requirements/core/REQ_param-type-response.adoc[]

[[core-query-parameters-externalid]]
===== Parameter externalid

include::requirements/core/REQ_param-externalid-definition.adoc[]

include::requirements/core/REQ_param-externalid-response.adoc[]

NOTE: I have chosen a small subset of core queryables (type, externalId) and mapped them as URL query parameters.  We could generalize this and say that any core queryable can be included as a URL query parameter.  Should we do this instead?

===== Combinations of Filtering Parameters

Any combination of query parameters from the <<core-query-parameters-table,Table of Query Parameters>> may be specified for filtering.

Any combination of `bbox`, `datetime`, `q` and `limit` parameters for filtering on Record properties is allowed. Note that the requirements on these parameters imply that only records matching all the predicates are in the result set; i.e., the logical operator between the predicates is 'AND' (exclusive).

==== Response

include::requirements/core/REQ_rc-response.adoc[]

include::recommendations/core/PER_additional-properties.adoc[]

[[core-queryables-record-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the catalogue record
[cols="20,5,55,20",options="header"]
|===
|Queryables |Requirement |Description |GeoJSON key
|recordId |M |A unique record identifier assigned by the server. |id
|record-created |O |The date this record was created in the server. |created
|record-updated |O |The most recent date on which the record was changed. |updated
|links |O |A list of links for navigating the API (e.g. link to previous or next pages; links to alternative representations, etc.) |links
|===

[[core-queryables-resource-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the resource
[cols="20,5,55,20",options="header"]
|===
|Queryables |Requirement |Description |GeoJSON key
|type |M |The nature or genre of the resource. |properties.type
|title |M |A human-readable name given to the resource. |properties.title

|description |O |A free-text description of the resource. |properties.description
|keywords |O |A list of keywords or tag associated with the resource. |properties.keyword
|language |O |This refers to the natural language used for textual values (i.e. titles, descriptions, etc) of a resource. |properties.language
|externalid |O |An identifier for the resource assigned by an external entity. |properties.externalid
|created |O |The date the resource was created. |properties.created
|updated |O |The more recent date on which the resource was changed. |properties.updated
|publisher |O |The entity making the resource available. |properties.publisher
|themes |O |A knowledge orgnaization system used to classify the resource. |properties.themes
|formats |O |A list of available distributions for the resource. |properties.formats
|contactpoint |O |An entity to contact about the resource. |properties.contactpoint
|license |O |A legal document under which the resource is made available. |properties.license
|rights |O |A statement that concerns all rights not addressed by the license such as a copyright statement. |properties.rights
|extent |O |The spatio-temporal coverage of the resource. |properties.extent
|associations |O |A list of links for accessing the resource, links to other resources associated with this resource, etc. |properties.associations
|===

==== Associations and Links

A record object contains both `links` and `properties.associations` properties.  The following
recommendations provide clarification on where and how to use these properties in a record.


[#association-uri-template-example,reftext=`Association URI Template Example`]
.Association URI Template Example
[source,json]
----
include::../examples/json/association-uri-template.json[]
----

The following recommendations provide clarification on where and how to use these properties in a record.

include::recommendations/core/REC_record-links.adoc[]

include::recommendations/core/REC_record-associations.adoc[]


==== Paged Response

One consequence of the Limit parameter is that the full result set is not delivered to the user. However, users frequently want to know how big the result set it and how to access the rest of it. The following requirement adds information to the response to address that need.

include::requirements/core/REQ_rc-paged-response.adoc[]

[[record-access]]
=== Record Access

==== Operation

include::requirements/core/REQ_record-op.adoc[]

==== Response

include::requirements/core/REQ_record-success.adoc[]

[[general-section]]
=== General

[[http-response]]
==== HTTP Response
Each HTTP request shall result in a response that meets the following requirement.

include::requirements/core/REQ_http-response.adoc[]

The YAML schema for these results is provided in <<http-response-schema>>.

[#http-response-schema,reftext='HTTP Response Schema']
.HTTP Response Schema
[source,yaml]
----
include::../openapi/schemas/common/exception.yaml[]
----

[[http-status-codes]]
==== HTTP status codes

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this standard. Status codes 200, 400, and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
|===
|Status code |Description
|`200` |A successful request.
|`304` |An <<web_caching,entity tag was provided in the request>> and the resource has not been changed since the previous request.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorised to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |The `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
|===

More specific guidance is provided for each resource, where applicable.

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

include::recommendations/core/PER_additional-status-codes.adoc[]
