[[overview]]
== Overview

[[general-overview]]
=== General

This standard extends OGC API Common to:

. Provide modern API patterns and encodings to facilitate further lowering the barrier to finding the existence of spatial resources on the Web.
. Provide functionality comparable to that of the <<api-behavior-model-overview,OGC Catalogue Service (CSW) standard>> so that a facade can be created over legacy services thus allowing them to participate in the new OGC API ecosystem.

Resources exposed through an OGC API may be accessed through a Universal Resource Identifier <<rfc3986,(URI).>> URIs are composed of three sections:

* Service Offering: The service endpoint (subsequently referred to as Base URI or {root})
* Access Paths: Unique paths to Resources
* Query: Parameters to adjust the representation of a Resource or Resources like encoding format or subsetting

Some resources are also accessible through links on previously accessed resources. Unique relation types are used for each resource.

Collections of records exposed though this OGC API may be accessed through an https://www.ogc.org/standards/ogcapi-features[OGC API Features API] that has been:

* constrained to a single <<record-schema-overview,information model>>,
* extended with additional query parameters at the <<records-access,records access>> endpoint (i.e. `/collections/{collectionId}/items`).

The following table, <<records-paths,Record API Paths>>, summarizes the access paths and relation types defined in this standard.

[[records-paths]]
[reftext='{table-caption} {counter:table-num}']
.Record API Paths
[width="90%",cols="40,20,40",options="header"]
|===
^|**Path Template** ^|**Relation** ^|**Resource** 
3+^|**Common**
|<<landing-page,{root}/>> |none |Landing page
|<<api-definition,{root}/api>> |`service-desc` or `service-doc` |API Description (optional)
|<<conformance-classes,{root}/conformance>> | `conformance` |Conformance Classes
|<<collections-access,{root}/collections>> | `data` |Metadata describing the spatial collections available from this API.
|<<collection-info,{root}/collections/{collectionId}>> | |Metadata describing the collection which has the unique identifier `{collectionId}`
3+^|**Records**
|<<records-access,{root}/collections/{collectionId}/items>> |`items` |Search results based on querying the service for records satisfying 0..n query parameters.
|<<record-access,{root}/collections/{collectionId}/items/{recordId}>> |`item` |Record of metadata which has the unique identifier `{recordId}`.
|===

Where:

* `{root}` = Base URI for the API server
* `{collectionId}` = an identifier for a specific collection of catalogue records
* `{recordId}` = an identifier for a specific record within a collection

[[record-schema-overview]]
=== Record Schema

The atomic unit of information in a catalogue is a record.

A record published in the catalogue contains a description of a resource.  A resource is any physical or digital asset that is being made discoverable through the catalogue.

A catalogue can be searched to identify subsets of records that satisfy search criteria specified by a client.

Having found one or more records of interst via a search, the client can then access (i.e. bind) the resource using the descriptive information contained in each record.

The following table lists the set of properties defined in this specification, called _**core queryables**_, that may be included in a catalogue record.

[#core-queryables-list,reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the catalogue record
[cols="2,5",options="header"]
|===
|Queryables |Description
|recordId |A unique record identifier assigned by the server.
|recordCreated |The date this record was created in the server.
|recordUpdated |The most recent date on which the record was changed.
|links |A list of links for navigating the API.
|type |The nature or genre of the resource.
|title |A human-readable name given to the resource.
|description |A free-text description of the resource.
|keywords |A list of keywords or tag associated with the resource.
|keywordsCodespace |A reference to a controlled vocabulary used for the keywords property.
|language |This refers to the natural language used for textual values.
|externalId |An identifier for the resource assigned by an external entity.
|created |The date the resource was created.
|updated |The more recent date on which the resource was changed.
|publisher |The entity making the resource available.
|themes |A knowledge orgnaization system used to classify the resource.
|formats |A list of available distributions for the resource.
|contactPoint |An entity to contact about the resource.
|license |A legal document under which the resource is made available.
|rights |A statement that concerns all rights not addressed by the license such as a copyright statement.
|extent |The spatio-temporal coverage of the resource.
|associations |A list of links for accessing the resource, links to other resources associated with this resource, etc.
|===

A complete definition of a record can be found in the query <<query-response,Response>> sub-clause of the <<record-access,Records access>> clause.

The choice of which properties to include in the set of core queryables was primarily informed by the following record models:

* The http://docs.opengeospatial.org/is/12-168r6/12-168r6.html#17[core catalogue schema] from the https://www.ogc.org/standards/cat[OGC® Catalogue Services 3.0] suite of standards,
* the https://www.w3.org/TR/vocab-dcat/[Data Catalog Vocabular (DCAT) - Version 2] and the https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.58/2017/mtg3/2017-UNECE-topic-i-EC-GeoDCAT-ap-paper.pdf[GeoDCAT-AP] specifications.

It is expected that the information necessary to populate this core set of record properties is readily available for any resource that is being registered in the catalogue.  

It is anticipated that this _core_ set of record properties will be extended to describe specific resource types (e.g. datasets, services, etc.) and also extended by information communities wishing to enrich the information content of the record to suit their needs.  Extending the information content of a record to suit specific needs is allowed and encouraged by this specification.

Although this document does not mandate any particular encoding for a record, the document does define conformance classes for three encodings:

* A <<record_json_encoding,GeoJSON>> record encoding,
* an <<record_atom_encoding,ATOM>> record encoding,
* and an <<record_html_encoding,HTML>> encoding.

Other encoding are allow but are not described in this document.

Accessing collections of records through the API defined in this document is described in the <<records-access,Records access>> section.

Accessing individual records through the API defined in this document is described in the <<record-access,Record access>> section.

=== Search

The primary search API for records is the Feature API which defines the following query parameters:

* a bounding box
* a time instant or time period
* limit

This standard extends this list of query parameters to allow searching for catalogue records using:

* keywords or free text,
* equality predicates based on a subset of the core queryables (e.g. by resource type, by external identifier)

This standard also includes a <<clause-opensearch,conformance class>> that allows a catalogue to be searched using https://portal.ogc.org/files/?artifact_id=56866[OpenSearch Geo].  OpenSearch Geo gives the user more control over the geometry types, that can be used to define an area of interest.

Finally, extensions such as the https://docs.ogc.org/DRAFTS/19-079.html[OGC API - Features - Part 3: Filtering and the Common Query Language (CQL)], may be used with this standard to support <<clause-cql-filter,complex search>> capabilities using a rich set of logically connected search predicates where the user has finer control over a query.

[[api-behavior-model-overview]]
=== API Behavior Model

The Records API is designed to be compatible with, but not conformant to, the OGC Catalogue Service for the Web (CSW). This allows OGC API - Records implementations and CSW implementations to co-exist in a single environment.  This also allows the Records API to be implmented as a facade on top of an existing CSW implementation.

The https://www.ogc.org/standards/cat[OGC Catalogue Service standard version 3] provides an abstract core model of metadata (data about data) describing a number of different information types (data, services, styles, processes, etc.) on which the classic operations GetCapabilities, DescribeRecord, GetRecords, and GetRecordById can be explained naturally. This model consists of a 1..n catalogue collections residing in a CSW backend repository. It holds service metadata describing service qualities (identification, contact, operations, filtering capabilities, etc.). At its heart, a catalogue may provide discovery services to any number of metadata repositories. The core catalogue model is based on an extension of Dublin Core (CSW Record). Application profiles can be developed to target specific metadata information models (such as ISO 19115/19139, etc.).

Discussion has shown that the API model also assumes underlying service and object descriptions, so a convergence seems possible. In any case, it will be advantageous to have a similar "mental model" of the server store organization on hand to explain the various functionalities introduced below.

[[dependencies-overview]]
=== Dependencies

This standard is an extension of the OGC API - Common standard. Therefore, an implementation of OGC API - Records must first satisfy the appropriate Requirements Classes from OGC API - Common. The following table, <<mapping-to-common,Mapping API - Records Sections to API - Common Requirements Classes>>, identifies the OGC API - Common Requirements Classes which are applicable to each section of this standard. Instructions on when and how to apply these Requirements Classes are provided in each section.

[[mapping-to-common]]
[reftext='{table-caption} {counter:table-num}']
.Mapping API - Records Sections to API - Common Requirements Classes
[width="90%",cols="2,6"]
|====
^|*API - Record Section* ^|*API - Common Requirements Class*
|<<landing-page,API Landing Page>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<api-definition,API Definition>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<conformance-classes,Declaration of Conformance Classes>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<collections-access,Collections>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|<<requirements-class-openapi_3_0-clause,OpenAPI 3.0>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/oas30
|<<requirements-class-json-clause,JSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/geojson
|<<requirements-class-html-clause,HTML>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/html
|====
