[[overview]]
== Overview

=== TLDR

In order to implements a catalogue that conforms to the _core_ if this standard:

* implmement the http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Core: Part 1] specification,
* implement the parameters defined in <<core-query-parameters-table>>,
* implement the record schema defined in <<core-queryables-record-table>> and <<core-queryables-resource-table>>.

[[general-overview]]
=== General

This standard, OGC API - Records - Part 1: Core, extends https://github.com/opengeospatial/ogcapi-common[OGC API Common] to:

. Provide modern API patterns and encodings to facilitate further lowering the barrier to finding the existence of spatial resources on the Web.
. Provide functionality comparable to that of the <<api-behavior-model-overview,OGC Catalogue Service (CSW) standard>> so that a facade can be created over legacy services thus allowing them to participate in the new OGC API ecosystem.

Records exposed through this OGC API may be accessed through a Universal Resource Identifier <<rfc3986,(URI)>>. URIs are composed of three sections:

* Service Offering: The service endpoint (subsequently referred to as Base URI or {root})
* Access Paths: Unique paths to Resources
* Query: Parameters to adjust the representation of a Resource or Resources like encoding format or subsetting

Some resources are also accessible through links on previously accessed resources. Unique relation types are used for each resource.

Collections of records exposed though this OGC API may be accessed through an https://www.ogc.org/standards/ogcapi-features[OGC API Features API] that has been:

* extended with <<records-access,additional parameters>> at the `/collections/{collectionId}/items` endpoint,
* and constrained to a single <<record-schema-overview,information model>> (called a **record**) that is extensible by communities of interest or to suite specific needs.

<<record-api-paths>> summarizes the access paths and relation types defined in this standard.

[[records-paths]]
[#record-api-paths,reftext='{table-caption} {counter:table-num}']
.Record API Paths
[width="90%",cols="40,^20,40",options="header"]
|===
|**Path Template** |**Relation** |**Resource** 
|<<landing-page,/>> |none |Landing page
|<<api-definition,/api>> |`service-desc` +
or +
`service-doc` |API Description (optional)
|<<conformance-classes,/conformance>> |`conformance` |Conformance Classes
|<<collections,/collections>> |`data` |Metadata describing the spatial collections available from this API.
|<<collectionInfo,/collections/{collectionId}>> | |Metadata describing the collection which has the unique identifier `{collectionId}`
|<<records-access,/collections/{collectionId}/items>> |`items` |Search results based on querying the service for records satisfying 0..n query parameters.
|<<record-access,/collections/{collectionId}/items/{recordId}>> |`item` |Record of metadata which has the unique identifier `{recordId}`.
|===

Where:

* {collectionId} = an identifier for a specific record collection identifier (i.e. catalogue identifier)
* {recordId} = an identifier for a specific record within a collection

[[record-schema-overview]]
=== Record Schema

The atomic unit of information in a catalogue is a record.

The following table lists the set or properties, called _**core queryables**_, that may be included in a catalogue record.

[#core-queryables-list,reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the catalogue record
[cols="2,5",options="header"]
|===
|Queryables |Description
|recordId |A unique record identifier assigned by the server.
|recordCreated |The date this record was created in the server.
|recordUpdated |The most recent date on which the record was changed.
|links |A list of links for navigating the API.
|type |The nature or genre of the resource.
|title |A human-readable name given to the resource.
|description |A free-text description of the resource.
|keywords |A list of keywords or tag associated with the resource.
|keywordsCodespace |A reference to a controlled vocabulary used for the keywords property.
|language |This refers to the natural language used for textual values.
|externalId |An identifier for the resource assigned by an external entity.
|created |The date the resource was created.
|updated |The more recent date on which the resource was changed.
|publisher |The entity making the resource available.
|themes |A knowledge orgnaization system used to classify the resource.
|formats |A list of available distributions for the resource.
|contactPoint |An entity to contact about the resource.
|license |A legal document under which the resource is made available.
|rights |A statement that concerns all rights not addressed by the license such as a copyright statement.
|extent |The spatio-temporal coverage of the resource.
|associations |A list of links for accessing the resource, links to other resources associated with this resource, etc.
|===

A complete definition of a record can be found in clause <<core-queryables,Core queryables>>.

The choice of which properties to include in the set of core queryables was primarily informed by the following record models:

* The http://docs.opengeospatial.org/is/12-168r6/12-168r6.html#17[core catalogue schema] from the https://www.ogc.org/standards/cat[OGC® Catalogue Services 3.0] suite of standards,
* the https://www.w3.org/TR/vocab-dcat/[Data Catalog Vocabular (DCAT) - Version 2] and the https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.58/2017/mtg3/2017-UNECE-topic-i-EC-GeoDCAT-ap-paper.pdf[GeoDCAT-AP] specifications.

It is expected that the information necessary to populate this core set of properties is readily available for any resource that is being registered in the catalogue.  

It is anticipated that this _core_ set of properties will be extended to describe specific resource types (e.g. datasets, services, etc.) and also extended by information communities wishing to enrich the information content of the record to suit their needs.

Although this document does not mandate any particular encoding for a record, the document does define conformance classes for three encodings:

* A <<record_json_encoding,GeoJSON>> record encoding,
* an <<record_atom_encoding,ATOM>> record encoding,
* and an <<record_html_encoding,HTML>> encoding.

Other encoding are allow but are not described in this document.

Accessing collections of records through the API defined in this document is described in the <<records-access,Records access>> section.

Accessing individual records through the API defined in this document is described in the <<record-access,Record access>> section.

[[api-behavior-model-overview]]
=== API Behavior Model

The Records API is designed to be compatible but not conformant with the OGC Catalogue Service for the Web (CSW). This allows OGC API - Records implementations and CSW implementations to co-exist in a single processing environment.

The https://www.opengeospatial.org/standards/cat[OGC Catalogue Service standard version 3] provides an abstract core model of metadata (data about data) describing a number of different information types (data, services, styles, processes, etc.) on which the classic operations GetCapabilities, DescribeRecord, GetRecords, and GetRecordById can be explained naturally. This model consists of a 1..n catalogue collections residing in a CSW backend repository. It holds service metadata describing service qualities (identification, contact, operations, filtering capabilities, etc.). At its heart, a catalogue may provide discovery services to any number of metadata repositories. The core catalogue model is based on an extension of Dublin Core (CSW Record). Application profiles can be developed to target specific metadata information models (such as ISO 19115/19139, etc.).

Discussion has shown that the API model also assumes underlying service and object descriptions, so a convergence seems possible. In any case, it will be advantageous to have a similar "mental model" of the server store organization on hand to explain the various functionalities introduced below.

=== Search

The Records API offers various levels of search capability of escalating complexity and capability.  At the core is the ability to search the catalogue by specifying:

* a bounding box
* a time instant or time period
* keywords
* free text
* equality predicates (i.e. _property_=_value_) based on a subset of core queryables (e.g. by resource type, by external identifier)

This specification also includes a <<clause-opensearch,conformance class>> that allows a catalogue to be searched using  https://portal.opengeospatial.org/files/?artifact_id=56866[OpenSearch Geo].  OpenSearch Geo gives the user more control over the kinds of geometries, beyond a bounding box, that can be used to define an area of interest.

Finally, the <<clause-record-filter,_Filter using the Common Query Language_ Requirements Class>> may be used to support complex search capabilities using a rich set of logically connected search predicates where the user has full control over to query expression.

[[dependencies-overview]]
=== Dependencies

The OGC API - Records standard is an extension of the https://github.com/opengeospatial/ogcapi-common[OGC API - Common] and the https://www.ogc.org/standards/ogcapi-features[OGC API - Features] standards.

An implementation of OGC API - Records must first satisfy the appropriate Requirements Classes from API - Common and OGC API - Features.  <<req-mappings>>, identifies the OGC API - Common and OGC API - Features Requirements Classes which are applicable to each section of this Standard. Instructions on when and how to apply these Requirements Classes are provided in each section.

[#req-mappings,reftext='{table-caption} {counter:table-num}']
.Required OGC API - Common and OGC API - Features Requirements Classes
[width="90%",cols="2,6"]
|====
^|*API - Record Section* ^|*OGC API - Common, OGC API - Features Requirements Class*
|<<landing-page,API Landing Page>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<api-definition,API Definition>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<conformance-classes,Declaration of Conformance Classes>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<collection-access-section,Collections>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|<<records-access,Records>>|<<records-to-features>>
|<<record-access,Record>>|<<record-to-features>>
|<<requirements-class-openapi_3_0-clause,OpenAPI 3.0>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/oas30
|<<requirements-class-json-clause,JSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/geojson
|<<requirements-class-html-clause,HTML>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/html
|====

[#records-to-features,reftext='{table-caption} {counter:table-num}']
.Required OGC API - Features Requirements Classes for Records Access
[width="90%"]
|====
|*API - Features Requirements Classes*
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-op
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-bbox-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-bbox-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-limit-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-limit-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-time-definition
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-time-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/query-param-invalid
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/query-param-unknown
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-response
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-links/req/core/fc-rel-type
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-timeStamp
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-numberMatches
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/fc-numberReturned,
|====

[#record-to-features,reftext='{table-caption} {counter:table-num}']
.Required OGC API - Features Requirements Classes for Record Access
[width="90%"]
|====
|*API - Features Requirements Classes*
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/f-op
| http://www.opengis.net/spec/ogcapi_features-1/1.0/req/core/f-success
|====
