[[clause-core-record-collection]]
== Requirements Class "Record Collection"

[[core-record-collection-overview]]
=== Overview

include::requirements/requirements_class_record-collection.adoc[]

The Record Collection requirements class defines the requirements for a collection.

A collection is an object that provides information about and access to a set of related <<clause-core-record,records>> also known as a catalogue.  You can think of a collection resource as a record that describes a catalogue.

The schema for the collection resource is an extension of the collection schema defined in http://docs.opengeospatial.org/DRAFTS/20-024.html#collection-description[OGC API - Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API - Features].

While http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API - Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API - Features] define a specific location for the collection resource (path: `/collections/{collectionId}`), OGC API Records only fixes the location of the collection in the <<clause-record-api,Record API>> conformance class.  Otherwise the collection resource can live anywhere the provider wishes to place it including as a static file in web space (e.g. a web-accessible directory or an S3 bucket).

[[record-collection-schema]]
==== Schema of a record collection

<<collection-properties-table>> defines the set of properties that may be used to describe a collection.

[#collection-properties-table,reftext='{table-caption} {counter:table-num}']
.Table of collection properties
[cols="30,5,65",options="header"]
|===
|Queryables |Requirement |Description
|_**id**_ |M |A unique identifier to the collection.
|_**title**_ |M |A human-readable name given to the collection.
|_**description**_ |O |A free-text description of the collection.
|_**links**_ |M |A list of links for navigating the API (e.g. link to previous or next pages; links to alternative representations, etc.)
|_**extent**_ |O |The spatio-temporal coverage of the collection.
|_**itemType**_ |M |Fixed to the value "record".
|_**crs**_ |O |A list of coordinate reference system used for spatial-temporal values.
|type |M |The nature or genre of the resource. Fixed to "Collection".
|keywords |O |A list of keywords or tag associated with the collection.
|keywordsCodespace |O |A reference to a controlled vocabulary used for the keywords property.
|language |O |This refers to the natural language used for textual values (i.e. titles, descriptions, etc) of a collection.
|created |O |The date the collection was created.
|updated |O |The more recent date on which the collection was changed.
|publisher |O |The entity making the collection available.
|themes |O |A knowledge organization system used to classify the collection.
|contactPoint |O |An entity to contact about the collection.
|license |O |A legal document under which the collection is made available.
|rights |O |A statement that concerns all rights not addressed by the license such as a copyright statement.
|===

NOTE: The properties _id_, _title_, _description_, _links_, _extent_, _itemsType_ and _crs_ were inherited from http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API - Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API - Features].

include::requirements/record-collection/REQ_mandatory-queryables-collection.adoc[]

include::recommendations/record-collection/PER_additional-queryables-collection.adoc[]

==== Keywords and Themes

See <<sc_keywords_and_themes,Keywords and Themes>> for a record.

==== Links

T.B.D.

* If the catalogue is a <<clause-crawlable-catalogue,crawlable catalogue>>, then the collection shall contain one or more `rel=item` links to explicitly point to each record in the collection.
* If the catalogue is a <<clause-searchable-catalogue,searchable catalogue>>, then the collection shall contain a link, `rel=items`, that point to the search and/or access endpoint for the records of the collection.
** These links can be typed to allow for the possibility of alternate representations for each record.

NOTE: The `rel` `items` is inherited from OGC API - Features but should that `rel` actually be the standard IANA `rel` `search`?

==== Templated links with variables

See <<sc_templated_links_with_variables,Templated links with variables>> for a record.

==== Language negotiation

See <<sc_language_negotiation,Language negotiation>> for a record.
