[[catalog-deployments]]
== Catalog deployments

=== Overview

This clause uses the <<building-blocks,common components>> defined in this Standard to define various catalog deployments.

[[clause-crawlable-catalog]]
=== Requirements Class "Crawlable Catalog" (Deployment)

[[crawlable-catalog-overview]]
==== Overview

include::requirements/requirements_class_crawlable-catalog.adoc[]

The `Crawlable Catalog` Requirements Class defines the requirements for a catalog composed of static, web-accessible files.

The goal of a crawlable catalog is to expose metadata about resources online with as low an entry barrier as possible, thus making those resources more easily discoverable.

A crawlable catalog is a deployment pattern that uses the <<clause-record-collection,collection>> and <<clause-record-core,record>> common components defined in this Standard.  It is simply a set of files deployed on the web, usually encoded as HTML or JSON, that conform to the <<clause-record-collection,collection>> and <<clause-record-core,record>> schemas defined in this Standard.  The files contain embedded links to enable navigation from one to another.  Any HTTP server or cloud storage service, for example, could be used to expose the files of a crawlable catalog.

A crawlable catalog is not searchable and does not respond to query requests.  As the name implies, it can only be crawled (or harvested) by following the embedded links, typically by search engines and other active catalogs or browsed using a web browser.  However, due to its simplicity, a crawlable catalog is easy to deploy and maintain, and is very reliable.

NOTE: It should be pointed out that a <<clause-searchable-catalog,searchable catalog>> can also behave as a crawlable catalog as long as the requirements in this clause are satisfied by the <<clause-searchable-catalog,searchable catalog>> implementation.

[[crawlable-catalog-record]]
==== Making a resource discoverable

include::requirements/crawlable-catalog/REQ_record.adoc[]

Attention is drawn to requirement <<per_record-core_additional-properties-record,/per/record-core/additional-properties-record>> that allows the information content of the record to be enriched as required to describe the resource being made discoverable.

include::requirements/crawlable-catalog/REQ_record-location.adoc[]

include::recommendations/crawlable-catalog/REC_record-file-name.adoc[]

include::recommendations/crawlable-catalog/REC_record-file-location.adoc[]

For example, the record file could be placed in the same web-accessible directory or object store as the resource(s) that the record describes.

[[crawlable-catalog]]
==== Grouping a collection of records into a catalog

include::requirements/crawlable-catalog/REQ_catalog.adoc[]

include::requirements/crawlable-catalog/REQ_catalog-location.adoc[]

include::requirements/crawlable-catalog/REQ_conformance.adoc[]

[[crawlable-collections]]
==== Organizing crawlable catalogs

In order to provide flexibility with regard to how crawlable catalogs can be organized (e.g., series, hierarchy, etc.) a catalog can also provide information about and access to related catalogs.  As such, the <<clause-record-collection,Record Collection object>> can be used as a common entry point for crawling to multiple related catalogs, sub-catalogs, records and other resources.  

The relationships among catalogs and records are expressed as links in the <<catalog-links-section,links section>> of the catalog and the <<record-links-section,links section>> of the record.

See <<sc_catalog-catalog-links,"Other catalogs">> and <<sc_catalog-record-links,Records>>.

[[clause-searchable-catalog]]
=== Requirements Class "Searchable Catalog" (Deployment)

include::requirements/requirements_class_searchable-catalog.adoc[]

==== Overview

The Searchable Catalog Requirements Class defines the requirements for a catalog that is searchable through an API.  A searchable catalog is an implementation of the <<OAFeat-1,OGC API - Features - Part 1: Core>> Standard that uses a defined information model.  In the case of the OGC API - Records Standard, that information model is the <<clause-record-core,Record>>.

include::requirements/searchable-catalog/REQ_searchable-catalog.adoc[]

include::recommendations/searchable-catalog/PER_additional-requirements.adoc[]

include::requirements/searchable-catalog/REQ_conformance.adoc[]

include::requirements/searchable-catalog/REQ_mandatory-catalog-properties.adoc[]

include::recommendations/searchable-catalog/PER_additional-catalog-properties.adoc[]

include::requirements/searchable-catalog/REQ_mandatory-record-properties.adoc[]

include::recommendations/searchable-catalog/PER_additional-record-properties.adoc[]

[[clause-searchable-catalog_filtering]]
==== Requirements Class "Searchable Catalog - Filtering" (Deployment)

include::requirements/requirements_class_searchable-catalog_filtering.adoc[]

This requirements class specifies requirements and recommendations for supporting advanced filtering at searchable catalog endpoints.  Advanced filter expressions can only reference properties from an advertised set of queryables.

include::requirements/searchable-catalog_filtering/REQ_filtering.adoc[]

include::requirements/searchable-catalog_filtering/REQ_conformance.adoc[]

include::requirements/searchable-catalog_filtering/REQ_mandatory-queryables.adoc[]

include::recommendations/searchable-catalog_filtering/PER_additional-queryables.adoc[]

[[clause-searchable-catalog_sorting]]
==== Requirements Class "Searchable Catalog - Sorting" (Deployment)

include::requirements/requirements_class_searchable-catalog_sorting.adoc[]

The Searchable Catalog - Sorting requirements class specifies requirements for supporting sorting of responses at searchable catalog endpoints.

include::requirements/searchable-catalog_sorting/REQ_sorting.adoc[]

include::requirements/searchable-catalog_sorting/REQ_conformance.adoc[]

[[clause-local-resources-catalog]]
=== Requirements Class "Local Resources Catalog" (Deployment)

[[local-resources-catalog-overview]]
==== Overview

include::requirements/requirements_class_local-resources-catalog.adoc[]

The <<ogc-api-resource-tree,set of OGC API Standards>> define a number of resource endpoints from which summary information about resources accessible via the server's API can be retrieved.  These endpoints are referred to as _local resources catalogs_ in this Standard because they provide metadata about resources offered locally by a deployment of some or all of the <<ogc-api-resource-tree, set of OGC API Standards>>.

[[local-resources-endpoint]]
[NOTE]
==================================================
* _**<<local-resources-endpoint-def,local_resources_endpoint>>**_ +
Refers to the path from which a catalog of local resources can be retrieved.

* _**<<local-resources-catalog-def,local_resources_catalog>>**_ +
Refers to an instance of the resource that can be retrieved from the _local resources endpoint_ (i.e., the catalog).

* _**<<local-resources-item-def,local_resources_item>>**_ +
Each local resources catalog includes an array member.  The items of that array are objects (i.e., records) that contain summary metadata about resources retrievable via the server's API.  These objects are referred to as _**local resources items**_.
==================================================

The `/collections` endpoint is an example of a _local resources endpoint_.  Doing a GET operation at the local resources endpoint (i.e., `GET /collections`) returns a document that is an example of a _local resources catalog_.  This document contains an array member named `collections` and the items of that array are the _local resources items_.  Each of these _local resources items_ provides metadata about some resource (e.g., a feature collection) that is accessible via the server's API.

Other _local resources endpoints_ available in the <<ogc-api-resource-tree,OGC API resource tree>> include the `/processes` endpoint which provides summary metadata about processes and the `/collections/{collectionId}/scenes` endpoint which provides metadata about the source images of a coverage.

In order to enable catalog-like searching at these local resources endpoints, this requirements class:

1. extends the information content of the local resources catalog to satisfy the requirements of the <<clause-record-collection,Record Collection>> common component;

2. extends the information content of the local resources i.e., to satisfy the requirements of the <<clause-record-core,Record Core>> common component; and

3. optionally extends the local resources endpoint with a set of query parameters that support a basic capability.

The Local Resources Catalog requirements class does not define the specific endpoints in the <<ogc-api-resource-tree,OGC API resource tree>> that should be enabled with catalog-like query capabilities.  It only defines how those endpoints should be enhanced should the requirement for catalog-like searching be identified by the responsible OGC Standard.  It is anticipated that the responsible OGC standard will define a requirements class or extension to enable local resources catalog capabilities at that endpoint.

==== Common components

include::requirements/local-resources-catalog/REQ_local-resources-catalog.adoc[]

==== Declaring conformance

include::requirements/local-resources-catalog/REQ_conformance.adoc[]

==== Extending the local resources catalog

As an example of a local resources endpoint, consider the `/collections` endpoint.  The resource, called _collections_, that can be retrieved from this endpoint is defined in http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_collections_[OGC API - Features].  The following table cross-walks the information content of the collections object with the <<clause-record-collection,catalog>>.

[[collections-catalog-crosswalk]]
[reftext='{table-caption} {counter:table-num}']
.Crosswalk of collections object and catalog
[cols="25,25,25,25",options="header"]
|===
|Collections property    |Requirement   |<<clause-record-collection,Catalog>> property |Requirement
|--                      |--            |id                |**required**
|--                      |--            |title             |optional
|--                      |--            |description       |optional
|--                      |--            |links             |optional
|--                      |--            |extent            |optional
|--                      |--            |itemType          |optional
|--                      |--            |crs               |optional
|--                      |--            |created           |optional
|--                      |--            |updated           |optional
|--                      |--            |type              |**required**
|--                      |--            |keywords          |optional
|--                      |--            |themes            |optional
|--                      |--            |language          |optional
|--                      |--            |languages         |optional
|--                      |--            |resourceLanguages |optional
|--                      |--            |externalIds       |optional
|--                      |--            |formats           |optional
|--                      |--            |contacts          |optional
|--                      |--            |license           |optional
|--                      |--            |rights            |optional
|--                      |--            |conformsTo        |optional
|--                      |--            |recordsArrayName  |optional
|collections             |**required**  |records           |optional
|links                   |**required**  |links             |**required**
|linkTemplates           |optional      |linkTemplates     |optional
|===

The information content of the _collections_ object, a local resources catalog, is sparse and so the following requirements and recommendations are made:

include::requirements/local-resources-catalog/REQ_mandatory-catalog-properties.adoc[]

include::recommendations/local-resources-catalog/PER_additional-catalog-properties.adoc[]

include::recommendations/local-resources-catalog/PER_other-catalog-properties.adoc[]

In practice the responsible standard would define how the two sets of properties are merged into the local resources catalog.  In this example it is straight forward since the collections object (path: `/collections`) is sparse and most catalog properties can be added without issue.  It should further be noted that for the collections object (path: `/collections`) the name of the array containing the local resources items (i.e., the records) is **"collections"** and so the value of the <<req_record-collection_records-array-name,`recordsArrayName`>> property would be set to **"collections"**.

==== Extending the local resources item

As an example of a local resources item, consider the _collection_ object defined in defined in http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_collection_[OGC API - Features].  The following table cross-walks the information content of the collection object with the <<core-properties,properties>> defined for the <<clause-record-core,Record Core>> common component:

[[record-collection-crosswalk]]
[reftext='{table-caption} {counter:table-num}']
.Crosswalk of collection and record properties
[cols="25,25,25,25",options="header"]
|===
|Collection property     |Requirement   |<<core-properties,Record>> property |Requirement
|id                      |**required**  |id                |**required**
|--                      |--            |created           |optional
|--                      |--            |updated           |optional
|--                      |--            |conformsTo        |optional
|--                      |--            |type              |optional
|itemType                |optional      |--                |--
|title                   |optional      |title             |optional
|description             |optional      |description       |optional
|extent (space)          |optional      |geometry          |optional
|extent (time)           |optional      |time              |optional
|crs                     |optional      |--                |--
|--                      |--            |keywords          |optional
|--                      |--            |themes            |optional
|--                      |--            |language          |optional
|--                      |--            |languages         |optional
|--                      |--            |resourceLanguages |optional
|--                      |--            |externalIds       |optional
|--                      |--            |formats           |optional
|--                      |--            |contacts          |optional
|--                      |--            |license           |optional
|--                      |--            |rights            |optional
|links                   |**required**  |links             |optional
|linkTemplates           |optional      |linkTemplates     |optional
|===

Many of the properties of the collection, a local resources item, are also properties of a record but the searchability of the collection can be improved by enhancing its information content.  Thus, the following requirements and recommendations are made:

include::requirements/local-resources-catalog/REQ_mandatory-record-properties.adoc[]

include::recommendations/local-resources-catalog/PER_additional-record-properties.adoc[]

include::recommendations/local-resources-catalog/PER_other-record-properties.adoc[]

In practice the responsible standard would define how the two sets of properties are merged into the local resources item.  In this case it is straight forward since the collection object (path: `/collections/{collectionID}`) and the record share a large number of properties.  Where there is a difference, `extent` versus `geometry` and `time`, can be handled by including both sets of properties in the local resources i.e., and ensuring that their values are consistent.

==== Examples

===== Collections example

The following JSON Schema fragments illustrate how to extend the https://docs.ogc.org/is/17-069r4/17-069r4.html#_collections_ [collections object] (a local resources catalog) and the https://docs.ogc.org/is/17-069r4/17-069r4.html#_collection_[collection object] (a local resources item) to include properties required and recommended by this requirements class.

[source,yaml]
----
include::../examples/yaml/collections/localResourcesCatalog.yaml[]
----

[source,yaml]
----
include::../examples/yaml/collections/localResourcesItem.yaml[]
----

[NOTE]
======================================================================
Referenced schemas can be found at:

* https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collections.yaml[collections.yaml],
* https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml[collection.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/catalog.yaml[catalog.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordCommonProperties.yaml[recordCommonProperties.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/linkBase.yaml[linkBase.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/linkTemplate.yaml[linkTemplate.yaml].
======================================================================

===== Processes example

The following JSON Schema fragments illustrate how to extend the https://docs.ogc.org/is/18-062r2/18-062r2.html#toc30[processes object] (a local resources catalog) and the https://docs.ogc.org/is/18-062r2/18-062r2.html#toc30[process summary] (a local resources item) to include properties required and recommended by this requirements class.

[source,yaml]
----
include::../examples/yaml/processes/localResourcesCatalog.yaml[]
----

[source,yaml]
----
include::../examples/yaml/processes/localResourcesItem.yaml[]
----

[NOTE]
======================================================================
Referenced schemas can be found at:

* https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/processList.yaml[processList.yaml],
* https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/processSummary.yaml[processSummary.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/catalog.yaml[catalog.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordCommonProperties.yaml[recordCommonProperties.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/linkBase.yaml[linkBase.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/linkTemplate.yaml[linkTemplate.yaml].
======================================================================

NOTE: T.D.B.  Should add an instance example of a collection object.

==== Discovery of local resources catalog endpoints

Discovery of which local resources catalog endpoints in an OGC API deployment are instrumented for catalog-like searching is accomplished using <<clause-autodiscovery,Autodiscovery>>.

include::requirements/local-resources-catalog/REQ_discovery.adoc[]

[[clause-local-resources-catalog_query-parameters]]
==== Requirements Class "Local Resources Catalog - Query Parameters" (Deployment)

include::requirements/requirements_class_local-resources-catalog_query-parameters.adoc[]

include::requirements/local-resources-catalog_query-parameters/REQ_conformance.adoc[]

===== Operation

include::requirements/local-resources-catalog_query-parameters/REQ_query-parameters.adoc[]

===== Response

include::requirements/local-resources-catalog_query-parameters/REQ_response.adoc[]

[[clause-local-resources-catalog_filtering]]
==== Requirements Class "Local Resources Catalog - Filtering" (Deployment)

===== Overview

include::requirements/requirements_class_local-resources-catalog_filtering.adoc[]

The Local Resources Catalog - Filtering requirements class specifies requirements and recommendations for supporting advanced filtering at _local resource catalog_ endpoints.

===== Conformance

include::requirements/local-resources-catalog_filtering/REQ_conformance.adoc[]

===== Filtering

include::requirements/local-resources-catalog_filtering/REQ_filtering.adoc[]

include::requirements/local-resources-catalog_filtering/REQ_queryables-link.adoc[]

[[clause-local-resources-catalog_sorting]]
==== Requirements Class "Local Resources Catalog - Sorting" (Deployment)

include::requirements/requirements_class_local-resources-catalog_sorting.adoc[]

The Local Resources Catalog - Sorting requirements class specifies requirements and recommendations for supporting sorting of responses at _local resource catalog_ endpoints.

===== Conformance

include::requirements/local-resources-catalog_sorting/REQ_conformance.adoc[]

===== Sorting  

include::requirements/local-resources-catalog_sorting/REQ_sorting.adoc[]

See also: <<req_sorting_get-sortables-op,/req/sorting/get-sortables-op>>, <<req_sorting_get-sortables-success,/req/sorting/get-sortables-success>>.

===== Examples

The following example illustrates a catalog filter expression being applied to the local resources endpoint /collections. In this case, the client is seeking all collection objects whose extent intersects a specified bounding box and that include the keyword "windmills".

----
   Client                                                          Server
     |                                                               |
     |   GET /collections?bbox=3,50,8,54&q=windmills   HTTP/1.1      |
     |   Accept: application/json                                    |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 200 OK                                             | 
     |   Content-Type: application/json                              |
     |                                                               |
     |   {                                                           |
     |     "collections": [                                          |
     |       {                                                       |
     |         "id": "dutch_windmills",                              |
     |         "title": "Windmills within The Netherlands",          |
     |         "description": "Locations of windmills within the Neth|
     |          erlands from Rijksdienst voor het Cultureel Erfgoed (|
     |          RCE) INSPIRE WFS. Uses GeoServer WFS v2 backend via O|
     |          GRProvider.",                                        |
     |         "keywords": [                                         |
     |           "Netherlands",                                      |
     |           "INSPIRE",                                          |
     |           "Windmills",                                        |
     |           "Heritage",                                         |
     |           "Holland",                                          |
     |           "RD"                                                |
     |         ],                                                    |
     |         "links": [                                            |
     |           {                                                   |
     |             "type": "text/html",                              |
     |             "rel": "canonical",                               |
     |             "title": "information",                           |
     |             "href": "https://www.nationaalgeoregister.nl/geone|
     |                      twork/srv/dut/catalog.search#/metadata/29|
     |                      1afe4b-4f4b-497c-8026-fb437c4e9c7e",     |
     |             "hreflang": "nl-NL"                               |
     |           },                                                  |
     |           {                                                   |
     |             "type": "application/json",                       |
     |             "rel": "root",                                    |
     |             "title": "Landing page of this server as JSON",   |
     |             "href": "https://demo.pygeoapi.io/master?f=json"  |
     |           },                                                  |
     |           {                                                   |
     |             "type": "text/html",                              |
     |             "rel": "root",                                    |
     |             "title": "Landing page of this server as HTML",   |
     |             "href": "https://demo.pygeoapi.io/master?f=html"  |
     |           },                                                  |
     |           {                                                   |
     |             "type": "application/json",                       |
     |             "rel": "self",                                    |
     |             "title": "This document as JSON",                 |
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills?f=json"               |
     |           },                                                  |
     |           {                                                   |
     |             "type": "application/ld+json",                    |
     |             "rel": "alternate",                               |
     |             "title": "This document as RDF (JSON-LD)",        |
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills?f=jsonld"             |
     |           },                                                  |
     |           {                                                   |
     |             "type": "text/html",                              |
     |             "rel": "alternate",                               |
     |             "title": "This document as HTML",                 |
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills?f=html"               |
     |           },                                                  |
     |           {                                                   |
     |             "type": "application/json",                       |
     |             "rel": "http://www.opengis.net/def/rel/ogc/1.0/sch|
     |                     ema",                                     |
     |             "title": "Schema of collection in JSON",          |
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills/schema?f=json"        |
     |           },                                                  |
     |           {                                                   |
     |             "type": "text/html",                              |
     |             "rel": "http://www.opengis.net/def/rel/ogc/1.0/sch|
     |                     ema",                                     |
     |             "title": "Schema of collection in HTML",          |
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills/schema?f=html"        |
     |           },                                                  |
     |           {                                                   |
     |             "type": "application/schema+json",                |
     |             "rel": "http://www.opengis.net/def/rel/ogc/1.0/que|
     |                     ryables",                                 |
     |             "title": "Queryables for this collection as JSON",|
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills/queryables?f=json"    |
     |           },                                                  |
     |           {                                                   |
     |             "type": "text/html",                              |
     |             "rel": "http://www.opengis.net/def/rel/ogc/1.0/que|
     |                     ryables",                                 |
     |             "title": "Queryables for this collection as HTML",|
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills/queryables?f=html"    |
     |           },                                                  |
     |           {                                                   |
     |             "type": "application/geo+json",                   |
     |             "rel": "items",                                   |
     |             "title": "Items as GeoJSON",                      |
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills/items?f=json"         |
     |           },                                                  |
     |           {                                                   |
     |             "type": "application/ld+json",                    |
     |             "rel": "items",                                   |
     |             "title": "Items as RDF (GeoJSON-LD)",             |
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills/items?f=jsonld"       |
     |           },                                                  |
     |           {                                                   |
     |             "type": "text/html",                              |
     |             "rel": "items",                                   |
     |             "title": "Items as HTML",                         |
     |             "href": "https://demo.pygeoapi.io/master/collectio|
     |                      ns/dutch_windmills/items?f=html"         |
     |           }                                                   |
     |         ],                                                    |
     |         "extent": {                                           |
     |           "spatial": {                                        |
     |             "bbox": [                                         |
     |               [                                               |
     |                 3.37,                                         |
     |                 50.75,                                        |
     |                 7.21,                                         |
     |                 53.47                                         |
     |               ]                                               |
     |             ],                                                |
     |             "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS|
     |                     84"                                       |
     |           },                                                  |
     |           "temporal": {                                       |
     |             "interval": [                                     |
     |               [                                               |
     |                 null,                                         |
     |                 null                                          |
     |               ]                                               |
     |             ]                                                 |
     |           }                                                   |
     |         },                                                    |
     |         "itemType": "feature",                                |
     |         "crs": [                                              |
     |           "http://www.opengis.net/def/crs/OGC/1.3/CRS84",     |
     |           "http://www.opengis.net/def/crs/EPSG/0/4326",       |
     |           "http://www.opengis.net/def/crs/EPSG/0/3857",       |
     |           "http://www.opengis.net/def/crs/EPSG/0/4258",       |
     |           "http://www.opengis.net/def/crs/EPSG/0/28992"       |
     |         ],                                                    |
     |         "storageCRS": "http://www.opengis.net/def/crs/EPSG/0/2|
     |                        8992"                                  |
     |       }                                                       |
     |     ],                                                        |
     |     "links": [                                                |
     |       {                                                       |
     |         "type": "application/json",                           |
     |         "rel": "self",                                        |
     |         "title": "This document as JSON",                     |
     |         "href": "https://demo.pygeoapi.io/master/collections?f|
     |                  =json"                                       |
     |       },                                                      |
     |       {                                                       |
     |         "type": "application/ld+json",                        |
     |         "rel": "alternate",                                   |
     |         "title": "This document as RDF (JSON-LD)",            |
     |         "href": "https://demo.pygeoapi.io/master/collections?f|
     |                  =jsonld"                                     |
     |       },                                                      |
     |       {                                                       |
     |         "type": "text/html",                                  |
     |         "rel": "alternate",                                   |
     |         "title": "This document as HTML",                     |
     |         "href": "https://demo.pygeoapi.io/master/collections?f|
     |                  =html"                                       |
     |       }                                                       |
     |     ]                                                         |
     |   }                                                           |
     |<--------------------------------------------------------------|
----

