[[overview]]
== Overview

[[general-overview]]
=== General

The OGC API family of standards enable access to resources using the HTTP protocol and its' associated operations (GET, PUT, POST, etc.). OGC API - Common defines a set of features which are applicable to all OGC APIs. Other OGC standards extend API - Common with features specific to a resource type. 

This standard, OGC API - Records - Part 1: Core, extends OGC API Common to:

. Provide modern API patterns and encodings to facilitate further lowering the barrier to finding the existence of spatial resources on the Web.
. Provide functionality comparable to that of the <<api-behavior-model-overview,OGC Catalogue Service (CSW) standard>> so that a facade can be created over legacy services thus allowing them to participate in the new OGC API ecosystem.

Resources exposed through an OGC API may be accessed through a Universal Resource Identifier <<rfc3986,(URI).>> URIs are composed of three sections:

* Service Offering: The service endpoint (subsequently referred to as Base URI or {root})
* Access Paths: Unique paths to Resources
* Query: Parameters to adjust the representation of a Resource or Resources like encoding format or subsetting

Some resources are also accessible through links on previously accessed resources. Unique relation types are used for each resource.

The following table, <<records-paths,Record API Paths>>, summarizes the access paths and relation types defined in this standard.

[[records-paths]]
[reftext='{table-caption} {counter:table-num}']
.Record API Paths
[width="90%",cols="40,20,40",options="header"]
|===
^|**Path Template** ^|**Relation** ^|**Resource** 
3+^|**Common**
|<<landing-page,{root}/>> |none |Landing page
|<<api-definition,{root}/api>> |`service-desc` +
or +
`service-doc` |API Description (optional)
|<<conformance-classes,{root}/conformance>> |`conformance` |Conformance Classes
|<<collections,{root}/collections>> |`data` |Metadata describing the spatial collections available from this API.
|<<collectionInfo,{root}/collections/{collectionId}>> | |Metadata describing the collection which has the unique identifier `{collectionId}`
3+^|**Records**
|<<records-access,{root}/collections/{collectionId}/items>> |`items` |Search results based on querying the service for records satisfying 0..n query parameters.
|<<record-access,{root}/collections/{collectionId}/items/{recordId}>> |`item` |Record of metadata which has the unique identifier `{recordId}`.
|===

Where:

* {root} = Base URI for the API server
* {collectionId} = an identifier for a specific collection
* {recordId} = an identifier for a specific record within a collection

[[record-schema-overview]]
=== Record Schema

T.B.D.

[[api-behavior-model-overview]]
=== API Behavior Model

The Records API is designed to be compatible but not conformant with the OGC Catalogue Service for the Web (CSW). This allows OGC API - Records implementations and CSW implementations to co-exist in a single processing environment.

The https://www.opengeospatial.org/standards/cat[OGC Catalogue Service standard version 3] provides an abstract core model of metadata (data about data) describing a number of different information types (data, services, styles, processes, etc.) on which the classic operations GetCapabilities, DescribeRecord, GetRecords, and GetRecordById can be explained naturally. This model consists of a 1..n catalogue collections residing in a CSW backend repository. It holds service metadata describing service qualities (identification, contact, operations, filtering capabilities, etc.). At its heart, a catalogue may provide discovery services to any number of metadata repositories. The core catalogue model is based on an extension of Dublin Core (CSW Record). Application profiles can be developed to target specific metadata information models (such as ISO 19115/19139, etc.).

Discussion has shown that the API model also assumes underlying service and object descriptions, so a convergence seems possible. In any case, it will be advantageous to have a similar "mental model" of the server store organization on hand to explain the various functionalities introduced below.

=== Search

The Records API offers various levels of search capability of escalating complexity and capability.  At the core is the ability to search the catalogue by specifying:

* a bounding box
* a time instant or time period
* keywords
* free text
* equality predicates based on a subset of core queryables (e.g. by resource type, by external identifier)

This specification also includes a conformance class that allows a catalogue to be searched using  https://portal.opengeospatial.org/files/?artifact_id=56866[OpenSearch Geo].  OpenSearch Geo gives the user more control over the kinds of geometries, beyond a bounding box, that can be used to define an area of interest.

Finally extensions, such as the https://docs.ogc.org/DRAFTS/19-079.html[OGC API - Features - Part 3: Filter and the Common Query Language (CQL)], may be used with the Records API to support complex search capabilities using a rich set of logically connected search predicates where the user has full control over to query expression.

[[dependencies-overview]]
=== Dependencies

The OGC API - Records standard is an extension of the OGC API - Common standard. Therefore, an implementation of OGC API - Records must first satisfy the appropriate Requirements Classes from API - Common. The following table, <<mapping-to-common,Mapping API - Records Sections to API - Common Requirements Classes>>, identifies the OGC API - Common Requirements Classes which are applicable to each section of this Standard. Instructions on when and how to apply these Requirements Classes are provided in each section.

[[mapping-to-common]]
[reftext='{table-caption} {counter:table-num}']
.Mapping API - Records Sections to API - Common Requirements Classes
[width="90%",cols="2,6"]
|====
^|*API - Record Section* ^|*API - Common Requirements Class*
|<<landing-page,API Landing Page>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<api-definition,API Definition>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<conformance-classes,Declaration of Conformance Classes>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<collection-access-section,Collections>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|<<requirements-class-openapi_3_0-clause,OpenAPI 3.0>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/oas30
|<<requirements-class-json-clause,JSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/geojson
|<<requirements-class-html-clause,HTML>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/html
|====
