[[media-types-section]]
== Media Types

This standard does not mandate any particular encoding or format. However, it does provide extensions for encodings which are commonly used in OGC APIs. These extensions include:

* <<requirements-class-json-clause,JSON>>
* <<requirements-class-html-clause,HTML>>

Neither of these encodings are mandatory. An implementor of this standard may choose to implement neither of them, selecting different encodings instead.

=== HTML Encoding
Support for HTML is recommended. HTML is the core language of the World Wide Web. An API that supports HTML will support browsing the spatial resources with a web browser and will also enable search engines to crawl and index those resources.

=== JSON Encoding
Support for JSON is recommended. JSON is a commonly used format that is simple to understand and well supported by tools and software libraries.

JSON structures documented in this standard are defined using JSON Schema. These schema are available in JSON and YAML formats from http://schemas.opengis.net/tbd[http://schemas.opengis.net/tbd]

==== GeoJSON
"GeoJSON is a geospatial data interchange format based on JavaScript Object Notation (JSON). It defines several types of JSON objects and the manner in which they are combined to represent data about geographic features, their properties, and their spatial extents. GeoJSON uses a geographic coordinate reference system, World Geodetic System 1984, and units of decimal degrees." <<GeoJSON,IETF RFC 7946>>

GeoJSON provides a simple way of represening OGC Featues in JSON. Due to its simplicity, however, it is not suitable for all feature data. It is best used for content which has a spatial extent that can be used with the World Geodetic System 1984 Coordinate Reference System.

=== Media Types
A description of the MIME-types is mandatory for any OGC standard which involves data encodings. The list of suitable MIME-types for the API - Records standard in provided in <<api-records-mime-types>>.

[#api-records-mime-types,reftext='{table-caption} {counter:table-num}']
.API - Records MIME Types
[width="90%",cols="2,4"]
|====
^|*Encoding* ^|*MIME Type*
|HTML |text/html
|JSON |application/json
|GeoJSON |application/geo+json
|ATOM |application/atom+xml
|====

[[media-type-defaults]]
=== Default Encodings

The media type used to encode a response to a request shall be determined through the HTTP content negotiation protocol as specified in API - Common. However, content negotiation is not required by the HTTP standard. So default encodings must be established.

include::requirements/core/REQ_rc-media-type-default.adoc[]
