== Conformance

Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance, are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The standardization targets of all conformance classes are "Web APIs".

OGC API - Common provides a common foundation for OGC API standards. Therefore, this standard should be viewed as an extension to OGC API - Common. Conformance to this standard requires demonstrated conformance to the applicable Conformance Classes of OGC API - Common.

This standard identifies seven (7) Conformance Classes. The Conformance Classes implemented by an API are advertised through the `/conformance` path. Each Conformance Class has an associated Requirements Class. The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.

The Requirements Classes for OGC API - Records are:

* <<clause-core,Core>>
* <<clause-sorting,Sorting>>
* <<clause-cql-filter,Filtering using the Common Query Language (CQL)>>
* <<clause-opensearch,OpenSearch>>
* <<requirements-class-json-clause,JSON-Record>>
* <<requirements-class-atom-clause,ATOM-Record>>
* <<requirements-class-html-clause,HTML-Record>>

The _Core_ Requirements Class is the minimal useful service interface for OGC API - Records. The requirements specified in this class are mandatory for all implementations of this standard. The core defines a baseline record schema, resource paths, a set of mandatory properties (core queryables) that every record must contain, a set of core query parameters that support bounding box spatial queries, temporal queries, full-text searching, parameters for sorting responses, and error handling.

The _Sorting_ Requirements Class defines the requirements to support sorting of records in a query response.

The _Filter using the Common Query Language_ Requirements Class defines the requirements to support record filtering using CQL.

The _OpenSearch_ Requirements Class defines the requirements to support query by OpenSearch clients.

The _JSON_ Requirements Class defines the requirements for a GeoJSON (see RFC 7946) representation of a standard catalogue record.

The _ATOM_ Requirements Class defines the requirements for an ATOM representation of a standard catalogue record.

The _HTML_ Requirements Class defines the requirements for an HTML representation of a standard catalogue record.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<ats_core,Core>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/core
|<<ats_sorting,Sorting>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/sorting
|<<ats_cql,CQL>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/cql
|<<ats_opensearch,OpenSearch>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/opensearch
|<<ats_json,JSON-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/JSON
|<<ats_atom,ATOM-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/atom
|<<ats_atom,HTML-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/html
|===
