[[clause-core]]
== Requirements Class "Core"

[[core-overview]]
=== Overview

include::requirements/requirements_class_core.adoc[]

The `Core` Requirements Class defines the requirements for searching and accessing Record resources.

The components of the `Core` requirements class that are derived from OGC API Common are presented in the following sections:

. <<api-platform-section,API Platform>>: a set of common capabilities
. <<collections-access,Collections access>>: operations for accessing information about collections of records
. <<general-requirements-section,General Requirments>>: general principles for use with this standard

The requirements for accessing collections of records are presented in the following sections:

. <<records-access,Records Access>>: operations for accessing record resources
. <<record-access,Record Access>>: operations for accessing a single record

[[record-model]]
=== Record 

The atomic unit of information in a catalogue is a **_record_** which is defined in this clause.

It is expected that the information necessary to populate the fields/properties of a catalogue record is readily available for any resource that is being registered in the catalogue.

It is anticipated that the schema of a record will be extended to describe specific resource types (e.g. datasets, services, etc.) and also extended by information communities wishing to enrich the information content of the record to suit their needs.

Although this document does not mandate any particular encoding for a record, this document does define conformance classes for three encodings:

* a <<record_json_encoding,GeoJSON>> record encoding,
* an <<record_atom_encoding,ATOM>> record encoding,
* and an <<record_html_encoding,HTML>> encoding.

Other encoding are allow but are not described in this document.

==== Overview

[[core-queryables]]
==== Core queryables

<<core-queryables-record-table>> and <<core-queryables-resource-table>> define the set of properties, called the _core queryables_, that may be included in a record.

[#core-queryables-record-table,reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the catalogue record
[cols="20,5,55,20",options="header"]
|===
|Queryables |Requirement |Description |GeoJSON key
|recordId |M |A unique record identifier assigned by the server. |id
|recordCreated |O |The date this record was created in the server. |created
|recordUpdated |O |The most recent date on which the record was changed. |updated
|links |O |A list of links for navigating the API (e.g. link to previous or next pages; links to alternative representations, etc.) |links
|===

[#core-queryables-resource-table,reftext='{table-caption} {counter:table-num}']
.Table of Core Queryables related to the resource
[cols="20,5,55,20",options="header"]
|===
|Queryables |Requirement |Description |GeoJSON key
|type |M |The nature or genre of the resource. |properties.type
|title |M |A human-readable name given to the resource. |properties.title

|description |O |A free-text description of the resource. |properties.description
|keywords |O |A list of keywords or tag associated with the resource. |properties.keyword
|keywordsCodespace |O |A reference to a controlled vocabulary used for the keywords property. |properties.keyword-codespace
|language |O |This refers to the natural language used for textual values (i.e. titles, descriptions, etc) of a resource. |properties.language
|externalId |O |An identifier for the resource assigned by an external entity. |properties.externalid
|created |O |The date the resource was created. |properties.created
|updated |O |The more recent date on which the resource was changed. |properties.updated
|publisher |O |The entity making the resource available. |properties.publisher
|themes |O |A knowledge orgnaization system used to classify the resource. |properties.themes
|formats |O |A list of available distributions for the resource. |properties.formats
|contactPoint |O |An entity to contact about the resource. |properties.contactpoint
|license |O |A legal document under which the resource is made available. |properties.license
|rights |O |A statement that concerns all rights not addressed by the license such as a copyright statement. |properties.rights
|extent |O |The spatio-temporal coverage of the resource. |properties.extent
|associations |O |A list of links for accessing the resource, links to other resources associated with this resource, etc. |properties.associations
|===

include::requirements/core/REQ_mandatory-queryables.adoc[]

include::recommendations/core/PER_additional-queryables.adoc[]

==== Keywords and Themes

A record allows for one ``properties.keywords`` and 0..n ``properties.themes``
properties.  The following provides an example of using keywords for free
form terms (e.g. tags) as well as themes to articulate terms from formal
vocabularies.

[#keywords-themes-example,reftext=`Keywords and themes Example`]
.Keywords and themes Example
[source,json]
----
include::../examples/json/keywords-themes.json[]
----

The following recommendations provide clarification on where and how to use
these properties in a record.

include::recommendations/core/REC_record-keywords-themes.adoc[]

==== Associations and Links

A record may contain both `links` and `properties.associations` properties which
serve different purposes.

include::recommendations/core/REC_record-links.adoc[]

include::recommendations/core/REC_record-associations.adoc[]

NOTE: The representation of links in the payload will depend on the encoding of the record.

The following provides an example of using associations for related resources of a record, as both traditional link relations as well as API resources via URI templates.

[#associations-simple-and-uri-template-example,reftext=`Associations simple and URI Template Example`]
.Associations simple and URI Template Example
[source,json]
----
include::../examples/json/associations-simple-and-uri-template.json[]
----

[[example_11]]
.Links in a record payload
====
The links in a record could be (in this example represented as link headers):

[source]
----
Link: <http://data.example.org/collections/my_catalogue/items/record_123.json>; rel="self"; type="application/geo+json"
Link: <http://data.example.org/collections/my_catalogue/items/record_123.html>; rel="alternate"; type="text/html"
Link: <http://data.example.org/collections/my_catalogue.json>; rel="collection"; type="application/json"
Link: <http://data.example.org/collections/my_catalogue.html>; rel="collection"; type="text/html"
----
====

==== Templated links with variables

This specification extends the https://github.com/opengeospatial/ogcapi-common/blob/master/core/openapi/schemas/link.json[schema for a link] defined in OGC API Common to include a `templated` key and a `variables` key.

T.B.D.  Need to add requirements and recommendations about `templated` and `variables`.

* the presence of the `templated` key with a value of `true` indicates that the included `href` value uses substitution variables of the from `{_variable name_}`.  
* the presence of the `variables` key indicated that a section is included that defines the schema of the one or more of the substitution variables used in the `templated` URL that is the value of the `href` key.

Templated links with variables may be used to bind to resources that may required additional information inorder to access the resources.  For example, simply knowing the URL of a legacy OGC service such as WMS or WFS is not sufficient to access resources offered by those services.  Additional information in the form of request parameters and values are required in order to have a complete link to a resources.  A templated link with variables can provide this additional context.

[#templated-link-with-variables,reftext=`Associations simple and URI Template Example`]
.Templated link with variables example
[source,json]
----
include::../examples/json/templated-link.json[]
----

==== Language negotiation

Two kinds of languages are handled in this specification.  The language
associated with the resource and the language associated with the record
that describes the resource in the catalogue.

The language associated with the resource is specified using the <<core-queryables-resource-table,language>> property of a catalogue record.  This indicates the language associated with the resource that the record described.

The language for the record itself is negotiated between a client and the servers using the https://tools.ietf.org/html/rfc7231#section-5.3.5[Accept-Language] header of https://tools.ietf.org/html/rfc7231[HTTP].  Records in a response document can only be presented in a single negotiated language.  There is no provision in the record schema to allow a response containing text fields simultaneously presented in multiple languages (e.g. multiple titles in different languages).  To obtain a record in multiple lanugages would require multiple requests to the server each nagotiating to a desired language.

[[records-access]]
=== Records access

==== Overview

The basic Records API process is the OGC API Features API that has been augmented with additional operators that are useful for searching collections of catalogue records. This clause describes these additional operators.

==== Operation

Catalogue records are accessible at the `/collections/{collectionId}/items`
endpoint.

include::requirements/core/REQ_record-collection-op.adoc[]

[[parameters-section]]
==== Parameters

===== Overview

The following tables list the set mandatory query parameters that must be 
supported at the `/collections/{collectionId}/items` endpoint.

[#core-query-parameters-table,reftext='{table-caption} {counter:table-num}']
.Table of Query Parameters
[cols="15,85",options="header"]
|===
|Parameter name |Description
|bbox |A bounding box. If the spatial extent of the record intersects the specified bounding box then the record shall be presented in the response document.
|datetime |A time instance or time period. If the temporal extent of the record intersects the specified data/time value then the record shall be presented in the response document.
|limit |The number of records to be presented in a response document.
|q |A comma-separated list of search terms. If any server-chosen text field in the record contains 1 or more of the terms listed then this records shall appear in the response set.
|type |An equality predicate consistent of a comma-separated list of resource types.  Only records of the listed type shall appear in the resource set.
|externalid |An equality predicate consistent of a comma-separated list of external resource identifiers. Only records with the specified external identifiers shall appear in the response set.
|===

The query parameters http://docs.opengeospatial.org/DRAFTS/20-024.html#bbox-parameter-requirements[`bbox`], http://docs.opengeospatial.org/DRAFTS/20-024.html#datetime-parameter-requirements[`datetime`] and http://docs.opengeospatial.org/DRAFTS/20-024.html#limit-parameter-requirements[`limit`] are inherited from API -Common.  All requirements and recommendations in API - Common regarding these parameters also apply for API - Records.

The query parameters `q`, `type` and `externalid` are specific to API - Records.

[[core-query-parameters-bbox]]
===== Parameter bbox

The Bounding Box (bbox) parameter is defined in API - Common. The following requirement governs use of that parameter in API - Records.

include::requirements/core/REQ_query-param-bbox.adoc[]

[[core-query-parameters-datetime]]
===== Parameter datetime

The Date-Time (datetime) parameter is defined in API - Common. The following requirement governs use of that parameter in API - Records.

include::requirements/core/REQ_query-param-datetime.adoc[]

[[core-query-parameters-limit]]
===== Parameter limit

The limit parameter is defined in API - Common. The following requirement governs use of that parameter in API - Records.

include::requirements/core/REQ_query-param-limit.adoc[]

[[core-query-parameters-q]]
===== Parameter q

include::requirements/core/REQ_query-param-q-definition.adoc[]

include::recommendations/core/REC_param-q.adoc[]

include::requirements/core/REQ_query-param-q-response.adoc[]

[[core-query-parameters-type]]
===== Parameter type

include::requirements/core/REQ_query-param-type-definition.adoc[]

include::requirements/core/REQ_query-param-type-response.adoc[]

[[core-query-parameters-externalid]]
===== Parameter externalId

include::requirements/core/REQ_query-param-externalid-definition.adoc[]

include::requirements/core/REQ_query-param-externalid-response.adoc[]

[[additional-query-parameters]]
===== Additional query parameters

This standard defines the following URL query parameters based on the set of
<<core-queryables-record-table,core queryables>> to support record selection
based on the resource type and/or an external identifier associated with the
resource.

* <<core-query-parameters-type,type>>
* <<core-query-parameters-externalid,externalId>>

include::recommendations/core/REC_additional-query-parameters.adoc[]

===== Combinations of Filtering Parameters

Any combination of query parameters from the <<core-query-parameters-table,Table of Query Parameters>> and any <<additional-query-parameters,additional query parameters>> may be specified for filtering. Note that the requirements on these parameters imply that only records matching all the predicates are in the result set; i.e., the logical operator between the predicates is **AND** (exclusive).

[[query-response]]
==== Response

include::requirements/core/REQ_record-collection-response.adoc[]

<<response-encodings>> lists specific requirements based on the negotiated representation of the response.

[#response-encodings,reftext='{table-caption} {counter:table-num}']
.Negotiated representation of response 
[width=40%,cols="30%,70%",options="header"]
|===
|Representation |Requirements
|JSON/GeoJSON |<<record_json_encoding,Requirements Class JSON>>
|HTML |<<record_html_encoding,Requirements Class HTML>>
|XML/ATOM |<<record_atom_encoding,Requirements Class ATOM>>
|===

==== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

==== Examples

The following is an example of a response to an OGC API - Records query
operation (path: `/collections/{collectionId}/items`).  This example shows
a JSON response and the response container is a GeoJSON feature collection.
Specific records are not presented in this example in order to illustrate
the structure of the response container in GeoJSON.

[#records-example,reftext=`Records Example`]
.Records Example in GeoJSON
[source,json]
----
include::../examples/json/record-collection.json[]
----

See <<record-example>> for an example of a single catalogue record.

[[record-access]]
=== Record access

==== Operation

include::requirements/core/REQ_record-op.adoc[]

==== Response

include::requirements/core/REQ_record-success.adoc[]

==== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

===== Examples

The following is an example of a single catalogue record encoded in GeoJSON.
Such a record might appears in the `features` array of a
<<records-example,query response>> or it may be the response when a specific,
single record is accessed (path: `/collections/{collectionId}/items/{recordId}`).

[#record-example,reftext=`Record Example`]
.Record Example in GeoJSON
[source,json]
----
include::../examples/json/record.json[]
----
