[[clause-encodings]]
== Encodings

[[requirements-class-json-clause]]
=== Requirements Class JSON

==== Overview

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the JSON Conformance Class
. The client negotiates a JSON or GeoJSON format

The JSON Requirements Class restricts requirements defined in the `Core` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `Core` requirements which lay within each scope.

include::requirements/requirements_class_json.adoc[]

==== Common

This section covers the requirements inherited from the API - Common standard. Its scope includes responses for the following operations:

* `{root}/`: Landing Page
* `{root}/api`: API Description
* `{root}/conformance`: Conformance Classes
* `{root}/collections`: Collections
* `{root}/collections/{collectionid}`: Collection Information

include::requirements/json/REQ_api-common.adoc[]

It is also necessary to advertise conformance with this Requirements Class.

include::requirements/json/REQ_json-conformance.adoc[]

==== Record 

GeoJSON is a commonly used format that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format supporting GeoJSON is recommended, if record data can be represented in GeoJSON for the intended use.

include::requirements/json/REQ_json-geojson-definition.adoc[]

include::requirements/json/REQ_json-geojson-content.adoc[]

[[schema_record]]
.link:http://fix.me/record.yaml[Schema for a catalogue record in JSON(record.yaml)]
[source,YAML]
----
type: object
required:
  - id
  - type
  - geometry
  - properties
properties:
  id:
    type: string
    description: A unique identifier of the catalogue record.
    format: uri
  type:
    type: string
    enum: 
      - Feature
  geometry:
    $ref: ../openapi/schemas/geometryGeoJSON.yaml
  properties:
    type: object
    required:
      - type
      - title
    properties:
      record-created:
        type: string
        description: Date of creation of this record.
        format: date-time
      record-updated:
        type: string
        description: The most recent date on which the record was changed.
        format: date-time
      type:
        type: string
        description: The nature or genre of the resource.
        format: uri
      title:
        type: string
        description: A human-readable name given to the resource.
      description:
        type: string
        description: A free-text account of the resource.
      keywords:
        type: array
        description: |-
           The topic or topics of the resource. Typically represented using
           keywords, tags, key phrases, or classification codes. Recommended
           best practice is to use a controlled vocabulary.
        items:
           type: string
      keywords-codespace:
         type: string
         description: A reference to a controlled vocabulary used for the keywords.
         format: uri
      language:
        type: string
        description: The natural language used for textual values (e.g. titles, descriptions, etc.) of the resource. ISO 639-1/639-2 codes should be used.
        default: en
      externalId:
        type: string
        description: An identifier for the resource assigned by an external (to the catalogue) entity.
      created:
        type: string
        description: Date of creation of the resource.
        format: date-time
      updated:
        type: string
        description: Most recent date on which the resource was changed.
        format: date-time
      publisher:
        type: string
        description: Link to the entity making the resource available.  Recommended best practice is to use a VCard (see http://www.w3.org/TR/vcard-rdf/).
        format: uri
      themes:
        type: array
        description: A knowledge organization system used to classify the resource.
        items:
          type: object
          properties:
            category:
              type: string
              description: A category of the resource.
              format: uri
            taxonomy:
              type: string
              description: The knowledge organization system used to classify the resource.
              format: uri
      formats:
        type: array
        description: A list of available distributions of the resource.
        items:
          type: string
      contactPoint:
        type: string
        description: Link to relevant contact information.  Recommended best practice is to use a VCard (see http://www.w3.org/TR/vcard-rdf/).
        format: uri
      license:
        type: string
        description: A legal document under which the resource is made available.
        format: uri
      rights:
        type: string
        description: A statement that concerns all rights not addresses by the license such as a copyright statement.
      extent:
         $ref: ./extent.yaml
      associations:
        type: array
        description: A list of links for accessing the resource (e.g. download link, access link) in one of the supported distribution formats and/or links to other resources associated with this resource.
        items:
          $ref: ../openapi/schemas/common/link.yaml
      additionalProperties: true
  links:
    type: array
    description: A list of links for navigating the API (e.g. prev, next, etc.).
    items:
      $ref: ../openapi/schemas/common/link.yaml
----

[[requirements-class-html-clause]]
=== Requirements Class HTML

==== Overview

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the HTML Conformance Class
. The client negotiates an HTML format

The HTML Requirements Class restricts requirements defined in the `Core` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `Core` requirements which lay within each scope.

include::requirements/requirements_class_html.adoc[]

==== Common

This section covers the requirements inherited from the API - Common standard. Its scope includes responses for the following operations:

* `{root}/`: Landing Page
* `{root}/api`: API Description
* `{root}/conformance`: Conformance Classes
* `{root}/collections`: Collections
* `{root}/collections/{collectionid}`: Collection Information

include::requirements/html/REQ_api-common.adoc[]

It is also necessary to advertise conformance with this Requirements Class.

include::requirements/html/REQ_html-conformance.adoc[]

==== Record

Catalogue information that is only accessible in formats primarily intended to
be read by machine, such as JSON or XML, have to issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web;

* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines] <<SDWBP>>. This standard therefore <<rec_html,recommends supporting HTML as an encoding>>.

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

[[requirements-class-atom-clause]]
=== Requirements Class ATOM

==== Overview

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the ATOM Conformance Class
. The client negotiates an ATOM format

The ATOM Requirements Class restricts requirements defined in the `Core` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `Core` requirements which lay within each scope.

include::requirements/requirements_class_atom.adoc[]

==== Common

This section covers the requirements inherited from the API - Common standard. Its scope includes responses for the following operations:

* `{root}/`: Landing Page
* `{root}/api`: API Description
* `{root}/conformance`: Conformance Classes
* `{root}/collections`: Collections
* `{root}/collections/{collectionid}`: Collection Information

It is necessary to advertise conformance with this Requirements Class.

include::requirements/atom/REQ_atom-conformance.adoc[]

include::requirements/atom/REQ_common-content.adoc[]

[#xml_content,reftext='{table-caption} {counter:table-num}']
.Media types and XML elements for each common resource[[table_3]]
[cols="30,35,35",options="header"]
|===
|Resource |Path |XML root element
|Landing page |`/` |`core:LandingPage`
|Conformance declaration |`/conformance` |`core:ConformsTo`
|Collections        |`/collections` |`core:Collections`
|Record collection +
(resource collection with `itemType=record`) |`/collections/{collectionId}` |`core:Collections`, with just one entry for the collection `collectionId`
|===

The namespace prefixes used above and in the OGC API Records Core XML schema is:

* `core`: `http://www.opengis.net/ogcapi-record-1/1.0`

* `atom`: `http://www.w3.org/2005/Atom`

* `xlink`: `http://www.w3.org/1999/xlink`

==== Records

In addition to HTML and GeoJSON, a significant volume of record data, especially in the Earth Observation space, is available in XML-based formats, notably https://tools.ietf.org/html/rfc4287[ATOM]. Therefore, this standard specifies requirements classes for https://tools.ietf.org/html/rfc4287[ATOM].

include::requirements/atom/REQ_media-type.adoc[]

include::requirements/atom/REQ_feed-extension-elements.adoc[]

include::requirements/atom/REQ_content.adoc[]

[#atom_content,reftext='{table-caption} {counter:table-num}']
.Media types and XML elements for each resource[[table_3]]
[cols="30,35,35",options="header"]
|===
|Resource |Path |XML root element
|Records |`/collections/{collectionId}/items` |`atom:feed`
|Record |`/collections/{collectionId}/items/{recordId}` |`atom:entry`
|===
