[[catalog-deployments]]
== Catalog deployments

=== Overview

This clause uses the <<building-blocks,building blocks>> defined in this Standard to define various catalog deployments.

[[clause-crawlable-catalog]]
=== Requirements Class "Crawlable Catalog" (Deployment)

[[crawlable-catalog-overview]]
==== Overview

include::requirements/requirements_class_crawlable-catalog.adoc[]

The `Crawlable Catalog` Requirements Class defines the requirements for a catalog composed of static, web-accessible files.

The goal of a crawlable catalog is to expose metadata about resources online with as low an entry barrier as possible, thus making those resources more easily discoverable.

A crawlable catalog is a deployment pattern that uses the <<clause-record-collection,collection>> and <<clause-record-core,record>> building blocks defined in this Standard.  It is simply a set of files deployed on the web, usually encoded as HTML or JSON, that conform to the <<clause-record-collection,collection>> and <<clause-record-core,record>> schemas defined in this Standard.  The files contain embedded links to enable navigation from one to another.  Any HTTP server or cloud storage service, for example, could be used to expose the files of a crawlable catalog.

A crawlable catalog is not searchable and does not respond to query requests.  As the name implies, it can only be crawled (or harvested) by following the embedded links, typically by search engines and other active catalogs or browsed using a web browser.  However, due to its simplicity, a crawlable catalog is easy to deploy and maintain, and is very reliable.

NOTE: It should be pointed out that a <<clause-searchable-catalog,searchable catalog>> can also behave as a crawlable catalog as long as the requirements in this clause are satisfied by the <<clause-searchable-catalog,searchable catalog>> implementation.

[[crawlable-catalog-record]]
==== Making a resource discoverable

include::requirements/crawlable-catalog/REQ_record.adoc[]

Attention is drawn to requirement <<per_record-core_additional-properties-record,/per/record-core/additional-properties-record>> that allows the information content of the record to be enriched as required to describe the resource being made discoverable.

include::requirements/crawlable-catalog/REQ_record-location.adoc[]

include::recommendations/crawlable-catalog/REC_record-file-name.adoc[]

include::recommendations/crawlable-catalog/REC_record-file-location.adoc[]

For example, the record file could be placed in the same web-accessible directory or object store as the resource(s) that the record describes.

[[crawlable-catalog]]
==== Grouping a collection of records into a catalog

include::requirements/crawlable-catalog/REQ_catalog.adoc[]

include::requirements/crawlable-catalog/REQ_catalog-location.adoc[]

include::requirements/crawlable-catalog/REQ_conformance.adoc[]

[[crawlable-collections]]
==== Organizing crawlable catalogs

In order to provide flexibility with regard to how crawlable catalogs can be organized (e.g. a hierarchy) this requirements class extends the <<clause-record-collection,Record Collection>> object used to organized related collections of records and allows a catalog to also provide information about and access to a related subordinate catalogs.  As such, the <<clause-record-collection,Record Collection object>> can be used as a common entry point for crawling to multiple, related, sub-catalogs, records and other resource types.

include::recommendations/crawlable-catalog/PER_other-catalogs.adoc[]

include::requirements/crawlable-catalog/REQ_catalog-itemType.adoc[]

include::requirements/crawlable-catalog/REQ_catalog-links.adoc[]

[[clause-searchable-catalog]]
=== Requirements Class "Searchable Catalog" (Deployment)

include::requirements/requirements_class_searchable-catalog.adoc[]

==== Overview

The Searchable Catalog Requirements Class defines the requirements for a catalog that is searchable through an API.  A searchable catalog is an implementation of the <<OAFeat-1,OGC API - Features - Part 1: Core>> Standard that uses a defined information model.  In the case of the OGC API - Records Standard, that information model is the <<clause-record-core,Record>>.

include::requirements/searchable-catalog/REQ_core.adoc[]

include::recommendations/searchable-catalog/PER_additional-requirements.adoc[]

include::requirements/searchable-catalog/REQ_mandatory-properties.adoc[]

include::recommendations/searchable-catalog/PER_additional-properties.adoc[]

[[clause-searchable-catalog_filtering]]
==== Requirements Class "Searchable Catalog - Filtering" (Deployment)

include::requirements/requirements_class_searchable-catalog_filtering.adoc[]

This requirements class specifies requirements and recommendations for supporting advanced filtering at searchable catalog endpoints.  Advanced filter expressions can only reference properties from an advertised set of queryables.
 
include::requirements/searchable-catalog_filtering/REQ_mandatory-queryables.adoc[]

include::recommendations/searchable-catalog_filtering/PER_additional-queryables.adoc[]

[[clause-searchable-catalog_sorting]]
==== Requirements Class "Searchable Catalog - Sorting" (Deployment)

include::requirements/requirements_class_searchable-catalog_sorting.adoc[]

The Searchable Catalog - Sorting requirements class specifies requirements for supporting sorting of responses at searchable catalog endpoints.

include::requirements/searchable-catalog_sorting/REQ_sorting.adoc[]

[[clause-local-resources-catalog]]
=== Requirements Class "Local Resources Catalog" (Deployment)

[[local-resources-catalog-overview]]
==== Overview

include::requirements/requirements_class_local-resources-catalog.adoc[]

The Local Resources Catalog requirements class specifies requirements for a _local resources catalog_.

The <<ogc-api-resource-tree,set of OGC API Standards>> define a number of resource endpoints that provide lists of sub-resources.  These endpoints are referred to as _local resources catalogs_ in this Standard because they provide metadata about resources offered locally by a deployment of some or all of the <<ogc-api-resource-tree, set of OGC API Standards>>.

[[local-resources-endpoint]]
NOTE: The term _local resources endpoint_ is used to reference the resource path of the _local resources catalog_.  The term _local resources object_ is used to refer to an instance of the object or resource that can be retrieved from the _local resources endpoint_.

The `/collections` endpoint is an example of a _local resources endpoint_.  This endpoint provides a list of objects describing the collections of items offered by an OGC API deployment.  Each offered collection (path `/collections/{collectionId}`) is described by a _local resources object_ containing a small number of properties.  A common set of properties is defined in  https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] and can be extended by resource-specific specifications (e.g. http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Feature - Part 1: Core]).  In this respect, the `/collections` endpoint is a catalog of collections (i.e. `/collections/{collectionId}` objects) describing the collections of items offered by the OGC API deployment.

Other _local resources catalogs_ available in the <<ogc-api-resource-tree,OGC API resource tree>> include the `/processes` endpoint which provides a list of offered processes and the `/collections/{collectionId}/scenes` endpoint which provides a list of source images of a coverage.

In order to enable catalog-like searching at these local resources endpoints, this requirements class defines requirements and recommendations that enhance the information content of each local resources object  (e.g. the `/collection/{collectionId}` object) with additional members from the list of <<core-properties,core record properties>>.

Other requirements classes in this Standard:

1. optionally define or extend the set of query parameters available at the local resources endpoint (e.g. `/collections`) to enhance its basic searchability,

2. optionally define or extend the set of query parameters available at the local resources endpoint (e.g. `/collections`) to support advanced searching using a filter language,

3. optionally support sorting of the response from a local resources endpoint.

The Local Resources Catalog requirements class does not define the specific endpoints in the <<ogc-api-resource-tree,OGC API resource tree>> that should be enabled with catalog-like query capabilities.  It only defines how those endpoints should be enhanced should the requirement for catalog-like searching be identified by the responsible OGC Standard.  It is anticipated that the responsible OGC standard will define a requirements class or extension to enable local resources catalog capabilities at that endpoint.

==== Resource Description

The clause defines requirements and recommendations for the information content of a local resources object that can be retrieved from a local resources endpoint.

As an example of a local resources endpoint, consider the `/collections` endpoint.  The object that can be retrieved from this endpoint is defined in https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_collections_[OGC API - Features].  The following table cross-walks the information content of the collection object with the <<core-properties,core properties>> defined for the <<clause-record-core,record>> building block:

[[record-collection-crosswalk]]
[reftext='{table-caption} {counter:table-num}']
.Crosswalk of core properties with collection information object properties
[cols="25,25,25,25",options="header"]
|===
|Property of `/collections` object |Requirement  |Property of <<core-properties,Record>> object |Requirement
|id                      |**required**  |recordId       |**required**
|title                   |optional      |title          |**required**
|description             |optional      |description    |optional
|itemType                |optional      |--             |--
|--                      |--            |type           |**required**
|extent                  |optional      |geometry       |optional
|links                   |**required**  |links          |**required**
|linkTemplates           |optional      |linkTemplates  |optional
|crs                     |optional      |--             |--
|===

As can be seen, there is a significant overlap of the properties of each resource.  This standard defines the following requirements and recommendations regarding information content of a local resources object such as the collection object that is retrievable from the `/collections` endpoint.

==== Property `recordId`

include::requirements/local-resources-catalog/REQ_property-recordId.adoc[]

==== Property `title`

include::requirements/local-resources-catalog/REQ_property-title.adoc[]

==== Property `type`

include::requirements/local-resources-catalog/REQ_property-type.adoc[]

include::requirements/local-resources-catalog/REQ_property-type-value.adoc[]

For example, the value of the `type` member in an extended feature collection object (path: `/collections/{collectionId}`) might be defined to be `featureCollection`.  Similarly, the value of the `type` member in an extended process summary (path: `processes/{processId}`) might be defined to be `process`.

==== Additional properties

include::recommendations/local-resources-catalog/PER_additional-properties.adoc[]

==== Property `created`

include::requirements/local-resources-catalog/REQ_property-created.adoc[]

==== Property `updated`

include::requirements/local-resources-catalog/REQ_property-updated.adoc[]

NOTE: Adding, modifying, or deleting items from a collection are all examples of changes that may occur that would require an update of the collection object that can be retrieved from the `/collections` endpoint.

==== Property `description`

include::recommendations/local-resources-catalog/PER_common-mark.adoc[]

==== Examples

===== Collection local resource

The following JSON Schema fragment illustrates how the feature collection object (path: `/collection/{collectionId}`) can be extended to include properties required and recommended by this conformance class:

[source,yaml]
----
include::../examples/yaml/collectionLocalResource.yaml[]
----

[NOTE]
======================================================================
Referenced schemas can be found at:

* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordCommonProperties.yaml[recordCommonProperties.yaml],
* https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml[collection.yaml].
======================================================================

===== Process Summary local resource

The following JSON Schema fragment illustrates how the process summary object (path: `/processes/{processId}`) can be extended to include properties required and recommended by this conformance class:

[source,yaml]
----
include::../examples/yaml/processSummaryLocalResource.yaml[]
----

[NOTE]
======================================================================
Referenced schemas can be found at:

* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordCommonProperties.yaml[recordCommonProperties.yaml],
* https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml[collection.yaml].
======================================================================

NOTE: T.D.B.  Should add an instance example of a collection object.

==== Discovery of local resources endpoints

Discovery of which local resources endpoints in an OGC API deployment are instrumented for catalog-like searching is accomplished using <<clause-autodiscovery,Autodiscovery>>.

[[clause-local-resources-catalog_query-parameters]]
==== Requirements Class "Local Resources Catalog - Query Parameters" (Deployment)

include::requirements/requirements_class_local-resources-catalog_query-parameters.adoc[]

===== Operation

include::requirements/local-resources-catalog_query-parameters/REQ_query-parameters.adoc[]

===== Response

include::requirements/local-resources-catalog_query-parameters/REQ_response.adoc[]

[[clause-local-resources-catalog_filtering]]
==== Requirements Class "Local Resources Catalog - Filtering" (Deployment)

include::requirements/requirements_class_local-resources-catalog_filtering.adoc[]

The Local Resources Catalog - Filtering requirements class specifies requirements and recommendations for supporting advanced filtering at _local resource catalog_ endpoints.

===== Operation

include::requirements/local-resources-catalog_filtering/REQ_filter-param.adoc[]

include::requirements/local-resources-catalog_filtering/REQ_filter-lang-param.adoc[]

include::recommendations/local-resources-catalog_filtering/REC_text-encoding.adoc[]

include::recommendations/local-resources-catalog_filtering/REC_json-encoding.adoc[]

include::requirements/local-resources-catalog_filtering/REQ_filter-crs-param.adoc[]

include::requirements/local-resources-catalog_filtering/REQ_queryables-link.adoc[]

===== Response

include::requirements/local-resources-catalog_filtering/REQ_filter-response.adoc[]

[[clause-local-resources-catalog_sorting]]
==== Requirements Class "Local Resources Catalog - Sorting" (Deployment)

include::requirements/requirements_class_local-resources-catalog_sorting.adoc[]

The Local Resources Catalog - Sorting requirements class specifies requirements and recommendations for supporting sorting of responses at _local resource catalog_ endpoints.

===== Operation

include::requirements/local-resources-catalog_sorting/REQ_param-sortby-def.adoc[]

===== Response 

include::requirements/local-resources-catalog_sorting/REQ_param-sortby-response.adoc[]

See also: <<req_sorting_get-sortables-op,/req/sorting/get-sortables-op>>, <<req_sorting_get-sortables-success,/req/sorting/get-sortables-success>>.

===== Examples

Example 1: List all the collections that lie within a specific bounding box and contain the keyword `weather`.

----
   Client                                                          Server
     |                                                               |
     |   GET /collections?bbox=41.875315,-96.767601,56.732861,-73.476|
     |   586&q=weather   HTTP/1.1                                    |
     |   Accept: application/json                                    |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 200 OK                                             | 
     |   Content-Type: application/json                              |
     |                                                               |
     |   T.B.D. Need example output here...                          |
     |<--------------------------------------------------------------|
----

