[[clause-record-filter]]
== Requirements Class "CQL Filter"

[[record-filter-overview]]
=== Overview

include::requirements/requirements_class_record-filter.adoc[]

This clause defines the binding to the filter parameters defined in the https://docs.ogc.org/DRAFTS/19-079.html#_requirements_class_filter[OGC API - Features - Part 3: Filter and the Common Query Language (CQL), Requirements Class "Filter"] clause.

=== Records

==== Operation

As specified in the <<records-access,Records Access>> clause, records are accessed using the HTTP GET method via the `/collections/{collectionId}/items` path.  The following additional requirements bind the parameters https://docs.ogc.org/DRAFTS/19-079.html#filter-param[filter], https://docs.ogc.org/DRAFTS/19-079.html#filter-lang-param[filter-lang] and https://docs.ogc.org/DRAFTS/19-079.html#filter-filter-crs[filter-crs] to the GET operation on this path.

include::requirements/record-filter/REQ_filter-param.adoc[]

include::requirements/record-filter/REQ_filter-lang-param.adoc[]

include::recommendations/record-filter/REC_text-encoding.adoc[]

include::recommendations/record-filter/REC_json-encoding.adoc[]

// TODO include::requirements/record-filter/REQ_cql-atom.adoc[]
// TODO include::requirements/record-filter/REQ_cql-html.adoc[]

include::requirements/record-filter/REQ_filter-crs-param.adoc[]

==== Response

include::requirements/record-filter/REQ_response.adoc[]

=== Filtering on links/associations

==== Overview

Links can be added to a catalogue record in various ways.  This clause 
describes the various linking patterns and describes how to use CQL to
filter based on links/associations.

==== Linking in records

Links can be added to the following sections in a catalogue record:

. the <<query-response,links>> section.
. the <<query-response,associations>> section.
. the <<query-response,properties>> section.

The schema for links added to the <<query-response,links>> and <<query-response,associations>> sections in based on https://tools.ietf.org/html/rfc8288[RFC 8288] and is described in https://docs.ogc.org/DRAFTS/19-072.html#link-relation-conventions[OGC API - Common - Part 1: Core] and http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml[OGC API - Features - Part 1: Core].

Links added directly to the <<query-response,properties>> section of a catalogue record can be
added using the following patterns:

. The link relation is the key for an array of links with a schemas similar to that used in the <<query-response,links>> and <<query-response,associations>> sections but omitting the `rel` key.
. The link relation is the key for an array of `href` values.
. The link relation is the key for an an `href` value.

The following examples illustrate each of these linking patterns:

[#linking-pattern-1,reftext=`Adding links to the **links** section.`]
.Adding links to the **links** section
----
{
   .
   .
   .,
   "properties": {
      .
      .
      .,
      "links":
      [
         .
         .
         .,
         {
            "rel" : "alternate",
            "title" : "This records as XML.",
            "href" : "https://example.com/collections/MyCat/items/rec01.xml"
         },
         {
            "rel": "next",
            "title": "The next record in this result set.",
            "href" : "https://example.com/collections/MyCat/items/rec02"
         },
         .
         .
         .
      ],
      .
      .
      .
   }
}
----

[#linking-pattern-2,reftext=`Adding links to the **associations** section.`]
.Adding links to the **associations** section
----
{
   .
   .
   .,
   "properties": {
      .
      .
      .,
      "associations":
      [
         .
         .
         .,
         {
            "rel" : "related",
            "title" : "A related record.",
            "href" : "https://example.com/collections/YourCat/items/rec15"
         },
         {
            "rel": "license",
            "title": "CC BY 2.0",
            "href" : "https:https://creativecommons.org/licenses/by/2.0/"
         },
         .
         .
         .
      ],
      .
      .
      .
   }
}
----

[#linking-pattern-3,reftext=`Adding links to the **properties** section.`]
.Adding links to the **properties** section
----
{
   .
   .
   .,
   "properties": {
      .
      .
      .,

      "related": [
         {
		      "title" : "A related record",
		      "href" : "https://example.com/related-record-path/rec15"
	      }
      ],
      "license": {
		   "title" : "CC BY 2.0",
		   "href" : "https://creativecommons.org/licenses/by/2.0/"
	   },
      .
      .
      .
   }
}
----

[#linking-pattern-4,reftext=`Adding links to the **properties** section.`]
.Adding links to the **properties** section
----
{
   .
   .
   .,
   "properties": {
      .
      .
      .,

      "related": ["https://example.com/related-record-path/rec15"],
      "license": "https://creativecommons.org/licenses/by/2.0/",
      .
      .
      .
   }
}
----

==== Example CQL filters on links/associations

The following example illustrate how to filter links/associations that may
appear in a catalogue record.

[#filter-pattern-1,reftext=`Filtering links in the **links** section.`]
.Filtering links in the **links** section
----
links[rel='license'].title LIKE 'CC%'
----

[#filter-pattern-2,reftext=`Filtering links in the **associations** section.`]
.Filtering links in the **associations** section
----
properties.associations[rel='related'].href LIKE '%/rec15'
----

[#filter-pattern-3,reftext=`Filtering links in the **properties** section.`]
.Filtering links in the **properties** section
----
properties.related[*].href LIKE '%/rec15' AND properties.license.title LIKE 'CC%'
----

[#filter-pattern-4,reftext=`Filtering links in the **properties** section.`]
.Filtering links in the **properties** section
----
properties.related LIKE '%/rec15' AND properties.license LIKE 'https://creativecommons.org/licenses/%'
----
