== Conformance

Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance, are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The one Standardization Target for this standard is Web APIs.

OGC API - Common provides a common foundation for OGC API standards. Therefore, this standard should be viewed as an extension to API - Common. Conformance to this standard requires demonstrated conformance to the applicable Conformance Classes of API - Common. 

This standard identifies eleven (11) Conformance Classes. The Conformance Classes implemented by an API are advertised through the `/conformance` path on the landing page. Each Conformance Class has an associated Requirements Class. The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.

The Requirements Classes for OGC API - Records are:

* *Core*
* *Collections*
* *OpenSearch*
* *JSON-Record*
* *ATOM-Record*
* *HTML-Record*

// P.A.V.
// Core includes: the parameters  -> bbox [bbox_crs], time, limit, offset, 
//                core queryables -> id(m), title(m), description(m),
//                                   keywords(m), extent(o), modified(o),
//                                   publisher(o), themes(o), license(o),
//                                   rights(o), links(o)
// Question: Should CQL be part of the core?
The _Core_ Requirements Class is the minimal useful service interface for the OGC Records API. The requirements specified in this Requirements Class are mandatory for all implementations of API - Records.  The core defines a set of mandatory properties (core queryables) that every record must contain, a set of core query parameters that support bounding box spatial queries, temporal queries, full text searching, parameters for sorting responses.

The _OpenSearch_ Requirements Class defines the requirements to support query by OpenSearch clients.

// P.A.V.
// This requirements class makes the /collections end point of a service
// queryable using the OAPIR core queryables and query API.
// If a servers wants to make its /collections end point queryable it has
// to do the following:
// 1. Add the approriate conformance URIs to is /conformance document.  There
//    may be more than one depending on the level of query capability offered
//
//    http://www.opengis.net/spec/ocgapi-records-1/1.0/queryable-collections
//    http://www.opengis.net/spec/ocgapi-records-1/1.0/cql-queryable-collections
//
// 2. Add the mandatory core queryables as keys in the collection object
//    if those keys are not already there
//
// 3. Add zero or more optional core queryables to the collection object
//
// 4. Implement the query parameters of the /collection end-point (core+).
//
// 5. The response is exactly what it would be if you fetched the /collections
//    resource but the only collections listed would be the ones that satisfy
//    the query predicates
The _Collections_ Requirements Class defines requirements for making the 
`/collections` endpoint of any OGC Web API searchable.

The _JSON_ Requirements Class defines the requirements for a GeoJSON (see RFC 7946) representation of a standard catalogue record.

The _ATOM_ Requirements Class defines the requirements for an ATOM representation of a standard catalogue record.

The _HTML_ Requirements Class defines the requirements for an HTML representation of a standard catalogue record.
