[[building-blocks]]
== Common Components

=== Overview

This clause specifies requirements classes that define common components that can be used to define various <<catalog-deployments,catalog deployments>>.

[[clause-record-core]]
=== Requirements Class "Record Core" (Common Component)

[[record-core-overview]]
==== Overview

include::requirements/requirements_class_record-core.adoc[]

[[record-model]]
The `Record` Requirements Class defines the requirements for a catalog record which is the atomic unit of information of a catalog.

It is expected that the information necessary to populate the fields/properties of a catalog record is readily available for any resource that is being registered in the catalog.

The expectation is that the schema of a record will be extended to describe specific resource types (e.g. datasets, services, etc.) as well as also extended by information communities wishing to enrich the information content of the record to suit their needs.

Although this Standard does not mandate any particular encoding for a record, this document does define conformance classes for two encodings:

* a <<clause-record-encoding-json,GeoJSON>> record encoding, and
* an <<requirements-class-html-clause,HTML>> encoding.

Other encodings are allowed but are not described in this document.

[[core-properties]]
==== Core properties

<<core-properties-record-table>> and <<core-properties-resource-table>> define the set of properties, called the _core properties_, that may be included in a record.

[#core-properties-record-table,reftext='{table-caption} {counter:table-num}']
.Table of Core Properties related to the catalog record
[cols="20,5,55,20",options="header"]
|===
|Property |Requirement |Description |GeoJSON key
|id |**required** |A unique record identifier assigned by the server. |`id`
|created |optional |The date this record was created in the server. |`properties.created`
|updated |optional |The most recent date on which the record was changed. |`properties.updated`
|conformsTo |optional |The extensions/conformance classes used in this record. |`conformsTo`
|===

[#core-properties-resource-table,reftext='{table-caption} {counter:table-num}']
.Table of Core Properties related to the resource
[cols="20,5,55,20",options="header"]
|===
|Property |Requirement |Description |GeoJSON key
|type |optional |The nature or genre of the resource. |`properties.type`
|title |optional |A human-readable name given to the resource. |`properties.title`
|description |optional |A free-text description of the resource. |`properties.description`
|geometry |optional |A spatial extent associated with the resource. +
Can be `null` if there is no associated spatial extent. |`geometry`
|time |optional |A temporal extent associated with the resource. +
Can be `null` if there is no associated temporal extent. |`time`
|keywords |optional |A list of free-form keywords or tags associated with the resource. |`properties.keywords`
|themes |optional |A knowledge organization system used to classify the resource. |`properties.themes`
|language |optional |The language used for textual values (i.e. titles, descriptions, etc.) of this record. |`properties.language`
|languages |optional |The list of other languages in which this record is available. |`properties.languages`
|resourceLanguages |optional |The list of languages in which the resource described by this record can be retrieved. |`properties.resourceLanguages`
|externalIds |optional |One or more identifiers for the resource assigned by an external entity. |`properties.externalIds`
|formats |optional |A list of available distributions for the resource. |`properties.formats`
|contacts |optional |A list of contacts qualified by their role(s) in association to the record or resource. |`properties.contacts`
|license |optional |The legal provisions under which the resource is made available. |`properties.license`
|rights |optional |A statement that concerns all rights not addressed by the license such as a copyright statement. |`properties.rights`
|[[record-links-section]]links |optional |A list of links related to this record.|`links`
|linkTemplates |optional |A list of link templates related to this record. |`linkTemplates`
|===

include::requirements/record-core/REQ_mandatory-properties-record.adoc[]

include::recommendations/record-core/PER_common-mark.adoc[]

include::recommendations/record-core/PER_additional-properties-record.adoc[]

[[sc_record_extensions]]
==== Record extensions

In <<core-properties-record-table>> and <<core-properties-resource-table>> this Standard defines a set of core properties for describing discoverable resources.  It is anticipated that this set of core properties will be extended to suit specific use cases or requirements.  For example, a catalog record may be extended to include additional properties from the https://semiceu.github.io/GeoDCAT-AP/releases/[GeoDCAT] vocabulary.  The fact that a catalog record has been extended in this way can be advertised using the `conformsTo` property.  The `conformsTo` property is a list of identifiers that indicate each extension used in a record.  This Standard does not define the specific identifiers that are used to identify specific extensions; it simply provides a place where these identifiers can be listed.

include::recommendations/record-core/REC_record-extensions.adoc[]

In the case where all the records of a catalog use the same set of extensions, and to prevent unnecessary duplication, there is also a `conformsTo` property at the https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/catalog.yaml[catalog level] that may be used to declare which extensions are used in all records of the catalog.  

NOTE: Extensions listed at the catalog and record levels are cumulative.

[[sc_type]]
==== Type

In order to facilitate the ability to discover resources of a particular type(s), this Standard makes the following recommendations:

include::recommendations/record-core/REC_record-type.adoc[]

include::recommendations/record-core/PER_record-type.adoc[]

In addition, links to external resources describing the record type vocabulary used to populate the `type` property are recommended, as described in <<sc_associations_and_links,Associations and Links>>.

[[sc_title-description]]
==== Title and description

In order to facilitate the discovery of resources utilizing keyword or free-text searches, this Standard makes the following recommendation:

include::recommendations/record-core/REC_record-title.adoc[]

include::recommendations/record-core/REC_record-description.adoc[]

[[sc_spatial_information]]
==== Spatial information
The spatial characteristic of the resource described by a record is specified using the optional `geometry` property.

include::recommendations/record-core/PER_record-geometry.adoc[]

For example, the <<rc_json,JSON>> requirements class makes the `geometry` member mandatory because the record encoding (i.e. https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON]) requires that the `geometry` member be mandatory.

[[sc_temporal_information]]
==== Temporal information

===== Overview

Many records have a geometry property that provides information about the primary spatial characteristics of the resource described by the record.  Records often also have temporal information.  In most cases time is either an instant (e.g., an event) or an interval (e.g., an activity or a temporal validity). In OGC API Records the temporal property is reflected in the <<core-query-parameters-datetime,datetime>> parameter which supports temporal filtering.

This Standard added support for the most common temporal case: Associating a resource with a single temporal instant or interval in the Gregorian calendar.  More complex cases and other temporal coordinate reference systems are out-of-scope for this Standard and might be specified in future extensions.

Records can have multiple properties that describe the temporal characteristics of the resource(s) that the record describes.

* In many records all temporal properties are instants (represented by a date or a timestamp) and intervals are described using two temporal instants, one for the start and one for the end.

* Multiple temporal properties are sometimes used to describe different temporal characteristics of the resource(s) the record describes. For example, the time instant or interval when the information in the record is valid (sometimes called "valid time") and the time when the record was recorded in the catalog (sometimes called "transaction time"). Another example is the https://www.ogc.org/standards/om[Observations & Measurements standard], where an observation has multiple temporal properties including "phenomenon time", "result time" and "valid time".

This Standard does not place any constraints on the number of additional temporal properties that may be added to a record to characterize temporal aspects of the resource being described by a record.  This can make it difficult for a naive client to recognize and utilize temporal information stored in the record.  For this reason, this Standard includes the `time` property in a record.  

include::recommendations/record-core/REC_time.adoc[]

This `time` property is set by the publisher of the record and describes characteristic temporal information (an instant or an interval) associated with the resource described by a record.   This `time` property can thus be used by naive clients without the need to inspect or understand the schema of an extended record.  If included in the record, the value of the `time` property is either `null` (no temporal information) or an object encoding a time instant or interval.

.Properties of the "time" object
[cols="20,10a,70a",options="header"]
|===
|Property |Type |Description
|`date` |string |An instant with the granularity of a date. See below for more details about instants.
|`timestamp` |string |An instant with the granularity of a timestamp. See below for more details about instants.
|`interval` |[ string ] |An interval, described by an array of the two instants (start and end). See below for more details about intervals.
|===

If both values interest, including both an instant and an interval is valid. In this case, clients should use the interval property and may use the date or timestamp property to determine the temporal characteristics of the resource being described by the record.

The "time" object may be extended with additional properties. Clients processing a "time" object must be prepared to parse additional properties. Clients should ignore properties that they do not understand. For example, in cases where the "time" property neither includes an "instant" nor "interval", a client may process the record as a record without temporal information.

NOTE: The data publisher decides how additional temporal properties are encoded in a record. The schema for the `time` property  does not imply a recommendation that temporal properties reuse the same schema. For example, it is expected that a date-valued record properties will in most cases be represented as a string with an RFC 3339 date value.

===== Instants

An instant is a value that conforms to https://datatracker.ietf.org/doc/html/rfc3339[RFC 3339 (Date and Time on the Internet: Timestamps)] and is consistent with one of the following production rules of the ISO 8601 profile specified in the RFC:

* `full-date` (e.g., `"1969-07-20"`)
* `date-time` (e.g., `"1969-07-20T20:17:40Z"`)

Conceptually, an instant is a "temporal entity with zero extent or duration" [<<owl-time,Time Ontology in OWL>>]. In practice, the temporal position of an instant is described using data types where each value has some duration or granularity. The value should be described with a granularity that is sufficient for the intended use of the data.

In the case of a timestamp the granularity is a second or smaller. All timestamps must be in the time zone UTC ("Z").

In the case of a date the granularity is a day and dates as instants will be used when a granularity of a day independent of its timezone is sufficient for the intended use of the data. If that is not the case and, for example, the timezone is important for the intended use, the temporal information should be provided as an interval with start and end timestamps.

NOTE: This Standard only provides guidance as to how record data is represented in JSON. It is out-of-scope for this Standard to provide guidance how to cast record data to other data types. The https://docs.ogc.org/DRAFTS/21-065.html[Common Query Language (CQL2)] standard uses the same model of instants and intervals as used here and includes additional guidance on how to compare values.

[#ex-time-1,reftext='{listing-caption} {counter:listing-num}']
.A date
====
[source,json,linenumbers]
----
"time" : {
    "date": "1969-07-20"
}
----
====

[#ex-time-2,reftext='{listing-caption} {counter:listing-num}']
.A timestamp
====
[source,json,linenumbers]
----
"time" : {
    "timestamp": "1969-07-20T20:17:40Z"
}
----
====

Dates and timestamps are the initial range of instant values. The range may be extended in the future to support additional use cases. Clients processing values of `time` must be prepared to receive other values. Clients may ignore values that they do not understand.

include::requirements/record-core/REQ_time-instant.adoc[]

include::recommendations/record-core/PER_temporal_comparison.adoc[]

===== Intervals

An interval is described by start and end instants. Both start and end instants are included in the interval, i.e., the interval is closed.

The end of unbounded intervals is represented by a double-dot string (`..`) for the start/end. This follows the convention of ISO 8601-2 for an open start or end.

[#ex-time-3,reftext='{listing-caption} {counter:listing-num}']
.An interval with dates
====
[source,json,linenumbers]
----
"time" : {
    "interval": [
        "1969-07-16",
        "1969-07-24"
    ]
}
----
====

[#ex-time-4,reftext='{listing-caption} {counter:listing-num}']
.An interval with timestamps
====
[source,json,linenumbers]
----
"time" : {
    "interval": [
        "1969-07-16T05:32:00Z",
        "1969-07-24T16:50:35Z"
    ]
}
----
====

[#ex-time-5,reftext='{listing-caption} {counter:listing-num}']
.An half-bounded interval
====
[source,json,linenumbers]
----
"time" : {
    "interval": [
        "2014-04-24T10:50:18Z",
        ".."
    ]
}
----
====

The options described above are the initial range of interval values - the granularity is either days or (sub-)seconds and interval ends may be unbounded. The value range may be extended in the future to support additional use cases. Clients processing values of `time` must be prepared to receive other values. Clients may ignore values that they do not understand.

include::requirements/record-core/REQ_time-interval.adoc[]

===== Instants and intervals

include::requirements/record-core/REQ_time-instant-interval.adoc[]

===== Time zones

include::requirements/record-core/REQ_time-zone.adoc[]

[[sc_keywords_and_themes]]
==== Keywords and Themes

A record allows for one `keywords` and one to many `themes` properties.  Keywords are free form terms or tags associated with the resource(s) that the record describes.  Themes are concepts associated with the resource(s) that a record describes taken from one or more formal knowledge organization systems or schemes.  The list of knowledge organization systems or schemes used in a <<clause-searchable-catalog,searchable>> or <<clause-local-resources-catalog,local resources>> catalog can be determined by inspecting the server's OpenAPI document or, if the server implements CQL2, by exposing a queryable (e.g. named `scheme`) and enumerating the list of schemes used in the queryable's schema definition.

include::recommendations/record-core/REC_record-keywords-themes.adoc[]

The following provides an example of using keywords for free form terms (e.g. tags) as well as themes to articulate terms from formal vocabularies or classification systems.

[#keywords-themes-example,reftext=`Keywords and themes Example`]
.Keywords and themes Example
[source,json]
----
include::../examples/json/keywords-themes.json[]
----

[[sc_formats]]
==== Formats

The `formats` property indicates the list of available distribution formats for the resource that a record describes.  These can include both physical and digital distribution formats.

The following example illustrates a resources that is a available is several formats.

[#formats-example,reftext=`Formats Example`]
.Formats Example
[source,json]
----
"formats": [
  { "name": "TK50" },
  { "name": "GRIB", "mediaType": "application/x-grib" },
  { "mediaType": "application/zip"}
]
----

include::recommendations/record-core/REC_format.adoc[]

[[sc_record_language_handling]]
==== Language handling

===== Overview

A catalog record can include language information about:

* The resource that the record describes.
* The language used for text values in the current record representation.
* Alternate languages in which the current record can be represented.

===== Language of the record

include::recommendations/record-core/REC_record-lang.adoc[]

The https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml[link object] and the https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/linkTemplate.yaml[templated link object] are based on https://datatracker.ietf.org/doc/html/rfc8288[RFC 8288 (Web Linking)] includes a `hreflang` attribute that can be used to state the language of a referenced resource.  This can be used to include links to the same record in different languages. 

[[minting-language-specific-uris]]
A server that wants to use language-specific links will have to support a mechanism to mint language-specific URIs to express links to the same record in other languages or to express links to the resource described by record in multiple languages.  This document does not mandate any approach how such a capability is supported by a server. 

[NOTE]
======================================================================
Two common approaches are:

* An additional path element for each language-specific encoding of a record or resource (this can be expressed, for example, using a language-specific path element like `.../en-ca/...`);

* An additional query parameter (for example, https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/parameters/language.yaml["language"] or "l") that overrides the Accept-Language header of the HTTP request.
======================================================================

[NOTE]
======================================================================
There is no provision in the record schema to allow a response containing text fields simultaneously presented in multiple languages (e.g. multiple titles in different languages).  To obtain a record in multiple languages would require multiple requests to the server each negotiating to a desired language.
======================================================================

===== Language of the resource

include::recommendations/record-core/REC_resource-langs.adoc[]

[[sc_contacts]]
==== Contacts

include::requirements/record-core/REQ_contact.adoc[]

include::recommendations/record-core/REC_contact.adoc[]

[[sc_license]]
==== License

A record may have one `license` property. If present, the value of this property should be a code, convenient for filtering records.

include::requirements/record-core/REQ_record-license.adoc[]

[[sc_associations_and_links]]
==== Associations and Links

A record must contain a `links` section and may contain a <<sc_templated_links_with_variables,`linkTemplates`>> section.  These sections contain navigation links and/or association links.

Navigation links are meant to encode relationships between catalog entities (i.e. <<clause-record-collection,collections>> and <<clause-record-core,records>>).  Navigation links in the `links` section can include links to the collection (eotion: `collection`) of which a record is a member, alternative representations (relation: `alternate`) of the record, and -- in the context of an API -- navigation links to previous (relation: `prev` or `previous`) or next (relation: `next`) records in a chain of records.  Links in the `links` section may also be used to organize records in a hierarchy (relation: `root`, relation: `parent`, relation: `child`).

include::requirements/record-core/REQ_record-links.adoc[]

include::recommendations/record-core/REC_links.adoc[]

Links in the `links` section may also encode canonical URIs for record properties such as `type` and `license`.

include::recommendations/record-core/REC_record-links_type.adoc[]

include::recommendations/record-core/REC_record-links_iana.adoc[]

Association links point to the resource(s) being described by a record. Such links allow binding to a resource once it has been discovered by searching a catalog.  Depending on how the target resource of a record is represented and how it may be accessed, there may be one or more association links.  For example, if the target resource is an Earth observation imagery file, links may point to the individually accessible bands of the image file.

Association links are also meant to point to other records related to the containing record.  For example, consider a record that describes a set of vector features and another record that describes a rendering style for that feature set.  These two records may, in their respective `links` sections point to each other to encode this "styles"/"styled-by" relationship.

Finally, association links are meant to point to other resources external to the catalog that are related to the containing record or the resource(s) that the record describes.

include::recommendations/record-core/REC_record-associations_relate.adoc[]

In some instances, additional context may be desirable or required to access (or bind to) the resource(s) being described by a record.  This is the case when, for example, access to the resource is through a service interface that requires mandatory parameters to be provided.  An implementation of the OGC Web Map Service (WMS) Standard is an example of such a service.  It may also be the case that efficient access to the resource would be facilitated by providing additional context.  Accessing data from a large data repository such as a data cube would be more efficient if the context of the query used to discover the resource (e.g. bbox, datetime) were passed down to the link used to access the data.

include::recommendations/record-core/REC_record-associations_templated.adoc[]

NOTE: This Standard does not define any specific link relations that should be used for links in the `links` or <<sc_templated_links_with_variables,`linkTemplates`>> sections.  Such relationships are typically domain specific and so it is left to communities of interest to standardize the relations that links should use.

The following provides an example of using association links for related resources of a record, as both traditional links as well as link templates.

[#associations-simple-and-uri-template-example,reftext=`Associations simple and URI Template Example`]
.Associations simple and Link Template Example
[source,json]
----
include::../examples/json/associations-simple-and-uri-template.json[]
----

[#links-in-https-headers,reftext=`Example of links in HTTP headers`]
￼.Example of links and link templates in HTTP headers
[source]
----
Link: <https://woudc.org/data/stations>; rel="search"; type="text/html"
Link-Template: <https://geo.woudc.org/ows?service=WMS&version=1.3.0&request=GetMap&crs={crs}&bbox={bbox}&layers=stations&width={width}&height={height}&format=image/png>; rel="item"; type="image/png"; varBase="https://geo.woudc.org/variables/"
----

[[sc_templated_links_with_variables]]
==== Templated links with variables

The OGC API - Records Standard uses links to express associations between resources including links that bind to the resource(s) being described by a record.  In some situations, a static link does not adequately express all the information necessary to retrieve the referenced resource OR does not allow for the resource to be retrieved in an efficient manner.

Consider the case where a record describing a coverage resource is discovered by searching the catalog using a spatial constraint (e.g. a bbox).  Further consider that the found record contains a link to retrieve the coverage.  Using a static link would only allow for retrieval of the entire coverage or a subset unrelated to the user's original catalog query.  Using a templated link, however, would allow the context of the catalog query (i.e. the bbox) to be passed to the retrieval link as a substitution variable.  The templated link with all substitution variables resolved would thus retrieve the subset of the coverage that corresponds to the spatial constraint used to discover the record in the first place which presumably represents the area of interest.

Templated links may also be used to bind to resources that may require additional information in order to access the resources.  For example, simply knowing the URL of a legacy OGC service instance such as for https://portal.ogc.org/files/?artifact_id=14416[WMS] or https://docs.ogc.org/is/09-025r2/09-025r2.html[WFS] implementations is not sufficient to access resources offered by those services.  Additional information in the form of request parameters and values is required in order to have a complete link to a resource.  A templated link with variables can provide this additional context.

This Standard defines a new schema, https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/linkTemplate.yaml[linkTemplate.yaml],  based on the https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml[schema for a link] that includes substitution variables who's values are filled in at runtime prior to resolving the link.  

Information about the substitution variables can be obtained in one of two ways.  The `variable` property may be used to encode the definitions of substitution variables in-line in the link.  Alternatively, the `varBase` property can be used to specify a base URI to which a variable name may be appended to retrieve the definition of the specified substitution variable.

include::requirements/record-core/REQ_templated-link.adoc[]

include::recommendations/record-core/REC_templated-link.adoc[]
￼
include::requirements/record-core/REQ_templated-link-header.adoc[]
￼
following example illustrates a link template to a legacy OGC Web service.  The example includes both an in-line and referenced dictionaries of substitution variables.
￼
[#templated-link-with-variables-inline,reftext=`Templated link example 1`]
.Templated link with in-line dictionary of substitution variables:
[source,json]
----
include::../examples/json/templated-link-inline.json[]
----
￼
[#templated-link-with-variables-ref,reftext=`Templated link example 2`]
.Templated link with `varBase` URI for retrieving substitution variable definitions:
[source,json]
----
include::../examples/json/templated-link-ref.json[]
----
￼
[#variable-def,reftext=`Variable definition example`]
.Using `varBase` to retrieve the definition of the variable bbox
----
   CLIENT                                                     SERVER
     |                                                           |
     |   GET variables/bbox HTTP/1.1                             |
     |   Host: example.org                                       |
     |   Accept: application/json                                |
     |---------------------------------------------------------->|
     |                                                           |
     |   HTTP/1.1 200 OK                                         |
     |   Content-Type: application/json                          |
     |                                                           |
     |   {                                                       |
     |     "bbox": {                                             |
     |       "description": "...",                               |
     |       "type": "array",                                    |
     |       "items": {                                          |
     |         "type": "number",                                 |
     |         "format": "double"                                |
     |       },                                                  |
     |       "minItems": 4,                                      |
     |       "maxItems": 4                                       |
     |     }                                                     |
     |   }                                                       |
     |<----------------------------------------------------------|
----

==== Resource timestamps

A <<clause-record-core,record>> contains information, encoded in the links and link templates sections, for accessing one or more resources described by the record.  Since a resource may have multiple representations there may be multiple links pointing to each representation of a resource.  Furthermore, representations of a resource may be created and updated at different times.  In order to capture this life cycle information of resource representations, the https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml[link schema] is extended with the addition of two properties named `created` and `updated`.  The values of these properties are used to indicate the creation and last updated dates of the resource representation pointed to by the link.

==== Record encodings

This Standard defines requirements classes for JSON and HTML encoding of a record. See <<clause-catalog-encoding,Encodings>>.

[[clause-record-collection]]
=== Requirements Class "Record Collection" (Common Component)

[[record-collection-overview]]
==== Overview

include::requirements/requirements_class_record-collection.adoc[]

The Record Collection requirements class defines the requirements for a record collection.

A _record collection_ is an object that provides information about and access to a set of related <<clause-core-record,records>>.  Such a collection of records is also referred to as a _catalog_. 

The schema for the catalog is an extension of the collection schema defined in http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API - Features Standard].

While http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API - Features - Part 1: Core] defines a specific location for the collection resource (path: `/collections/{collectionId}`), OGC API - Records only fixes the location of the catalog in the <<clause-records-api,Records API>> conformance class.  Otherwise, the catalog resource can live anywhere the provider wishes to place it including as a static file in web space (e.g. a web-accessible directory or an S3 bucket).

Although this Standard does not mandate any particular encoding for a catalog, two conformance classes are defined:

* a <<clause-catalog-encoding,JSON>> catalog encoding, and
* an <<requirements-class-html-clause,HTML>> encoding.

Other encodings are allowed but are not described in this document.

[[record-collection-schema]]
==== Catalog schema

<<collection-properties-table>> defines the set of properties that may be used to describe a catalog.

[#collection-properties-table,reftext='{table-caption} {counter:table-num}']
.Table of catalog properties
[cols="30,5,65",options="header"]
|===
|Property |Requirement |Description
|id |**required** |A unique identifier for this catalog.
|created |optional |The date this collection was created.
|updated |optional |The more recent date on which this collection was changed.
|conformsTo |optional |The extensions/conformance classes used in this catalog object.
|type |**required** |Fixed value of "Catalog".
|itemType |optional |Fixed value of "record", "catalog" or both.
|title |optional |A human-readable name given to this catalog.
|description |optional |A free-text description of this catalog.
|extent |optional |The spatiotemporal coverage of this catalog.
|crs |optional |A list of coordinate reference systems used for spatiotemporal values.
|keywords |optional |A list of free-form keywords or tags associated with this collection.
|themes |optional |A knowledge organization system used to classify this collection.
|language |optional |The language used for textual values (i.e. titles, descriptions, etc.) of this collection object. 
|languages |optional |The list of other languages in which this collection object is available. 
|recordLanguages |optional |The list of languages in which records from the collection can be represented.
|contacts |optional |A list of contacts qualified by their role(s).
|license |optional |The legal provisions under which this collection is made available.
|rights |optional |A statement that concerns all rights not addressed by the license such as a copyright statement.
|recordsArrayName |optional |The name of the array property in the catalog used to encode records in-line.  The default value is `records`.
|records |optional |An array of records encoded in-line in the catalog.
|[[catalog-links-section]]_**links**_ |**required** |A list of links related to this catalog.
|linkTemplates |optional |A list of link templates related to this catalog.
|===

NOTE: The properties _id_, _itemType_, title_, _description_, _extent_, _crs_ and _links_ are inherited from http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API - Features - Part 1: Core].

include::requirements/record-collection/REQ_mandatory-properties.adoc[]

include::recommendations/record-collection/PER_common-mark.adoc[]

include::recommendations/record-collection/PER_additional-properties.adoc[]

==== Catalog extensions

In <<record-collection-schema>> this Standard defines a set of core properties for describing a catalog.  It is anticipated that this set of properties will be extended to suit specific use cases or requirements.  The `conformsTo` property is a list of identifiers that indicate each extension used in the description of the catalog.  This Standard does not define the specific identifiers that are used to identify specific extensions; it simply provides a place where these identifiers can be listed.  

In the case where all the records of a catalog use the same set of extensions, and to prevent unnecessary duplication, the `conformsTo` property of the catalog can also be used to declare which extensions are used that apply to all records.

See <<sc_record_extensions,Record extensions>>.

==== Item type

A catalog can include references to records, other catalogs or both.

include::requirements/record-collection/REQ_itemType.adoc[]

==== Title and description

In order to facilitate the discovery of resources utilizing keyword or free-text searches, this Standard makes the following recommendation:

include::recommendations/record-collection/REC_title.adoc[]

include::recommendations/record-collection/REC_description.adoc[]

==== Keywords and Themes

include::recommendations/record-collection/REC_keywords-themes.adoc[]

See <<sc_keywords_and_themes,Keywords and Themes>>.

==== Language handling

include::recommendations/record-collection/REC_catalog-lang.adoc[]

include::recommendations/record-collection/REC_record-langs.adoc[]

See <<sc_record_language_handling,Language handling>>.

==== Contacts

include::requirements/record-collection/REQ_contact.adoc[]

==== License

include::requirements/record-collection/REQ_license.adoc[]

[[sc_catalog-record-links]]
==== Records

include::recommendations/record-collection/PER_records.adoc[]

include::requirements/record-collection/REQ_links-record.adoc[]

include::requirements/record-collection/REQ_links-records.adoc[]

include::requirements/record-collection/REQ_records.adoc[]

include::recommendations/record-collection/PER_records-array-name.adoc[]

include::requirements/record-collection/REQ_records-array-name.adoc[]

[[sc_catalog-catalog-links]]
==== Other catalogs

===== Overview

include::recommendations/record-collection/PER_catalogs.adoc[]

Related catalogs may be organized as:

* an unorganized set of related catalogs,
* as a series of related catalogs (e.g. for paging),
* as a hierarchy of related catalogs.

===== Related catalogs

include::requirements/record-collection/REQ_links-catalog-related.adoc[]

===== Series of related catalogs

include::requirements/record-collection/REQ_links-catalog-series.adoc[]

include::recommendations/record-collection/REC_links-catalog-series.adoc[]

===== Hierarchy if related catalog

include::requirements/record-collection/REQ_links-catalog-hierarchy.adoc[]

include::recommendations/record-collection/REC_links-catalog-hierarchy.adoc[]

==== Links

include::requirements/record-collection/REQ_links.adoc[]

include::recommendations/record-collection/PER_links.adoc[]

==== Templated links with variables

See <<sc_templated_links_with_variables,Templated links with variables>>.

==== Encodings

This Standard defines requirements for JSON and HTML encoding of a catalog. See <<clause-catalog-encoding,Encodings>>.

[[clause-record-core-query-parameters]]
=== Requirements Class "Record Core Query Parameters" (Common Component)

[[record-core-query-parameters-overview]]
==== Overview

include::requirements/requirements_class_record-core-query-parameters.adoc[]

The Record Core Query Parameters requirements class defines a minimum core set of query parameters that should be implemented at a searchable catalog endpoint.  The <<core-query-parameters-table,following table>> lists this minimum set of query parameters.

The parameters `bbox`, `datetime`, `limit` and `ids` are inherited from https://docs.opengeospatial.org/is/17-069r4/17-069r4.html[OGC API Features - Part 1: Core].  The remaining parameters are defined in this Standard.

[#core-query-parameters-table,reftext='{table-caption} {counter:table-num}']
.Table of Core Query Parameters
[cols="15,85",options="header"]
|===
|Parameter name |Description
|https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#_parameter_bbox[bbox] |A bounding box. If the spatial extent of the record intersects the specified bounding box, then the record shall be presented in the response document.
|https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#_parameter_datetime[datetime] |A time instance or time period. If the temporal extent of the record intersects the specified date/time value, then the record shall be presented in the response document.
|https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#_parameter_limit[limit] |The number of records to be presented in a response document.
|<<core-query-parameters-q,q>> |A comma-separated list of search terms. If any server-chosen text field in the record contains 1 or more of the terms listed, then this record shall appear in the response set.
|<<core-query-parameters-type,type>> |An equality predicate consisting of a comma-separated list of resource types.  Only records of the listed type shall appear in the response set.
|https://fix.me[ids] |An equality predicate consisting of a comma-separated list of record identifiers. Only records with the specified identifiers shall appear in the response set.
|<<core-query-parameters-externalIds,externalIds>> |An equality predicate consisting of a comma-separated list of external resource identifiers. Only records with the specified external identifiers shall appear in the response set.
|<<additional-query-parameters,_prop_=_value_>> |Equality predicates with any <<additional-query-parameters,queryable>> not already listed in this table.
|===

[[core-query-parameters]]
==== Query parameters

[[core-query-parameters-bbox]]
===== Parameter bbox
include::requirements/record-core-query-parameters/REQ_query-param-bbox.adoc[]

[[core-query-parameters-datetime]]
===== Parameter datetime
include::requirements/record-core-query-parameters/REQ_query-param-datetime.adoc[]

[[core-query-parameters-limit]]
===== Parameter limit
include::requirements/record-core-query-parameters/REQ_query-param-limit.adoc[]

[[core-query-parameters-q]]
===== Parameter q

The `q` parameter provides a simple, easy-to-implement keyword search capability across one or more text fields in a record.  

include::requirements/record-core-query-parameters/REQ_query-param-q-definition.adoc[]

The specific text fields in a record that are to be searched is not mandated in this Standard.

include::recommendations/record-core-query-parameters/REC_param-q.adoc[]

include::requirements/record-core-query-parameters/REQ_query-param-q-response.adoc[]

For example, the following `q` parameter specification:

----
q=ocean,climate%20%09change,desalination
----

represents the query predicate:

----
(anytext CONTAINS 'ocean') OR
(anytext CONTAINS 'climate\s+change') OR
(anytext CONTAINS 'desalination')`
----

NOTES:

* The term `anytext` represents the set of text fields that are searched by the operation.
* The `CONTAINS` operator used above is just an example of an operator that searches a text field(s) for specific search terms.  How this operator is implemented and what it is named in the system backing a catalog implementation is beyond the scope of this Standard.
* The regular expression `\s+` represents one or more white spaces.

[[core-query-parameters-type]]
===== Parameter type

include::requirements/record-core-query-parameters/REQ_query-param-type-definition.adoc[]

include::recommendations/record-core-query-parameters/REC_query-param-type-definition.adoc[]

include::requirements/record-core-query-parameters/REQ_query-param-type-response.adoc[]

[[core-query-parameters-ids]]
===== Parameter ids

include::requirements/record-core-query-parameters/REQ_query-param-ids-definition.adoc[]

include::requirements/record-core-query-parameters/REQ_query-param-ids-response.adoc[]

[[core-query-parameters-externalIds]]
===== Parameter externalIds

include::requirements/record-core-query-parameters/REQ_query-param-externalIds-definition.adoc[]

include::requirements/record-core-query-parameters/REQ_query-param-externalIds-response.adoc[]

[[additional-query-parameters]]
===== Additional query parameters

This Standard defines the following URL query parameters based on the set of
<<core-properties-record-table,core properties>> to support record selection
based on the resource type and/or an external identifier associated with the
resource.

* <<core-query-parameters-type,type>>
* <<core-query-parameters-externalIds,externalIds>>

include::recommendations/record-core-query-parameters/REC_additional-query-parameters.adoc[]

[[clause-records-api]]
=== Requirements Class "Records API" (Common Component)

[[records-api-overview]]
==== Overview

include::requirements/requirements_class_records-api.adoc[]

The core requirements for an API that enables searching a catalog are defined by the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] Standard.

include::requirements/records-api/REQ_resource-name-mapping.adoc[]

==== Declarations of conformance class

include::requirements/records-api/REQ_conformance-classes.adoc[]

include::recommendations/records-api/PER_conformance-classes.adoc[]

==== Encodings

While the OGC API - Records - Part 1: Core Standard does not specify any mandatory encoding, support for the following encodings is recommended.

include::recommendations/records-api/REC_html.adoc[]

include::recommendations/records-api/REC_json.adoc[]

The encoding of a server response is determined according to the mechanisms defined in https://www.rfc-editor.org/rfc/rfc2616#section-12[Clause 12] of the https://www.rfc-editor.org/rfc/rfc2616[HTTP 1.1] Standard.

The <<media-types-section,Media Types>> sub-clause includes guidance on media types for encodings that are specified in this document.

Note that any server that supports multiple encodings will have to support a mechanism to mint encoding specific URIs for resources to express links, for example, to alternate representations of the same resource. This document does not mandate any particular approach as to how this is supported by the server.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism as to how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") URIs in the browser address bar, can study the API definition document (e.g. the OpenAPI definition).

[NOTE]
======================================================================
Two common approaches are:

* An additional path for each encoding of each resource (this can be expressed,
for example, using format specific suffixes like ".html");

* An additional query parameter (for example, "accept" or "f") that overrides
the Accept header of the HTTP request.
======================================================================

[[record-collection]]
==== Record collection response

include::requirements/records-api/REQ_record-collection-response.adoc[]

[[record-collections]]
==== Record collections response

include::requirements/records-api/REQ_record-collections-response.adoc[]

[[records-access]]
==== Records access

===== Operation

include::requirements/records-api/REQ_records-op.adoc[]

===== Combinations of Filtering Parameters

Any combination of query parameters from the <<core-query-parameters-table,Table of Query Parameters>> and any <<additional-query-parameters,additional query parameters>> may be specified for filtering. Note that the requirements on these parameters imply that only records matching all the predicates are in the result set, i.e., the logical operator between the predicates is **AND** (exclusive).

[[query-response]]
===== Response

<<response-encodings>> lists specific requirements based on the negotiated representation of the response.

[#response-encodings,reftext='{table-caption} {counter:table-num}']
.Negotiated representation of response 
[width=40%,cols="30%,70%",options="header"]
|===
|Representation |Requirements
|JSON/GeoJSON |<<clause-record-encoding-json,Requirements Class JSON>>
|HTML |<<requirements-class-html-clause,Requirements Class HTML>>
|===

===== Examples

The following is an example of a response to an OGC API - Records query operation (path: `/collections/{collectionId}/items`).  This example shows a JSON response and the response container is a GeoJSON feature collection.  Specific records are not presented in this example to illustrate the structure of the response container in GeoJSON.

[#records-example,reftext=`Records Example`]
.Records Example in GeoJSON
[source,json]
----
include::../examples/json/record-collection.json[]
----

The following is an example of a single catalog record encoded in GeoJSON.
Such a record might appear in the `features` array of a
<<records-example,query response>> or it may be the response when a specific,
single record is accessed (path: `/collections/{collectionId}/items/{recordId}`).

[#record-example,reftext=`Record Example`]
.Record Example in GeoJSON
[source,json]
----
include::../examples/json/record.json[]
----

[[record-access]]
==== Record access

===== Operation

include::requirements/records-api/REQ_record-op.adoc[]

===== Response

include::requirements/records-api/REQ_record-response.adoc[]

[[clause-sorting]]
=== Requirements Class "Sorting" (Common Component)

[[sorting-overview]]
==== Overview

include::requirements/requirements_class_sorting.adoc[]

The `Sorting` Requirements Class defines the requirements for specifying how records in a response should be ordered for presentation.

[[sorting-parameter-sortby]]
==== Parameter sortby

include::requirements/sorting/REQ_sortby-definition.adoc[]

[NOTE]
======================================================================
The core definition of the `sortby` parameter only defines a single directive that controls the sort order of the corresponding property.  It is anticipated extensions would add additional search facets such as directives for:

. Handling missing values,
. Specifying a high value indicating that the corresponding property be sorted as if it were the highest possible value,
. Specifying a low value indicating that the corresponding property be sorted as if it were the lowest possible value,
. Allowing records to be omitted from the result set based on their sort order,
. Specify a fixed value and a fixed value that sorts the corresponding property as if it were the specified fixed value.
======================================================================

include::requirements/sorting/REQ_sortby-response.adoc[]

include::requirements/sorting/REQ_get-sortables-op.adoc[]

include::requirements/sorting/REQ_get-sortables-success.adoc[]

include::recommendations/sorting/PER_synthetic.adoc[]

The response is returned as a JSON Schema document that describes a single JSON object where each property is a sortable. Note that the sortables schema does not specify a schema of any object that can be retrieved from a Records API endpoint. JSON Schema is used for the sortables to have a consistent approach for describing schema information and JSON Schema is/will be used in other parts of OGC API - Features suite of standards to describe schemas for GeoJSON feature content including in OpenAPI documents.

NOTE: The OGC Features API Standards Working Group has a schema harmonization task that could lead to a future OGC API Standard that will deprecate the approach for the sortables resource specified in this document.

To support clients, providing additional detail about the meaning of the sortables is recommended:

include::recommendations/sorting/REC_sortables-schema.adoc[]

In an OpenAPI 3.0 document, the Sortables resource has the following schema:

[[schema_sortables]]
.link:https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/responses/Sortables.yaml[Schema for the list of sortable properties (Sortables.yaml)]
[source,YAML]
----
include::../openapi/responses/Sortables.yaml[]
----

==== Declaring default sort order

This Specification does not mandate a specific default sort order for records
fetched from a searchable catalog.  However, servers can declare a default
sort order.

include::requirements/sorting/REQ_defaultSortOrder-definition.adoc[]

==== Sorting by relevance (informative)

A common practice is to sort search results by relevance.

This capability is accomodated in this Standard by using <<per_sorting_sortables-synthetic,synthetic>> sortables.  That is, sortables that are derived or synthesized by the server.

A sever implementing relevance sorting might include, in the list of sortables, a sortable named `relevance` that is dynamically computed for each result in a result set.  The value of the synthetic `relevance` sortable could, for example, be between 0 and 10 with zero indicating least relevance and 10 indicating most relevance.  A `sortBy` clause specified on a request specifying a descending sort be the `relevance` property would present search results from most to least relevant.

==== Examples

[#defaultSortOrder-example,reftext=`Default Sort Order Example`]
.Default Sort Order Example
[source,json]
----
include::../examples/json/defaultSortOrder.json[]
----

The following examples assume the following set of sortables retrieved from the servers `/collection/{catalogId}/sortables` endpoint:

[#sortables-example,reftext=`Sortables Example`]
.List of sortables
[source,json]
----
include::../examples/json/sortables.json[]
----

[#sortby-example,reftext=`SortBy Example`]
.sortby Example of descending sort by updated date and ascending sort of record identifier.
[source]
----
.../collections/mycat/items?...&sortby=%2Dupdated,%2Bid&...
----

[#sortby-extent-example,reftext=`SortBy Extent Example`]
.sortby Example of an ascending sort by extent (i.e. smallest area first)
[source]
----
.../collections/mycat/items?...&sortby=%2Bextent&...
----

[#sortby-relevance-example,reftext=`SortBy Relevance Example`]
.sortby Example of a descending sort by relevance (i.e. most relevant first)
[source]
----
.../collections/mycat/items?...&sortby=%2Drelevance&...
----

[[clause-filtering]]
=== Requirements Class "Filtering" (Common Component)

[[record-filter-overview]]
==== Overview

include::requirements/requirements_class_record-filter.adoc[]

This clause defines the binding to the filtering parameters defined in the https://docs.ogc.org/DRAFTS/19-079r1.html#_requirements_class_filter[OGC API - Features - Part 3: Filtering] and the use of the https://docs.ogc.org/DRAFTS/21-065.html[Common Query Language (CQL2)] as the query language.

==== Records filtering

===== Operation

As specified in the <<records-access,Records Access>> clause, records are accessed using the HTTP GET method via the `/collections/{collectionId}/items` path.  The following additional requirements bind the parameters https://docs.ogc.org/DRAFTS/19-079.html#filter-param[filter], https://docs.ogc.org/DRAFTS/19-079.html#filter-lang-param[filter-lang] and https://docs.ogc.org/DRAFTS/19-079.html#filter-filter-crs[filter-crs] to the GET operation on this path.

include::requirements/record-filter/REQ_filter-param.adoc[]

include::requirements/record-filter/REQ_filter-lang-param.adoc[]

include::recommendations/record-filter/REC_text-encoding.adoc[]

include::recommendations/record-filter/REC_json-encoding.adoc[]

include::requirements/record-filter/REQ_filter-crs-param.adoc[]

===== Response

include::requirements/record-filter/REQ_response.adoc[]

==== Filtering on links

===== Overview

Links can be added to a catalog record in various ways.  This clause 
describes the various linking patterns and describes how to use CQL to
filter based on links.

===== Linking patterns in records

Links can be added to the following sections in a catalog record:

. the <<query-response,links>> section,
. the <<query-response,linkTemplates>> section,
. the <<query-response,properties>> section.

The schema for links added to the <<query-response,links>> and <<query-response,linkTemplates>> sections is based on https://tools.ietf.org/html/rfc8288[RFC 8288] and is described in the https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml[OGC API - Features - Part 1: Core] Standard.

Links added directly to the <<query-response,properties>> section of a catalog record can be added using the following patterns:

. The link relation is the key for an array of links with a schema similar to that used in the <<query-response,links>> section but omitting the `rel` key.
. The link relation is the key for an array of `href` values.
. The link relation is the key for an an `href` value.

The following examples illustrate each of these linking patterns:

[#linking-pattern-1,reftext=`Adding links to the **links** section.`]
.Adding links to the **links** section
----
{
   ...,
   "properties": {
      ...,
      "links":
      [
         ...,
         {
            "rel" : "alternate",
            "title" : "This records as XML.",
            "href" : "https://example.org/collections/mycat/items/rec01.xml"
         },
         {
            "rel": "next",
            "title": "The next record in this result set.",
            "href" : "https://example.org/collections/mycat/items/rec02"
         },
         ...
      ],
      ...
   }
}
----

[#linking-pattern-2,reftext=`Adding links to the **properties** section.`]
.Adding links to the **properties** section
----
{
  ...,
  "properties": {
    ...,
    "related": [
      {
        "title" : "A related record",
        "href" : "https://example.org/related-record-path/rec15"
      }
    ],
    "license": {
      "title" : "CC BY 2.0",
      "href" : "https://creativecommons.org/licenses/by/2.0/"
    },
    "enclosure": {
      "title": "GeoPackage of Feature Data",
￼      "href" : "https:/example.org/collections/MyCollection/items?f=application/geopackage+vnd.sqlite3&bbox={bbox}",
 ￼     "varBase": "https://example.org/variables/
    },
    ...
  }
}
----

[#linking-pattern-3,reftext=`Adding links to the **properties** section.`]
.Adding links to the **properties** section
----
{
   ...,
   "properties": {
      ...,
      "related": ["https://example.org/related-record-path/rec15"],
      "license": "https://creativecommons.org/licenses/by/2.0/",
      ...
   }
}
----

===== Examples

====== CQL filters on links

The following example illustrates how to filter links that may appear in a catalog record.

[#filter-pattern-1,reftext=`Filtering links in the **links** section.`]
.Filtering links in the **links** section
----
links[rel='license'].title LIKE 'CC%'
----

[#filter-pattern-2,reftext=`Filtering links in the **properties** section.`]
.Filtering links in the **properties** section
----
properties.related[*].href LIKE '%/rec15' AND properties.license.title LIKE 'CC%'
----

[#filter-pattern-3,reftext=`Filtering links in the **properties** section.`]
.Filtering links in the **properties** section
----
properties.related LIKE '%/rec15' AND properties.license LIKE 'https://creativecommons.org/licenses/%'
----

====== Filtering by keyword from a controlled vocabulary

The following example illustrates how to use https://docs.ogc.org/DRAFTS/19-079r1.html[OGC API - Feature - Part 3: Filtering] and https://docs.ogc.org/DRAFTS/21-065.html[CQL2] to query by keywords from a specific controlled vocabulary.

The use of keywords from a controlled vocabulary is encoded in a record using the <<sc_keywords_and_themes,`themes`>> property.  Consider a record that has the following `themes` property:

----
   "themes": [
     {
       "concepts": [
         "dobson",
         "brewer",
         "vassey",
         "pion",
         "microtops",
         "spectral",
         "hoelper",
         "saoz",
         "filter"
       ],
       "scheme": "https://geo.woudc.org/codelists.xml#WOUDC_InstrumentCode"
     },
     {
       "concepts": [
         "atmosphericComposition",
         "pollution",
         "observationPlatform",
         "rocketSounding"
       ],
       "scheme": "https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode"
     }
   ],
----

Using an implementation of the https://docs.ogc.org/DRAFTS/19-079r1.html[OGC API - Feature - Part 3: Filtering] Standard, a server would need to expose two https://docs.ogc.org/DRAFTS/19-079r1.html#queryables[queryables], `scheme` and `concept` for the purpose of filtering using keywords from a specific controlled vocabulary.  Using these queryables, the following filter could be expressed:

----
https://example.org/collections/myCatalog/items?filter-lang=cql2-text&filter=scheme%3D%27https%3A%2F%2Fgeo.woudc.org%2Fcodelists.xml%23WOUDC_InstrumentCode%27%20and%20concept%3D%27spectral%27%2C%0Ahoelper%27
----

An alternative approach that does rely on using https://docs.ogc.org/DRAFTS/19-079r1.html[OGC API - Feature - Part 3: Filtering] and https://docs.ogc.org/DRAFTS/21-065.html[CQL2] would rely on the server defining a set of https://docs.ogc.org/is/17-069r4/17-069r4.html#_parameters_for_filtering_on_feature_properties[query parameters] in the server's https://docs.ogc.org/is/17-069r4/17-069r4.html#_api_definition[API description document], again named `scheme` and `concept`, that would allow the following filter to be expressed:

----
https://example.org/collections/myCatalog/items?scheme=https%3A%2F%2Fgeo.woudc.org%2Fcodelists.xml%23WOUDC_InstrumentCode&concept=spectral,hoelper
----

[[clause-autodiscovery]]
=== Requirements Class "Autodiscovery" (Common Component)

==== Overview

include::requirements/requirements_class_autodiscovery.adoc[]

The purpose of autodiscovery is, knowing the location of a web page, to find the addresses(s) of that page's associated catalog(s).  For example, a client could retrieve the landing page of an OGC API deployment, find the location of the site's searchable catalog by locating the `rel="http://www.opengis.net/def/rel/ogc/1.0/ogc-catalog"` link in the landing page and then, using that catalog, search for resources offered by the site.

==== Autodiscovery links

include::requirements/autodiscovery/REQ_autodiscovery.adoc[]

[[clause-encodings]]
=== Encodings

[[requirements-class-json-clause]]
==== Requirements Class JSON (Common Component)

===== Overview

include::requirements/requirements_class_json.adoc[]

[[clause-record-encoding-json]]
===== Record encoding

https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON] is a commonly used format based on JSON that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format, supporting GeoJSON is recommended. The caveat is, if record data can be represented in GeoJSON for the intended use.

The following requirements apply when:

. The Records API endpoint advertises conformance to the JSON Conformance Class.
. The client negotiates that the content of the server's response be https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON].

include::requirements/json/REQ_record-response.adoc[]

include::requirements/json/REQ_record-content.adoc[]

[[schema_json_record]]
.link:https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml[Schema for a catalog record encoded as GeoJSON (recordGeoJSON.yaml)]
[source,YAML]
----
include::../openapi/schemas/recordGeoJSON.yaml[]
----

.link:https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordCommonProperties.yaml[Common record properties schema (recordCommonProperties.yaml)]
[source,YAML]
----
include::../openapi/schemas/recordCommonProperties.yaml[]
----

[NOTE]
======================================================================
Referenced schemas can be found at:

* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/time.yaml[time.yaml],
* https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/geometryGeoJSON.yaml[geometryGeoJSON.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/language.yaml[language.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/theme.yaml[theme.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/contact.yaml[contact.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/license.yaml[license.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/common/linkBase.yaml[linkBase.yaml].
======================================================================

include::recommendations/json/PER_time.adoc[]

[NOTE]
=================================================
This standard does not define a normative schema for a record encoding that is not GeoJSON.  However, this https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordJSON.yaml[informative schema] is offered as an example of what a such record schema might look like.
=================================================

[[clause-catalog-encoding]]
===== Catalog encoding

https://datatracker.ietf.org/doc/html/rfc8259[JSON] is an open standard file format and data interchange format that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and arrays (or other serializable values).  JSON is a commonly used data encoding with diverse uses in electronic data interchange, including that of web applications with servers.  Therefore, the recommendation is to use the JSON encoding if the catalog (i.e. a collection of record) data can be represented in JSON for the intended use.

The following requirements apply when:

. The Records API endpoint advertises conformance to the JSON Conformance Class
. The client negotiates that the content of the server's response be JSON.

include::requirements/json/REQ_collection-response.adoc[]

include::requirements/json/REQ_collection-content.adoc[]

[[schema_json_collection]]
.link:https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/catalog.yaml[Schema for a catalog encoded as JSON(catalog.yaml)]
[source,YAML]
----
include::../openapi/schemas/catalog.yaml[]
----

[NOTE]
======================================================================
Referenced schemas can be found at:

* https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml[collection.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/language.yaml[language.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/theme.yaml[theme.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/contact.yaml[contact.yaml],
* https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/license.yaml[license.yaml].
======================================================================

[[requirements-class-html-clause]]
==== Requirements Class HTML (Common Component)

include::requirements/requirements_class_html.adoc[]

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the HTML Conformance Class
. The client negotiates that the content of the server's response be encoded as HTML.

Catalog information that is only accessible in formats primarily intended to
be read by machines, such as JSON or XML, have two issues:

* The data is not discoverable using the most common mechanism for discovering information, the Web search engines.

* The data cannot be viewed directly in a browser (additional tools are required to view the data).

Therefore, sharing catalog data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines] <<SDWBP>>. The Records API Standard therefore <<rec_html,recommends supporting HTML as an encoding>>.

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

[[clause-oas30]] 
=== Requirements Class "OpenAPI 3.0" (Common Component)

==== Basic requirements

Servers conforming to this requirements class define their API using an 
http://spec.openapis.org/oas/v3.0.3#openapi-document[OpenAPI Document].

include::requirements/oas30/REQ_oas30.adoc[]

include::requirements/oas30/REQ_oas-conformance.adoc[]
