[[media-types-section]]
== Media Types

=== Overview

The OGC API - Records Standard does not mandate any particular encoding for a <<clause-record-core,record>> or a <<clause-record-collection,catalog>>.  However, it does provide requirements classes for encodings that are commonly used in implementations of OGC API Standards. These encodings include <<requirements-class-json-clause,JSON>> and <<requirements-class-html-clause,HTML>>.  This clause indicates the media that to be used for these encodings of the resources defined in this Standard.

=== Media types
A description of the MIME types is mandatory for any OGC API Standard that specifies requirements for data encoding(s). <<media-types-table>> provides a list of suitable MIME types for <<clause-record-core,records>> and <<clause-record-collection,catalogs>>.

[#media-types-table,reftext='{table-caption} {counter:table-num}']
.API - Records MIME Types
[width="80%",cols="20,20,60",options="header"]
|====
2+^|*Encoding*               ^|*MIME Type*
.2+|<<clause-record-core,Record>>  |HTML     |`text/html`
|GeoJSON  |`application/geo+json; application=ogc-record`
.2+|<<clause-record-collection,Catalog>> |HTML    |`text/html`
|JSON     |`application/ogc-catalog+json`
|====

[[media-type-defaults]]
=== Default Encodings

The canonical method of selecting a desired response encoding is to use https://datatracker.ietf.org/doc/html/rfc7231#section-3.4[HTTP content negotiation].  However, content negotiation is not required by the HTTP standard.  Therefore, default encodings must be established.

include::requirements/building-blocks/record-core/REQ_default-mediatype.adoc[]

include::requirements/building-blocks/record-collection/REQ_default-mediatype.adoc[]
