[[clause_local-resources-catalogue]]
== Requirements Class "Local Resources Catalogue"

[[local-resources-catalogue-overview]]
=== Overview

include::requirements/requirements_class_local-resources-catalogue.adoc[]

This conformance class specifies requirements for local resource catalogues.

The OGC API defines a number of resource endpoints that provide lists of
sub-resources.  These endpoints are refered to "local resource catalogues" in this specification because they provide metadata about resources offered locally by an OGC API deployment.

The `/collections` endpoint is an example of a local resources catalogue.  It
provides a list of offered collections of resources.  Each offered collections (i.e. `/collections/{collectionId}`) is described by a small number of properties defined in https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] and typically extended by the resource-specification specification (e.g. OGC API - Feature - Part 1: Core).

Other local resources catalogues include the `/processes` endpoint which provides a list of offered processes and the `/collections/{collectionId}/scenes` endpoint which provides a list of source images.

The conformance class defines requirements that :

1. Define or extend the set of query parameters defined at the local resource catalogue endpoint. In the case of the `/collections` endpoint, for example, the requirements in this conformance class extend the set of queryables, `bbox`, `datetime` and `limit`, to include a parameters such as a text search parameter `q`.

2. Extend the schema of the local resource catalogue endpoint to add additional keys/properties that provide richer descriptive information.  In the case of the
`/collections` endpoint, for example, these additional properties enhance the information content defined in the https://docs.ogc.org/DRAFTS/20-024.html#collection-description[Collection Description] clause of the https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] extension

=== Collections Metadata

WARNING: T.B.D.  The rest of this clause was originally a description of extending the `/collections` endpoint but is not being expanded to be any endpoint where it makes sense to add catalogue-like query capability.

The https://docs.ogc.org/DRAFTS/20-024.html#collections-metadata[Collections Metadata] clause of the https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] extension defines the `bbox`, `datetime` and 'limit' query parameters for the `/collections` resource. 

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_query-params.adoc[]

The collections metadata (i.e. HTTP GET on the `/collections` path) is defined in the https://docs.ogc.org/DRAFTS/20-024.html#_response[Collections Metadata] clause of the https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] extension.  

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_query-response.adoc[]

=== Collection Description

The collection information object is defined in the https://docs.ogc.org/DRAFTS/20-024.html#collection-description[Collection Description] clause of the https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] extension.

The following table cross-walks the properties of the collection information
object with the core queryables.

[[record-collection-crosswalk]]
[reftext='{table-caption} {counter:table-num}']
.Crosswalk of core queryables with collection information object properties
[cols="25,25,25,25",options="header"]
|===
|Collection property |Requirement |Core Queryable |Requirement
|id                  |M           |id             |M
|title               |O           |title          |M
|description         |O           |description    |M
|itemType            |O           |--             |--
|extent              |O           |extent         |O
|links               |M           |links          |O
|crs                 |O           |--             |--
|===

The following requirements specify additional properties that a compliant
implementation of this conformance class must add to the collection 
information object.

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_title.adoc[]

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_description.adoc[]

No additional requirements are necessary for the `extent` property.

No additional requirements are necessary to the `links` property.  Since the
`links` property is mandatory for the collection information object, it will
always be present but because it is an optional core queryables, catalogue
clients will either know how to handle it or they will ignore it.

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_type.adoc[]

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_created.adoc[]

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_updated.adoc[]

NOTE: Adding, modifying, or deleting items from a collections are all examples of changes to that collection.

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_keywords.adoc[]

include::recommendations/local-resources-catalogue/REC_local-resources-catalogue_additional-properties.adoc[]

The collections metadata response is defined in the https://docs.ogc.org/DRAFTS/20-024.html#collection-metadata[Collections Metadata] clause on the https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] extension.

include::requirements/local-resources-catalogue/REQ_local-resources-catalogue_schema.adoc[]

=== Examples

Example 1: List all the collections that lie within a specific bounding box and contains the the keyword `weather`.

---
   Client                                                          Server
     |                                                               |
     |   GET /collections?bbox=￼41.875315,-96.767601,56.732861,-73.47|
     |                          6586&q=weather   HTTP/1.1            |
     |   Accept: application/json                                    |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 200 OK                                             | 
     |   Content-Type: application/json                              |
     |                                                               |
     |   Need example output here...                                 |
     |<--------------------------------------------------------------|
---

