[[conformance_class]]
== Conformance

Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance, are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The one Standardization Target for this standard is Web APIs.

OGC API - Common provides a common foundation for OGC API standards. Therefore, this standard should be viewed as an extension to API - Common. Conformance to this standard requires demonstrated conformance to the applicable Conformance Classes of API - Common. 

This standard identifies seven (7) Conformance Classes. The Conformance Classes implemented by an API are advertised through the <<conformance-classes,`/conformance`>> path on the <<landing-page,landing page>>. Each Conformance Class has an associated Requirements Class. The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.

The Requirements Classes for OGC API - Records are:

* <<clause-core,Core>>
* <<clause-sorting,Sorting>>
* <<clause-cql-filter,Filtering using the Common Query Language (CQL)>>
* <<clause-opensearch,OpenSearch>>
* <<requirements-class-json-clause,JSON-Record>>
* <<requirements-class-atom-clause,ATOM-Record>>
* <<requirements-class-html-clause,HTML-Record>>

The <<clause-core,_Core_ Requirements Class>> is the minimal useful service interface for the OGC Records API. The requirements specified in this Requirements Class are mandatory for all implementations of API - Records.  The core is composed of two components:

* an API based on http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Feature - Part 1: Core] with <<records-access,extensions>> specific to OGC API Records,

* a core set of properties (<<core-queryables,core queryables>>) that every catalog records must contain.  This core set of properties can be extended by communities of interest or to suite specific needs.

The <<clause-sorting,_Sorting_ Requirements Class>> defines the requirements to support sorting of records in a query response.

The <<clause-record-filter,_Filter using the Common Query Language_ Requirements Class>> defines the requirements to support record filtering using https://docs.ogc.org/DRAFTS/19-079r1.html[CQL].

The <<clause-opensearch,_OpenSearch_ Requirements Class>> defines the requirements to support query by OpenSearch clients.

The <<requirements-class-json-clause,_JSON-Record_ Requirements Class>> defines the requirements for a GeoJSON (see RFC 7946) representation of a standard catalogue record.

The <<requirements-class-atom-clause,_ATOM-Record_ Requirements Class>> defines the requirements for an ATOM representation of a standard catalogue record.

The <<requirements-class-html-clause,_HTML-Record_ Requirements Class>> defines the requirements for an HTML representation of a standard catalogue record.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<ats_core,Core>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/core
|<<ats_sorting,Sorting>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/sorting
|<<ats_cql,CQL>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/cql
|<<ats_opensearch,OpenSearch>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/opensearch
|<<ats_json,JSON-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/JSON
|<<ats_atom,ATOM-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/atom
|<<ats_atom,HTML-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/html
|===

include::requirements/core/REQ_conformance.adoc[]

include::recommendations/core/PER_additional-conformance.adoc[]
