[[clause-encodings]]
== Encodings

[[requirements-class-geojson-clause]]
=== Requirements Class GeoJSON

include::requirements/requirements_class_geojson.adoc[]

GeoJSON is a commonly used format that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format supporting GeoJSON is recommended, if record data can be represented in GeoJSON for the intended use.

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the JSON Conformance Class
. The client negotiates to a record response encoded as GeoJSON.

include::requirements/geojson/REQ_response.adoc[]

include::requirements/geojson/REQ_content.adoc[]

[[schema_geojson_record]]
.link:http://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordGeoJSON.yaml[Schema for a catalogue record in JSON(recordGeoJSON.yaml)]
[source,YAML]
----
include::../openapi/schemas/recordGeoJSON.yaml[]
----

[[requirements-class-jsonfg-clause]]
=== Requirements Class OGC Features and Geometries JSON (JSON-FG)

include::requirements/requirements_class_jsonfg.adoc[]

The OGC Features and Geometries JSON (JSON-FG) Standard extends GeoJSON to support a limited set of additional capabilities that are out-of-scope for GeoJSON, but that are important for a variety of use cases involving record data.

The JSON-FG Standard specifies the following minimal extensions to the GeoJSON Standard:

* The ability to use Coordinate Reference Systems (CRSs) other than WGS 84;
* Allow the use of non-Euclidean metrics, in particular ellipsoidal metrics;
* Solids and multi-solids as geometry types;
* The ability to encode temporal characteristics of a feature; and
* The ability to declare the type and the schema of a feature.

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the JSON Conformance Class
. The client negotiates to a record response encoded as GeoJSON.

include::requirements/jsonfg/REQ_response.adoc[]

include::requirements/jsonfg/REQ_content.adoc[]

[[schema_jsonfg_record]]
.link:http://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordGeoJSON.yaml[Schema for a catalogue record in JSON(recordGeoJSON.yaml)]
[source,YAML]
----
include::../openapi/schemas/recordGeoJSON.yaml[]
----

[[requirements-class-html-clause]]
=== Requirements Class HTML

include::requirements/requirements_class_html.adoc[]

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the HTML Conformance Class
. The client negotiates an HTML format

Catalogue information that is only accessible in formats primarily intended to
be read by machine, such as JSON or XML, have two issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web;

* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines] <<SDWBP>>. This standard therefore <<rec_html,recommends supporting HTML as an encoding>>.

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

