[[clause-sorting]]
== Requirements Class "Sorting"

[[sorting-overview]]
=== Overview

include::requirements/requirements_class_sorting.adoc[]

The `Sorting` Requirements Class defines the requirements for specifying how records in a response should be ordered for presentation.

[[sorting-parameter-sortby]]
=== Parameter sortby

include::requirements/sorting/REQ_sortby-definition.adoc[]

NOTE: The core definition of the `sortby` parameter only defines a single directive that controls the sort order of the corresponding property.  It is anticipated extensions would add additional search facets such as directives for:
handling missing values; specifying a high value indicating that the corresponding property be sorted as if it were the highest possible value; specifying a low value indicating that the corresponding property be sorted as if it were the lowest possible value; allowing records to be omitted from the result set based on their sort order; specify a fixed value and a fixed value that sorts the corresponding property as if it were the specified fixed value.

include::requirements/sorting/REQ_sortby-response.adoc[]

include::requirements/sorting/REQ_get-sortables-op.adoc[]

include::requirements/sorting/REQ_get-sortables-success.adoc[]

The response is returned as a JSON Schema document that describes a single JSON object where each property is a sortable. Note that the sortables schema does not specify a schema of any object that can be retrieved from the API. JSON Schema is used for the sortables to have a consistent approach for describing schema information and JSON Schema is/will be used in other parts of OGC API Features to describe schemas for GeoJSON feature content including in OpenAPI documents.

NOTE: The OGC Features API Standards Working Group has a schema harmonization task that could lead to a future OGC API standard that will deprecate the approach for the sortables resource specified in this document.

To support clients, providing additional detail about the meaning of the sortables is recommended:

include::recommendations/sorting/REC_sortables-schema.adoc[]

In an OpenAPI 3.0 document, the Sortables resource has the following schema:

[[schema_sortables]]
.link:http://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/responses/Sortables.yaml[Schema for the list of sortable properties (Sortables.yaml)]
[source,YAML]
----
include::../openapi/responses/Sortables.yaml[]
----

=== Declaring default sort order

This specification does not mandate a specific default sort order for records
fetched from a searchable catalogue.  However, servers can declare a default
sort order.

include::requirements/sorting/REQ_defaultSortOrder-definition.adoc[]

=== Examples

[#defaultSortOrder-example,reftext=`Default Sort Order Example`]
.Default Sort Order Example
[source,json]
----
include::../examples/json/defaultSortOrder.json[]
----

This examples indicates that by default, response records are sorted by the `updated` sortable and the `area` sortable with the most recent record with the largest area being presented first.

[#sortables-example,reftext=`Sortables Example`]
.Sortables Example
[source,json]
----
include::../examples/json/sortables.json[]
----

[#sortby-example,reftext=`SortBy Example`]
.sortby Example of descending sort by updated date and ascending sort of record identifier.
[source]
----
.../collections/mycat/items?...&sortby=-updated,id&...
----

[#sortby-extent-example,reftext=`SortBy Extent Example`]
.sortby Example of an ascending sort by extent (i.e. smaller area first)
[source]
----
.../collections/mycat/items?...&sortby=%2Bextent&...
----


