[[clause-core-record-collection]]
== Requirements Class "Record Collection"

[[core-record-collection-overview]]
=== Overview

include::requirements/requirements_class_record-collection.adoc[]

The `Core Record Collection` Requirements Class defines the requirements for a collection object or catalogue that provices information about and access to a related set of <<clause-core-record,records>>.  

[[record-collection]]
=== Record collection (catalogue)

==== Overview

The schema for a collection presented in this clause is an extension of the collection schema defined in OGC API Common and OGC API Records.

While OGC API Common and OGC API Records defines a specific relative path for the collection object (i.e. `/collections/{collectionId}`), OGC API Records only fixes the location of the collection in the <<clause-record-api,Record API>> conformance class.  Otherwise the collection object can live anywhere the provider wished to place it.

[[record-collection-schema]]
==== Schema of a record collection

<<collection-properties-table>> defines the set of properties that may be used to describe a collection.

[#collection-properties-table,reftext='{table-caption} {counter:table-num}']
.Table of collection properties
[cols="30,5,65",options="header"]
|===
|Queryables |Requirement |Description
|_**id**_ |M |A unique identifier to the collection.
|_**title**_ |M |A human-readable name given to the collection.
|_**description**_ |O |A free-text description of the collection.
|_**links**_ |M |A list of links for navigating the API (e.g. link to previous or next pages; links to alternative representations, etc.)
|_**extent**_ |O |The spatio-temporal coverage of the collection.
|_**itemType**_ |M |Fixed to the value "record".
|_**crs**_ |O |A list of coordinate reference system used for spatial-temporal values.
|type |M |The nature or genre of the resource. Fixed to "Collection".
|keywords |O |A list of keywords or tag associated with the collection.
|keywordsCodespace |O |A reference to a controlled vocabulary used for the keywords property.
|language |O |This refers to the natural language used for textual values (i.e. titles, descriptions, etc) of a collection.
|created |O |The date the collection was created.
|updated |O |The more recent date on which the collection was changed.
|publisher |O |The entity making the collection available.
|themes |O |A knowledge orgnaization system used to classify the collection.
|contactPoint |O |An entity to contact about the collection.
|license |O |A legal document under which the collection is made available.
|rights |O |A statement that concerns all rights not addressed by the license such as a copyright statement.
|===

NOTE: The properties _id_, _title_, _description_, _links_, _extent_, _itemsType_ and _crs_ were inherited from OGC API - Common and OGC API Features.

include::requirements/core/REQ_mandatory-queryables-collection.adoc[]

include::recommendations/core/PER_additional-queryables-collection.adoc[]

==== Keywords and Themes

See <<sc_keywords_and_themes,Keywords and Themes>> for a record.

==== Links

T.B.D.

* The collection object can include one or more  `rel=item` links to explicitly point to the records of the collection.
* If there is a search API available for the collection, then a `rel=items` ... shouldn't this be `search`?
* These links can be typed to allow for the possibility of alternate representatin of each record.

==== Templated links with variables

See <<sc_templated_links_with_variables,Templated links with varables>> for a record.

==== Language negotiation

See <<sc_language_negotiation,Language negotiation>> for a record.

[[static-record-deployment]]
=== Static record deployment

T.B.D.

A provider or set of providers wishing to make their resources discoverable create a record describing each resource.  These records are then statically deployed to some web-accessible location; typically co-located with the resource the record is describing (e.g. in a web accessible directory).  Collections of related records can then be grouped and described using a collection object.  Each collection object includes links to each record in the collection.

[source]
----
               collection
              (catalogue)
                   |
        +----------+----------+ ...
        |          |          |
     record     record     record ...
        |          |          |
     resource   resource   resource ...
----

The collection object represent the root of a 3-level tree structure where the leaf nodes are resources to be discovered and the node just before the a leaf resource node is a record describing the resource.

These statically deployed collection and record objects can easily be traversed using a web browser and indexed by search engine crawlers.

Although not described in this specification, a deeper tree strcture of linked collection objects can be used to organize a hierarchy of collections and records.
