[big]*i.     Abstract*

The OGC API family of standards are being developed to make it easy for anyone to provide geospatial data to the web. These standards build upon the legacy of the OGC Web Service standards (WMS, WFS, WCS, WPS, etc.), but define resource-centric APIs that take advantage of modern web development practices. 

This document defines the OGC API for Records. A Record is a way of making a resource discoverable. In this context, resources are things that would be useful to a user or developer, such as features, coverages, tiles / maps, assets, services or widgets. The OGC API - Records provides a way to query or browse a curated set of Records known as a catalogue. 

[reftext='{table-caption} {counter:table-num}']
.Overview of resources, applicable HTTP methods and links to the document sections[[table_1]][[tldnr]]
[cols="25,35,10,20",options="header"]
|===
|Resource |Path |HTTP method |Document reference
|Landing page |`/` |GET |<<landing_page,API landing page>>
|Conformance declaration |`/conformance` |GET |<<conformance_classes,Declaration of Conformance Classes>>
|Record collections |`/collections` |GET |<<collections-access,Collection Access>>
|Record collection |`/collections/{collectionId}` |GET |<<collectionInfo,Collection Information>>
|Records |`/collections/{collectionId}/items` |GET |<<records-access,Records Access>>
|Record |`/collections/{collectionId}/items/{recordId}` |GET |<<record-access,Record Access>>
|===

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, OGC API, catalogue, record, resource

[big]*iii.   Preface*

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

Organization name(s)

* CubeWerx Inc.

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

|===
^|Name  ^|Affiliation
| Panagiotis (Peter) A. Vretanos (editor) | CubeWerx Inc.
| Tom Kralidis (editor) | Meteorological Service of Canada
|===
