[[clause-encodings]]
== Encodings

[[requirements-class-json-clause]]
=== Requirements Class JSON

include::requirements/requirements_class_json.adoc[]

JSON and GeoJSON are commonly used formats that are simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using JSON-based formats supporting: 

* JSON is recommended if <<clause-record-collection,catalogue>> and <<clause-record-folder,folder>> data can be represented in JSON for the intended use
* and GeoJSON is recommended, if <<clause-record-core,record>> data can be represented in GeoJSON for the intended use.

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the JSON Conformance Class
. The client negotiates to a JSON or GeoJSON encoded response.

include::requirements/json/REQ_geojson-response.adoc[]

include::requirements/json/REQ_geojson-content.adoc[]

.link:http://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordGeoJSON.yaml[Schema for a catalogue record in JSON(recordGeoJSON.yaml)]
[source,YAML]
----
include::../openapi/schemas/recordGeoJSON.yaml[]
----

include::requirements/json/REQ_json-response.adoc[]

include::requirements/json/REQ_json-content.adoc[]

[[schema_json_catalogue]]
.link:https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/catalogue.yaml[Schema for a catalogue in JSON(catalogue.yaml)]
[source,YAML]
----
include::../openapi/schemas/catalogue.yaml[]
----

[[schema_json_folder]]
.link:https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/folder.yaml[Schema for a folder in JSON(folder.yaml)]
[source,YAML]
----
include::../openapi/schemas/folder.yaml[]
----

[[requirements-class-html-clause]]
=== Requirements Class HTML

include::requirements/requirements_class_html.adoc[]

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the HTML Conformance Class
. The client negotiates an HTML format

Catalogue information that is only accessible in formats primarily intended to
be read by machines, such as JSON or XML, have two issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web;

* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines] <<SDWBP>>. This standard therefore <<rec_html,recommends supporting HTML as an encoding>>.

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

