[[clause-records-api]]
== Requirements Class "Records API"

[[records-api-overview]]
=== Overview

include::requirements/requirements_class_records-api.adoc[]

The core API for a catalogue is defined by the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

[[req_records-api_resource-name-mapping]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/resource-name-mapping*

Each reference to `features` or `feature` in the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard SHALL be replaced by the terms `records` or `record` when interpreting an http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] requirement for the Records API.
|===

=== API landing page

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#_api_landing_page[API landing page] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

=== API definition

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#_api_definition_2[API definition] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

=== Declarations of conformance classes

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#_declaration_of_conformance_classes[Declaration of conformance classes] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

[[req_records-api_conformance]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/conformance*

An implementation of the Records API SHALL declare the following conformance classes in the conformance declaration retrieved from the `/conformance` endpoint as defined in the http://docs.ogc.org/is/17-069r3/17-069r3.html#_declaration_of_conformance_classes[Declaration of conformance classes] clause of the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/searchable-catalogue
* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core
* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-collection
* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/records-api
|===

[[per_records-api_conformance]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/record-aoi/conformance*

The conformance declaration MAY include the following conformance classes:

* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/sorting
* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/cql
* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/json
* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/html
* http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/autodiscovery
|===

[[sc_http]]
=== HTTP 1.1

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#_http_1_1[HTTP 1.1] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

=== Unknown or invalid query parameters

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#query_parameters[Unknown or invalid query parameters] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

=== Web caching

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#web_caching[Web caching] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

=== Support for cross-origin requests

See http://docs.ogc.org/is/17-069r3/17-069r3.html#cross_origin[Support for cross-origin requests] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

=== Encodings

While OGC API Records does not specify any mandatory encoding, support for the following encodings is recommended.

include::recommendations/records-api/REC_html.adoc[]

include::recommendations/records-api/REC_json.adoc[]

The requirements specified in the <<sc_http,HTTP 1.1>> sub-clause imply that the encoding of a server response is determined using content negotiation as specified by the HTTP RFC.

The <<media-types-section,Media Types>> sub-clause includes guidance on media types for encodings that are specified in this document.

Note that any server that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. This document does not mandate any particular approach how this is supported by the server.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") URIs in the browser address bar, can study the API definition.

[NOTE]
=====================================================================
Two common approaches are:

* an additional path for each encoding of each resource (this can be expressed,
for example, using format specific suffixes like ".html");

* an additional query parameter (for example, "accept" or "f") that overrides
the Accept header of the HTTP request.
=====================================================================

=== String internationalization

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#string_i18n[String internationalization] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

=== Coordinate reference systems

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#_coordinate_reference_systems[Coordinate reference systems] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

=== Link headers

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#_link_headers[Link headers] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

[[record-collections]]
=== Record collections

==== Operation 

[[req_records-api_record-collections-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/record-collections*
^|A |The list of available catalogues (i.e. record collections) SHALL be retrieved from the `/collections` endpoint as defined by the http://docs.ogc.org/is/17-069r3/17-069r3.html#_operation_4[Feature collections operation] of the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.
^|B |Only collections where the value of the `itemType` property (JSONPath: `$.collections[*].itemType`) is `record` SHALL be considered record collections or catalogues.
|===

==== Response

[[req_records-api_record-collections-response]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/record-collections*

^|A |Successful execution of the response SHALL be reported as described in the http://docs.ogc.org/is/17-069r3/17-069r3.html#_response_4[Feature collections response] clause of the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.
^|B |The schema of each collection in the response where the value of the `itemType` property (JSONPath: `$.collections[*].itemType`) is `record` SHALL be augmented as defined by <<req_records-api_record-collection,/req/records-api/record-collection>> requirement.
|===

==== Error situations

See http://docs.ogc.org/is/17-069r3/17-069r3.html#http_status_codes[HTTP status codes] for general guidance.

[[record-collection]]
=== Record collection

==== Operation

[[req_records-api_record-collection-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/record-collections*
^|A |The description of a specific catalogue or record collection SHALL be retrieved from the `/collections/{collectionId}` endpoint as defined by the http://docs.ogc.org/is/17-069r3/17-069r3.html#_operation_5[Feature collection operation] of the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.
|===

==== Response 

[[req_records-api_record-collection]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/record-collection*
^|A |The description of a record collection or catalogue can be retrieved from the `/collections/{collectionId}` endpoint as defined in http://docs.ogc.org/is/17-069r3/17-069r3.html#_operation_5[Feature collection] clause of the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.
^|B |The schema the response collection SHALL be augmented as defined in the <<clause-core-record-collection,record collection>> clause and specified by the following schema fragment:

[source,YAML]
----
include::../openapi/schemas/catalogue.yaml[]
----
|===

==== Error situations

See http://docs.ogc.org/is/17-069r3/17-069r3.html#http_status_codes[HTTP status codes] for general guidance.

[[records-access]]
=== Records access

==== Operation

[[req_records-api_records-access]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/record-collections*

For every collection identified in the collections response (path /collections) where the value of the `itemsType` parameter is `record` the server SHALL support the HTTP GET operation at the `/collection/{collectionId}/items` endpoint as defined in the http://docs.ogc.org/is/17-069r3/17-069r3.html#_operation_6[Feature operation] clause of the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.
|===

[[parameters-section]]
==== Parameters

===== Overview

[[req_records-api_mandatory-params]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/mandatory-params*

An implementations of the Records API shall support the parameters listed in <<core-query-parameters-table>> at the `/collections/{collectionId}/items` endpoints.
|===

[#core-query-parameters-table,reftext='{table-caption} {counter:table-num}']
.Table of Query Parameters
[cols="15,85",options="header"]
|===
|Parameter name |Description
|bbox |A bounding box. If the spatial extent of the record intersects the specified bounding box then the record shall be presented in the response document.
|datetime |A time instance or time period. If the temporal extent of the record intersects the specified data/time value then the record shall be presented in the response document.
|limit |The number of records to be presented in a response document.
|q |A comma-separated list of search terms. If any server-chosen text field in the record contains 1 or more of the terms listed then this records shall appear in the response set.
|type |An equality predicate consistent of a comma-separated list of resource types.  Only records of the listed type shall appear in the resource set.
|externalid |An equality predicate consistent of a comma-separated list of external resource identifiers. Only records with the specified external identifiers shall appear in the response set.
|_prop_=_value_ |Equality predicates with any queryable (see: /collections/{catalogueId}/queryables)
|===

[[core-query-parameters-bbox]]
===== Parameter bbox

include::requirements/records-api/REQ_query-param-bbox.adoc[]

[[core-query-parameters-datetime]]
===== Parameter datetime

include::requirements/records-api/REQ_query-param-datetime.adoc[]

[[core-query-parameters-limit]]
===== Parameter limit

include::requirements/records-api/REQ_query-param-limit.adoc[]

[[core-query-parameters-q]]
===== Parameter q

include::requirements/records-api/REQ_query-param-q-definition.adoc[]

include::recommendations/records-api/REC_param-q.adoc[]

include::requirements/records-api/REQ_query-param-q-response.adoc[]

[[core-query-parameters-type]]
===== Parameter type

include::requirements/records-api/REQ_query-param-type-definition.adoc[]

include::recommendations/records-api/REC_query-param-type-definition.adoc[]

include::requirements/records-api/REQ_query-param-type-response.adoc[]

[[core-query-parameters-externalid]]
===== Parameter externalId

include::requirements/records-api/REQ_query-param-externalid-definition.adoc[]

include::requirements/records-api/REQ_query-param-externalid-response.adoc[]

[[additional-query-parameters]]
===== Additional query parameters

This standard defines the following URL query parameters based on the set of
<<core-queryables-record-table,core queryables>> to support record selection
based on the resource type and/or an external identifier associated with the
resource.

* <<core-query-parameters-type,type>>
* <<core-query-parameters-externalid,externalId>>

include::recommendations/records-api/REC_additional-query-parameters.adoc[]

===== Combinations of Filtering Parameters

Any combination of query parameters from the <<core-query-parameters-table,Table of Query Parameters>> and any <<additional-query-parameters,additional query parameters>> may be specified for filtering. Note that the requirements on these parameters imply that only records matching all the predicates are in the result set; i.e., the logical operator between the predicates is **AND** (exclusive).

[[query-response]]
==== Response

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#_response_6[Response] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

include::requirements/records-api/REQ_record-collection-response.adoc[]

<<response-encodings>> lists specific requirements based on the negotiated representation of the response.

[#response-encodings,reftext='{table-caption} {counter:table-num}']
.Negotiated representation of response 
[width=40%,cols="30%,70%",options="header"]
|===
|Representation |Requirements
|JSON/GeoJSON |<<record_json_encoding,Requirements Class JSON>>
|HTML |<<record_html_encoding,Requirements Class HTML>>
|===

==== Error situations

See http://docs.ogc.org/is/17-069r3/17-069r3.html#http_status_codes[HTTP status codes] for general guidance.

==== Examples

The following is an example of a response to an OGC API - Records query
operation (path: `/collections/{collectionId}/items`).  This example shows
a JSON response and the response container is a GeoJSON feature collection.
Specific records are not presented in this example in order to illustrate
the structure of the response container in GeoJSON.

[#records-example,reftext=`Records Example`]
.Records Example in GeoJSON
[source,json]
----
include::../examples/json/record-collection.json[]
----

The following is an example of a single catalogue record encoded in GeoJSON.
Such a record might appears in the `features` array of a
<<records-example,query response>> or it may be the response when a specific,
single record is accessed (path: `/collections/{collectionId}/items/{recordId}`).

[#record-example,reftext=`Record Example`]
.Record Example in GeoJSON
[source,json]
----
include::../examples/json/record.json[]
----

=== Record access

==== Operation

[[req_records-api_record-access]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/records-api/record-access*

^|A |For every collection identified in the collections response (path `/collections`) where the value of the `itemsType` parameter (JSONPath: `$.collections[*].itemType`) is `record` the server SHALL support the HTTP GET operation at the `/collection/{collectionId}/items/{recordId}` endpoint.
^|B |The parameter `collectionId` is each `id` property in the collections response (JSONPath: $.collections[*].id) where the value of the `itemType` property (JSONPath: `$.collections[*].itemType`) is `record`. `recordId` is the local identifier of the record.
|===

==== Response

See: http://docs.ogc.org/is/17-069r3/17-069r3.html#_response_7[Response] from the http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] standard.

==== Error situations

See http://docs.ogc.org/is/17-069r3/17-069r3.html#http_status_codes[HTTP status codes] for general guidance.

If the path parameter `collectionId` or the path parameter `recordId` do not exist on the server, the status code of the response will be 404.
