[[clause-encodings]]
== Encodings

[[requirements-class-geojson-clause]]
=== Requirements Class GeoJSON

include::requirements/requirements_class_geojson.adoc[]

GeoJSON is a commonly used format that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format supporting GeoJSON is recommended, if record data can be represented in GeoJSON for the intended use.

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the JSON Conformance Class
. The client negotiates to a record response encoded as GeoJSON.

include::requirements/geojson/REQ_content.adoc[]

[[schema_geojson_record]]
.link:http://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordGeoJSON.yaml[Schema for a catalogue record in JSON(recordGeoJSON.yaml)]
[source,YAML]
----
include::../openapi/schemas/recordGeoJSON.yaml[]
----

[[requirements-class-html-clause]]
=== Requirements Class HTML

include::requirements/requirements_class_html.adoc[]

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the HTML Conformance Class
. The client negotiates an HTML format

Catalogue information that is only accessible in formats primarily intended to
be read by machines, such as JSON or XML, have two issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web;

* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines] <<SDWBP>>. This standard therefore <<rec_html,recommends supporting HTML as an encoding>>.
