[[conformance_class]]
== Conformance

Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance, are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The standardization targets of all conformance classes are "Web APIs".

OGC API - Common provides a common foundation for OGC API standards. Therefore, this standard should be viewed as an extension to OGC API - Common. Conformance to this standard requires demonstrated conformance to the applicable Conformance Classes of OGC API - Common.

This standard identifies eleven (11) Conformance Classes. The Conformance Classes implemented by an API are advertised through the <<conformance-classes,`/conformance`>> path on the <<landing-page,landing page>>. Each Conformance Class has an associated Requirements Class. The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.

The Requirements Classes for OGC API - Records are:

* <<clause-static-catalogue,Static Catalogue>>
* <<clause-searchable-catalogue,Searchable Catalogue>>
* <<clause-record-core,Record>>
* <<clause-record-collection,Record collection>>
* <<clause-core-api,Record API>>
* <<clause-sorting,Sorting>>
* <<clause-cql-filter,Filtering using the Common Query Language (CQL)>>
* <<clause-opensearch,OpenSearch>>
* <<requirements-class-json-clause,JSON-Record>>
* <<requirements-class-atom-clause,ATOM-Record>>
* <<requirements-class-html-clause,HTML-Record>>

The <<clause-static-catalogue,Static Catalogue>> conformance class defines the core requirements for a static catalogue.  The <<clause-record-core,Record>>, <<clause-record-collection,Record collection>> are mandatory requirements classes that must be implemented for this conformance class.

The <<clause-searchable-catalogue,Searchable Catalogue>> conformance class defines the core requirements for a searchable catalogue.  The <<clause-record-core,Record>>, <<clause-record-collection,Record collection>> and <<clause-core-api,Record API>> requirements are mandatory requirements classes that must be implemented for this conformance class.

The <<clause-record-core,_Record_ Requirements Class>> defines the core schema of a catalogue record which is a set of properties (<<core-queryables,core queryables>>) that can be used to make any resource discoverable via a catalogue.  This core set of properties can be extended by communities of interest or to suite specific needs.

The <<clause-record-collection,_Record Collection_ Requirements Class>> defines the metadata used to describe a collection of records.

The <<clause-record-api,_Records API_ Requirement Class>> defines an API for searching collections of records based on logically connected predicates they can include spatial and/or temporal predicates.  The Records API is based on http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Feature - Part 1: Core] with <<records-access,extensions>> specific to for OGC API Records.

The <<clause-sorting,_Sorting_ Requirements Class>> defines the requirements to support sorting of records in a query response.

The <<clause-record-filter,_Filter using the Common Query Language_ Requirements Class>> defines the requirements to support record filtering using https://docs.ogc.org/DRAFTS/19-079r1.html[CQL].

The <<clause-opensearch,_OpenSearch_ Requirements Class>> defines the requirements to support query by OpenSearch clients.

The <<requirements-class-json-clause,_JSON-Record_ Requirements Class>> defines the requirements for a GeoJSON (see RFC 7946) representation of a standard catalogue record.

The <<requirements-class-atom-clause,_ATOM-Record_ Requirements Class>> defines the requirements for an ATOM representation of a standard catalogue record.

The <<requirements-class-html-clause,_HTML-Record_ Requirements Class>> defines the requirements for an HTML representation of a standard catalogue record.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<ats_core_record,Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core
|<<ats_record_collection,Record Collection>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-collection
|<<ats_record_api,Record API>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-api
|<<ats_sorting,Sorting>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/sorting
|<<ats_cql,CQL>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/cql
|<<ats_opensearch,OpenSearch>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/opensearch
|<<ats_json,JSON-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/json
|<<ats_atom,ATOM-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/atom
|<<ats_atom,HTML-Record>> |http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/html
|===

include::requirements/core/REQ_conformance.adoc[]

include::recommendations/core/PER_additional-conformance.adoc[]
