[[req_stac-extensions_conformance]]

[requirement]
====
[%metadata]
identifier:: /req/stac-extensions/conformance
part:: A server that provides records through an API, and whose records or catalogs use STAC extensions, SHALL declare the following conformance class in the conformance declaration retrieved from the `/conformance` endpoint, as defined in the http://docs.ogc.org/is/17-069r4/17-069r4.html#_declaration_of_conformance_classes[Declaration of conformance classes] clause of http://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Features - Part 1: Core]:
+
* http://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac-extensions
part:: In a crawlable catalog, each catalog object that uses STAC extensions, or whose records use them, SHALL include the URI listed above in its `conformsTo` member.
====

NOTE: A crawlable catalog has no `/conformance` endpoint. The second part therefore follows the pattern of the `/req/crawlable-catalog/conformance` requirement in https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API - Records - Part 1: Core], which places the conformance declaration in the catalog object.
