[[rec_record-core_type]]

//[width="90%",cols="2,6a"]
//|===
//^|*Recommendation {counter:rec-id}* |*/rec/record-core/type*
//^|A |A record SHOULD include the `type` property to indicate the nature or genre of the resource that the record is describing.
//^|B |The list of codes that can occur in records of a catalog for the property `type` SHOULD use a formal, controlled vocabulary defined by an organization (e.g. ISO), or a community of interest/domain (e.g. WMO).
//^|C |The list of codes that can occur in records of a catalog for the property `type` SHOULD be listed as enum values in the API definition of the record schema.
//|===

[recommendation]
====
[%metadata]
identifier:: /rec/record-core/type
part:: A record SHOULD include the `type` property to indicate the nature or genre of the resource that the record is describing.
part:: The list of codes that can occur in records of a catalog for the property `type` SHOULD use a formal, controlled vocabulary defined by an organization (e.g. ISO), or a community of interest/domain (e.g. WMO).
part:: The list of codes that can occur in records of a catalog for the property `type` SHOULD be listed as enum values in the API definition of the record schema.
====