[[ats_sorting_defaultSortOrder-definition]]
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/sorting/defaultSortOrder-definition*
^|Test Purpose |Validate the behavior of sort order definitions.
^|Requirement |<<req_sorting_defaultSortOrder-definition,/req/sorting/defaultSortOrder-definition>>
^|Test Method |. Construct a path for a collection page.
. Issue an HTTP GET request on the path.
. Check that the `+defaultSortOrder+` attribute exists.
. Construct a path for collection sortables.
. Issue an HTTP GET request on the path
. For each sortable found in the `+defaultSortOrder+` array, check that it is  present in the results of the sortables result.
^|Test Method |. Construct a path for a collection page.
. Issue an HTTP GET request on the path.
. Check that the `+defaultSortOrder+` attribute exists.
. Using one sortable, construct a path for an `+.../items+` query with `+sortby+` using explicit ascending order (`+`).
. Issue an HTTP GET request on the path.
. Parse the response to capture the sortable property for each record returned.
. Verify that sorting the list of sortable properties in ascending order is consistent with the response of the server.
. Using one sortable, construct a path for an `+.../items+` query with `+sortby+` using descending order (`-`).
. Issue an HTTP GET request on the path.
. Parse the response to capture the sortable property for each record returned.
. Verify that reverse sorting the list of sortable properties in descending order is consistent with the response of the server.
^|Test Method |. Construct a path for a collection page.
. Issue an HTTP GET request on the path.
. Check that the `+defaultSortOrder+` attribute exists.
. Using one sortable, construct a path for an `+.../items+` query with `+sortby+` using explicit ascending order (`+`).
. Issue an HTTP GET request on the path.
. Using the same sortable, construct a path for an `+.../items+` query with `+sortby+` using implicit ascending order (i.e. no `+`).
. Issue an HTTP GET request on the path.
. Verify that the records returned in both responses are identical.
|===

[abstract_test]
====
[%metadata]
identifier:: TBA
target:: TBA
test-purpose:: TBA
test-method::
+
--
TBA
--
====