[[overview]]
== Overview

[[general-overview]]
=== General

T.B.D.

[[records-paths]]
[reftext='{table-caption} {counter:table-num}']
.Record API Paths
[width="90%",cols="40,20,40",options="header"]
|===
^|**Path Template** ^|**Relation** ^|**Resource** 
|<<collections,{root}/collections>> |`data` |Metadata describing the spatial collections available from this API.
|<<collectionInfo,{root}/collections/{collectionId}>> | |Metadata describing the collection which has the unique identifier `{collectionId}`
|===

Where:

* {root} = Base URI for the API server
* {collectionId} = an identifier for a specific collection

NOTE: This table is copied from Part 1 as a placeholder to a similar table for Part 2.

[[record-schema-overview]]
=== Record Schema

T.B.D.

Basically collectionInfo.yaml extended with the core queriables from Part 1.

=== Search

The Records API offers various levels of search capability of escalating complexity and capability.  At the core is the ability to search the catalogue by specifying:

* a bounding box
* a time instant or time period
* keywords
* free text
* equality predicates based on a subset of core queryables (e.g. by resource type, by external identifier)

Finally extensions, such as the https://docs.ogc.org/DRAFTS/19-079.html[OGC API - Features - Part 3: Filter and the Common Query Language (CQL)], may be used with Part 2 to support complex search capabilities using a rich set of logically connected search predicates where the user has full control over to query expression.

[[dependencies-overview]]
=== Dependencies

T.B.D.
