== Conformance

Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance, are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The one Standardization Target for this standard is Web APIs.

OGC API - Common provides a common foundation for OGC API standards. Therefore, this standard should be viewed as an extension to API - Common. Conformance to this standard requires demonstrated conformance to the applicable Conformance Classes of API - Common. 

This standard identifies one (1) Conformance Classes. The Conformance Classes implemented by an API are advertised through the `/conformance` path on the landing page. Each Conformance Class has an associated Requirements Class. The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.

The Requirements Classes for Part 2 are:

* <<clause-Collections,Collections>>
* <<clause-sorting,Sorting>>
* <<clause-cql-filter,Filtering using the Common Query Language (CQL)>>
* <<clause-opensearch,OpenSearch>>
* <<requirements-class-json-clause,JSON>>
* <<requirements-class-atom-clause,ATOM>>
* <<requirements-class-html-clause,HTML>>

The _Collections_ Requirements Class defines:

* a set of extended properties for the collectionInfo object,
* a set of extended query parameters that support boundning box spatial queries, temporal queries, full text searching, searching be collection type, external identifier searching and parameters for sorting responses.

The _Sorting_ Requirements Class defines the requirements to support sorting of collection info objects in a query response.

The _Filter using the Common Query Language_ Requirements Class defines the requirements to support filtering of collection info object using CQL.

The _OpenSearch_ Requirements Class defines the requirements to support query by OpenSearch clients.

The _JSON_ Requirements Class defines the requirements for a JSON representation of an extended collection info object.

The _ATOM_ Requirements Class defines the requirements for an ATOM representation of an extended collection info object.

The _HTML_ Requirements Class defines the requirements for an HTML representation of an extended collection info object.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<ats_collections,Collections>> |http://www.opengis.net/spec/ogcapi-records-2/1.0/conf/collections
|<<ats_sorting,Sorting>> |http://www.opengis.net/spec/ogcapi-records-2/1.0/conf/sorting
|<<ats_cql,CQL>> |http://www.opengis.net/spec/ogcapi-records-2/1.0/conf/cql
|<<ats_opensearch,OpenSearch>> |http://www.opengis.net/spec/ogcapi-records-2/1.0/conf/opensearch
|<<ats_json,JSON>> |http://www.opengis.net/spec/ogcapi-records-2/1.0/conf/json
|<<ats_atom,ATOM>> |http://www.opengis.net/spec/ogcapi-records-2/1.0/conf/atom
|<<ats_html,HTML>> |http://www.opengis.net/spec/ogcapi-records-2/1.0/conf/html
|===
