[[clause-encodings]]
== Encodings

[[requirements-class-json-clause]]
=== Requirements Class JSON

==== Overview

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the JSON Conformance Class
. The client negotiates a JSON or GeoJSON format

The JSON Requirements Class restricts requirements defined in the `Core` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `Core` requirements which lay within each scope.

include::requirements/requirements_class_json.adoc[]

==== Common

This section covers the requirements inherited from the API - Common standard. Its scope includes responses for the following operations:

* `{root}/collections`: Collections
* `{root}/collections/{collectionid}`: Collection Information

include::requirements/json/REQ_api-common.adoc[]

It is also necessary to advertise conformance with this Requirements Class.

include::requirements/json/REQ_json-conformance.adoc[]

[[schema_record]]
.link:http://schemas.opengis.net/ogcapi/records/part2/1.0/openapi/schemas/extendedCollectionInfo.yaml[Schema for an extended collection information object (extendedCollectionInfo.yaml)]
[source,YAML]
----
include::../openapi/schemas/extendedCollectionInfo.yaml[]
----

[[requirements-class-html-clause]]
=== Requirements Class HTML

==== Overview

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the HTML Conformance Class
. The client negotiates an HTML format

The HTML Requirements Class restricts requirements defined in the `Core` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `Core` requirements which lay within each scope.

include::requirements/requirements_class_html.adoc[]

==== Common

This section covers the requirements inherited from the API - Common standard. Its scope includes responses for the following operations:

* `{root}/collections`: Collections
* `{root}/collections/{collectionid}`: Collection Information

include::requirements/html/REQ_api-common.adoc[]

It is also necessary to advertise conformance with this Requirements Class.

include::requirements/html/REQ_html-conformance.adoc[]

This is discussed in detail in link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines] <<SDWBP>>. This standard therefore <<rec_html,recommends supporting HTML as an encoding>>.

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

[[requirements-class-atom-clause]]
=== Requirements Class ATOM

==== Overview

The following requirements apply to an OGC API - Records implementation when the following conditions apply:

. The API advertises conformance to the ATOM Conformance Class
. The client negotiates an ATOM format

The ATOM Requirements Class restricts requirements defined in the `Core` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `Core` requirements which lay within each scope.

include::requirements/requirements_class_atom.adoc[]

==== Common

This section covers the requirements inherited from the API - Common standard. Its scope includes responses for the following operations:

* `{root}/collections`: Collections
* `{root}/collections/{collectionid}`: Collection Information

It is necessary to advertise conformance with this Requirements Class.

include::requirements/atom/REQ_atom-conformance.adoc[]

include::requirements/atom/REQ_common-content.adoc[]

[#xml_content,reftext='{table-caption} {counter:table-num}']
.Media types and XML elements for each common resource[[table_3]]
[cols="30,35,35",options="header"]
|===
|Resource |Path |XML root element
|Collections        |`/collections` |`core:Collections`
|Record collection +
(resource collection with `itemType=record`) |`/collections/{collectionId}` |`core:Collections`, with just one entry for the collection `collectionId`
|===

The namespace prefixes used above and in the Part 2 XML schema is:

* `collections`: `http://www.opengis.net/ogcapi-record-2/1.0`

* `atom`: `http://www.w3.org/2005/Atom`

* `xlink`: `http://www.w3.org/1999/xlink`

In addition to HTML and GeoJSON, a significant volume of record data, especially in the Earth Observation space, is available in XML-based formats, notably https://tools.ietf.org/html/rfc4287[ATOM]. Therefore, this standard specifies requirements classes for https://tools.ietf.org/html/rfc4287[ATOM].

include::requirements/atom/REQ_media-type.adoc[]

include::requirements/atom/REQ_feed-extension-elements.adoc[]

include::requirements/atom/REQ_content.adoc[]

[#atom_content,reftext='{table-caption} {counter:table-num}']
.Media types and XML elements for each resource[[table_3]]
[cols="30,35,35",options="header"]
|===
|Resource |Path |XML root element
|Records |`/collections` |`atom:feed`
|Record |`/collections/{collectionId}` |`atom:entry`
|===
