[[clause-cql]]
== Requirements Class "CQL Filter"

[[cql-overview]]
=== Overview

include::requirements/requirements_class_cql.adoc[]

This clause defines the binding to the filter parameters defined in the https://docs.ogc.org/DRAFTS/19-079.html#_requirements_class_filter[OGC API - Features - Part 3: Filter and the Common Query Language (CQL), Requirements Class "Filter"] clause.

=== Collection info objects

==== Operation

As specified in the ??? clause of OGC API Common, collection info objects are accessed using the HTTP GET method via the `/collections` path.  The following additional requirements bind the parameters https://docs.ogc.org/DRAFTS/19-079.html#filter-param[filter], https://docs.ogc.org/DRAFTS/19-079.html#filter-lang-param[filter-lang] and https://docs.ogc.org/DRAFTS/19-079.html#filter-filter-crs[filter-crs] to the GET operation on this path.

include::requirements/cql/REQ_filter-param.adoc[]

include::requirements/cql/REQ_filter-lang-param.adoc[]

include::recommendations/cql/REC_text-encoding.adoc[]

include::recommendations/cql/REC_json-encoding.adoc[]

// TODO include::requirements/cql/REQ_cql-atom.adoc[]
// TODO include::requirements/cql/REQ_cql-html.adoc[]

include::requirements/cql/REQ_filter-crs-param.adoc[]

==== Response

include::requirements/cql/REQ_response.adoc[]

=== Filtering on links

==== Overview

Links can be added to a collection info object in various ways.  This clause 
describes the various linking patterns and describes how to use CQL to
filter based on links.

==== Linking in collection info object

Links can be added to the following sections in an extended collection info object:

. to the collection info object itself as the value of a key/property
. the <<query-response,links>> section.

The schema for links added to the <<query-response,links>> section in based on https://tools.ietf.org/html/rfc8288[RFC 8288] and is described in https://docs.ogc.org/DRAFTS/19-072.html#link-relation-conventions[OGC API - Common - Part 1: Core] and http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml[OGC API - Features - Part 1: Core].

Links added directly to the collection info object can be added using the following patterns:

. The link relation is the key for an array of links with a schemas similar to that used in the <<query-response,links>> section but omitting the `rel` key.
. The link relation is the key for an array of `href` values.
. The link relation is the key for an an `href` value.

The following examples illustrate each of these linking patterns:

[#linking-pattern-1,reftext=`Adding links to the **links** section.`]
.Adding links to the **links** section
----
{
   .
   .
   .,
   "links":
   [
      .
      .
      .,
      {
         "rel" : "alternate",
         "title" : "This records as XML.",
         "href" : "https://example.com/collections/MyCat/items/rec01.xml"
      },
      {
         "rel": "next",
         "title": "The next record in this result set.",
         "href" : "https://example.com/collections/MyCat/items/rec02"
      },
      .
      .
      .
   ],
   .
   .
   .
}
----

[#linking-pattern-2,reftext=`Adding links to the collection info object itself.`]
.Adding links to the collection info object itself
----
{
   .
   .
   .,
   "related": [
      {
	    "title" : "A related record",
	    "href" : "https://example.com/related-record-path/rec15"
	   }
   ],
   "license": {
	 "title" : "CC BY 2.0",
	 "href" : "https://creativecommons.org/licenses/by/2.0/"
	},
   .
   .
   .
}
----

[#linking-pattern-3,reftext=`Adding links to the **properties** section.`]
.Adding links to the collection info object itself
----
{
   .
   .
   .,
   "related": ["https://example.com/related-record-path/rec15"],
   "license": "https://creativecommons.org/licenses/by/2.0/",
   .
   .
   .
}
----

==== Example CQL filters on links

The following example illustrate how to filter links that may
appear in a catalogue record.

[#filter-pattern-1,reftext=`Filtering links in the **links** section.`]
.Filtering links in the **links** section
----
links[rel='license'].title LIKE 'CC%'
----

[#filter-pattern-2,reftext=`Filtering links as **properties** in the collection object.`]
.Filtering links that are **properties** in the collection object
----
properties.related[*].href LIKE '%/rec15' AND properties.license.title LIKE 'CC%'
----

[#filter-pattern-3,reftext=`Filtering links in the **properties** section.`]
.Filtering links that are **properties** in the collection object
----
properties.related LIKE '%/rec15' AND properties.license LIKE 'https://creativecommons.org/licenses/%'
----
