[[req_stac_entity]]

[requirement]
====
[%metadata]
identifier:: /req/stac/entity
part:: A record that includes the URI `http://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac` in its `conformsTo` member SHALL be a valid STAC Item according to the version of the <<STAC,STAC specification>> given in its `stac_version` member.
part:: A catalog that includes the URI `http://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac` in its `conformsTo` member SHALL be a valid STAC Collection according to the version of the <<STAC,STAC specification>> given in its `stac_version` member. This also applies to all records of the catalog.
part:: If a server declares the conformance class `http://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac` at its `/conformance` endpoint, each record that the server provides in a JSON encoding SHALL be a valid STAC Item, and each catalog that the server provides in a JSON encoding SHALL be a valid STAC Collection.
====

NOTE: A catalog can never be a STAC Catalog, because OGC API - Records - Part 1: Core fixes the `type` member of a catalog to `Collection`, while a STAC Catalog requires `Catalog`.

NOTE: A valid STAC entity fulfills all requirements of the STAC specification, not only those that can be checked with the STAC JSON Schemas. Members that are easily missed when starting from a record include `stac_version`, `bbox`, `assets`, `properties.datetime`, and the `collection` member that STAC requires whenever a link with the relation type `collection` is present. <<clause_records-and-stac-items,Records and STAC Items>> and <<clause_records-and-stac-collections,Catalogs and STAC Collections>> list all differences.
