[[req_records-api_resource-name-mapping]]

//[width="90%",cols="2,6a"]
//|===
//^|*Requirement {counter:req-id}* |*/req/records-api/resource-name-mapping*
//
//Each reference to `features` or `feature` in the narrative text of http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] Standard SHALL be replaced by the terms `records` or `record` when interpreting an http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] requirement for the Records API.
//|===


[requirement]
====
[%metadata]
identifier:: /req/records-api/resource-name-mapping
part:: Each reference to `features` or `feature` in the narrative text of http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] Standard SHALL be replaced by the terms `records` or `record` when interpreting an http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] requirement for the Records API.
====

NOTE: This requirement does not imply that the terms `features` or `feature` in the schemas or code examples of http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] should be replaced by the terms `records` or `record`.  For example, the <<clause-record-encoding-json,GeoJSON encoding of a record>> and the https://docs.ogc.org/is/17-069r3/17-069r3.html#_requirements_class_geojson[GeoJSON encoding of a feature] both include a top-level field named `type` whose value is fixed to `Feature` as defined in the https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON specification].  This requirement does not imply that the value `Feature` should be changed to `Record` in this Standard since such a change would invalidate the GeoJSON document.
