.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

This standard defines requirements for supporting Spatial-Temporal Asset Catalog (STAC) extensions in an OGC API Records implementation.

Records, as defined in https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API - Records - Part 1: Core], share many common elements with STAC items.  This standard further defines requirements that allow records generated by a server to be fully compliant STAC items.

== Security considerations

Given the dependency on https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API - Records] aspects of security are discussed in that Standard.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
|Matthias Mohr (editor) | moreGeo GmbH 
|Panagiotis (Peter) A. Vretanos (editor) | CubeWerx Inc.
|Angelos Tzotsos | Open Source Geospatial Foundation
|Tom Kralidis | Environment and Climate Change Canada
|===

== Contributors

//This clause is optional.

Additional contributors to this Standard include the following:

Individual name(s), Organization
