== Terms and Definitions

[[asset-def]]
=== asset
an object that references data of a STAC Item or STAC Collection that can usually be downloaded or streamed, together with metadata about the data, for example its media type and roles (<<STAC>>)

NOTE: STAC separates assets from <<link-def,links>>. Assets reference the data that a STAC Item or STAC Collection describes, for example the files of a satellite scene. They are usually downloadable, and clients load them to access and process the data. Links reference related resources, for example the parent STAC Collection, related STAC Items, or a license text. Clients usually do not download them, but navigate to them or use them in other ways. Members that STAC extensions define for data, such as `file:size` or `proj:shape`, are therefore often defined in the asset metadata.

=== catalog; record collection
a collection of related <<record-def,records>>

=== conformance module; conformance test module
set of related tests, all within a single conformance test class (<<ogc08-131,OGC 08-131>>)

NOTE: When no ambiguity is possible, the word `test` may be omitted. i.e., conformance test module is the same as conformance module. Conformance modules may be nested in a hierarchical way.

=== conformance class; conformance test class
set of conformance test modules that must be applied to receive a single certificate of conformance (<<ogc08-131,OGC 08-131>>)

NOTE: When no ambiguity is possible, the word `test` may be omitted, so conformance test class may be called a conformance class.

[[crawlable-catalog-def]]
=== crawlable catalog
a catalog composed of static, web-accessible files that can only be crawled by following the links embedded in the files (OGC API - Records - Part 1: Core)

NOTE: STAC calls this deployment pattern a _static catalog_.

=== dataset
collection of data, published or curated by a single agent, and available for access or download in one or more serializations or formats (<<DCAT>>)

=== deployment; deployment type 
a set of components implemented to execute the runtime functions of a catalog

EXAMPLE: a crawlable catalog deployment composed of static, web-accessible files

EXAMPLE: a searchable catalog deployment composed of an API that can be used to dynamically search a collection of catalog records

=== distribution
represents an accessible form of a *dataset* (<<DCAT>>)

EXAMPLE: a downloadable file, an RSS feed or a web service that provides the data

=== executable test suite (ETS)
set of code (e.g., Java and CTL) that provides runtime tests for the assertions defined by the ATS. Test data required to do the tests are part of the ETS https://portal.ogc.org/files/?artifact_id=55234[(OGC 08-134)]

[[link-def]]
=== link
an object that describes a relationship between the containing document and another resource, consisting of the URI of the resource (`href`), the relation type (`rel`), and optional hints such as the media type (`type`) and a title (<<rfc8288,RFC 8288>>)

NOTE: In STAC, links reference related resources that clients navigate to or use in other ways than assets, while the data that clients load for access and processing is referenced by <<asset-def,assets>>. In OGC API - Records, links serve both purposes: navigation links express relationships between catalogs and records, and association links reference the resources described by a record.

[[local-resources-endpoint-def]]
=== local resources endpoint
the path from which a catalog of local resources can be retrieved (e.g., `/collections`)

[[local-resources-catalog-def]]
=== local resources catalog
an instance of the document or resource that is retrieved from a <<local-resources-endpoint-def,local resources endpoint>>

[[local-resources-item-def]]
=== local resources item
an instance of an object that provides summary information about a discoverable local resource retrieved from a <<local-resources-catalog-def,local resources catalog>> (e.g., `/collections{/collectionID}`)

[[ogc-api-resource-tree]]
=== OGC API resource tree
a collection of resources defined by the set of https://ogcapi.ogc.org/[OGC API Standards] that are hierarchically organized and exposed by implementations of the https://ogcapi.ogc.org/[OGC API Standards] through a root node that is common to all OGC APIs

[[record-def]]
=== record
atomic unit of information of a catalog that is used to provide information (i.e., metadata) about a particular resource that the publisher of that resources wishes to make discoverable

=== recommendation
expression in the content of a document conveying that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others, or that a certain course of action is preferred but not necessarily required, or that (in the negative form) a certain possibility or course of action is deprecated but not prohibited (<<ogc08-131,OGC 08-131>>) 

=== requirement
expression in the content of a document conveying criteria to be fulfilled if compliance with the document is to be claimed and from which no deviation is permitted (<<ogc08-131,OGC 08-131>>)

=== requirements class
aggregate of all requirement modules that must all be satisfied to satisfy a conformance test class (<<ogc08-131,OGC 08-131>>)

=== requirements module
aggregate of requirements and recommendations of a specification against a single standardization target type (<<ogc08-131,OGC 08-131>>)

=== resource
an asset of interest that may be described by metadata (i.e., a <<record-def,record>>) in a catalog for the purpose of discovery and access (i.e., binding)

=== standardization target
entity to which some requirements of a standard apply (<<ogc08-131,OGC 08-131>>)

NOTE: The standardization target is the entity which may receive a certificate of conformance for a requirements class.

[[stac-def]]
=== STAC; SpatioTemporal Asset Catalog
a specification for describing geospatial resources and their assets with JSON-based catalogs (<<STAC>>)

[[stac-entity-def]]
=== STAC entity
a STAC Catalog, a STAC Collection, or a STAC Item (<<STAC>>)

[[stac-extension-def]]
=== STAC extension
an extension to the <<stac-def,STAC>> specification that defines additional members for <<stac-entity-def,STAC entities>> and is identified by the URI of the JSON Schema that validates those members

NOTE: A list of registered STAC extensions is available at https://stac-extensions.github.io/[stac-extensions.github.io].
