.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

The SpatioTemporal Asset Catalog (STAC) community maintains a large set of extensions that describe geospatial resources in detail, for example their projection, bands, data cube dimensions, or files. This Standard defines how records and catalogs of https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API - Records - Part 1: Core] can use these STAC extensions.

This Standard also defines requirements for records and catalogs that are valid STAC Items and STAC Collections at the same time, so that clients of both ecosystems can use the same documents. Informative clauses compare records with STAC Items, catalogs with STAC Collections, crawlable catalogs with static STAC catalogs, and Records APIs with STAC APIs, explain how links are resolved in both ecosystems, and give guidance for implementing both.

== Security considerations

OGC API - Records - Part 1: Core discusses security aspects that apply to all records and catalogs.

Validating a record against the STAC extensions it lists means retrieving JSON Schemas from the URIs in the `stac_extensions` member. These URIs are provided by the publisher of the record. Validators should only retrieve schemas from trusted locations, cache them, and not follow URIs to local or private network addresses.

Some STAC extensions, such as https://github.com/stac-extensions/authentication[Authentication] and https://github.com/stac-extensions/storage[Storage], describe how to access protected resources. Records using these extensions should only describe access mechanisms and never include credentials.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
|Matthias Mohr (editor) | moreGeo GmbH
|Panagiotis (Peter) A. Vretanos (editor) | CubeWerx Inc.
|Angelos Tzotsos | Open Source Geospatial Foundation
|Tom Kralidis | Environment and Climate Change Canada
|Francis Charette-Migneault | Technologies Luqia
|===

== Contributors

//This clause is optional.

Additional contributors to this Standard include the following:

Individual name(s), Organization
