[[clause_stac-items]]

== Requirements Class "STAC Items"

=== Overview

include::../requirements/requirements_class_stac-items.adoc[]

=== Generating valid STAC items

include::../requirements/stac-items/REQ_conformance.adoc[]

=== Advertising conformance to STAC extensions in a STAC item

include::../recommendations/stac-items/REC_stac-item-conformsto.adoc[]

=== Examples

The following example illustrates how a record that simultaneously conforms to the _OGC API Records - Core_
conformance class, which also happens to be a valid STAC Item definition supplemented by more STAC extensions
requirements, can explicitly indicate both dependencies through the `conformsTo` field. This provides an indication
to clients that the server returning this definition accommodates both representations simultaneously, and that the
entire set of `stac_extensions` requirements also applies to the fields found under a _OGC API Records_ representation.

The advantage of the below representation, in contrast to <<req_stac-items_conformance,/req/stac-items/conformance>>
that indicates "_when a server **has the ability to** support_" STAC extensions, is that the below indication explicitly
tells "_when a specific record **relies on**_" STAC extensions. This allows the server to simultaneously support and
document the generation of records that employ STAC extensions or not. A Core-only _OGC API Records_ definition could
instead omit `https://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac-extensions` from the `conformsTo` field to
communicate that it only supports the Core conformance class, contrary to a STAC-enabled record.

.An OGC API Record with additional STAC extensions requirements and explicit indication of its record conformance
====
[source,json]
----
{
  "id": "b7d2fd24-8cd8-4965-a997-69eb1a987b5a",
  "conformsTo": [
    "https://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core",
    "https://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac-extensions"
  ],
  "stac_extensions": [
    "https://stac-extensions.github.io/contacts/v1.0.0/schema.json",
    "https://stac-extensions.github.io/external-ids/v1.0.0/schema.json",
    "https://stac-extensions.github.io/themes/v1.0.0/schema.json",
    "https://stac-extensions.github.io/projection/v2.0.0/schema.json",
    "https://stac-extensions.github.io/file/v2.1.0/schema.json"
  ],
  "type": "Feature",
  "time": {
    "interval": [null, null]
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [3.37087, 50.7539],
        [3.37087, 53.4658],
        [7.21097, 53.4658],
        [7.21097, 50.7539],
        [3.37087, 50.7539]
      ]
    ]
  },
  "properties": {
    "proj:code": "EPSG:4326",
    "created": "2019-04-16Z",
    "updated": "2025-06-16T12:39:58Z",
    "datetime": "2019-04-16T00:00:00Z",
    "type": "dataset",
    "title": "Zonpotentie velden",
    "description": "...",
    "contacts": [
      {
        "name": null,
        "organization": "Atlas Leefomgeving",
        "emails": [
          {
            "value": "atlasleefomgeving@rivm.nl"
          }
        ],
        "roles": ["resourceProvider"]
      }
    ],
    "externalIds": [
      {
        "scheme": "default",
        "value": "b7d2fd24-8cd8-4965-a997-69eb1a987b5a"
      }
    ],
    "themes": [
      {
        "concepts": [
          {"id": "zonnepanelen" },
          {"id": "energie"}
        ],
        "scheme": null
      }
    ]
  },
  "links": [
    {
      "type": "application/json",
      "rel": "root",
      "title": "The landing page of this server as JSON",
      "href": "https://demo.pygeoapi.io/master?f=json"
    },
    {
      "rel": "self",
      "type": "application/geo+json",
      "title": "This document as JSON",
      "href": "https://demo.pygeoapi.io/master/collections/dutch-metadata/items/b7d2fd24-8cd8-4965-a997-69eb1a987b5a?f=json"
    },
    {
      "rel": "data",
        "type": "image/tiff; application=geotiff",
        "title": "The data as GeoTIFF",
        "href": "https://demo.pygeoapi.io/master/collections/dutch-metadata/items/b7d2fd24-8cd8-4965-a997-69eb1a987b5a/data?f=geotiff",
        "file:size": 123456789,
        "file:checksum": "12209cbc07c3f991725836a3aa2a581ca2029198aa420b9d99bc0e131d9f3e2cbe47",
        "file:local_path": "example.tif"
    }
  ]
}
----
====
