[[clause_stac-extensions]]
== Requirements Class "STAC Extensions"

[[sc_stac-extensions_overview]]
=== Overview

include::../requirements/requirements_class_stac-extensions.adoc[]

This requirements class defines how <<def_record,records>> and <<def_catalog,catalogs>> use <<def_stac-extension,STAC extensions>>. The records and catalogs remain records and catalogs as defined by <<OGC20-004r1,OGC API - Records - Part 1: Core>>. They do not need to be <<def_stac-item,STAC Items>> or <<def_stac-collection,STAC Collections>>. Records and catalogs that are also valid STAC entities are covered by the <<clause_stac,Requirements Class "STAC">>.

[[sc_stac-extensions_using-stac-extensions]]
=== Using STAC extensions

include::../requirements/stac-extensions/REQ_member.adoc[]

include::../requirements/stac-extensions/REQ_extension-conformance.adoc[]

Each STAC extension specifies where its members are placed in STAC entities, for example in the `properties` of a STAC Item, at the top level of a STAC Collection, or in assets. <<extension-member-locations>> shows the corresponding locations in records and catalogs. Where OGC API - Records has no corresponding structure, the STAC structure can be reused, as noted in brackets.

[#extension-member-locations,reftext='{table-caption} {counter:table-num}']
.Location of STAC extension members in records and catalogs
[cols="40,60",options="header"]
|===
|Location in STAC entities |Location in OGC API - Records
|Item Properties (`properties` of a STAC Item) |`properties` of a record
|Top level of a STAC Collection |Top level of a catalog
|Summaries (`summaries` of a STAC Collection) |None (the STAC `summaries` member can be reused in catalogs, see <<per_stac-extensions_summaries,/per/stac-extensions/summaries>>)
|Asset (`assets` of a STAC Item or STAC Collection) |Association links in `links` of a record or catalog, for example with the link relation type `describes` or `enclosure` (the STAC `assets` member can be reused in records and catalogs, see <<per_stac-extensions_assets,/per/stac-extensions/assets>>)
|Item Asset Definition (`item_assets` of a STAC Collection) |None (the STAC `item_assets` member can be reused in catalogs, see <<per_stac-extensions_assets,/per/stac-extensions/assets>>). This is only useful if the records of the catalog include `assets` as well.
|Link (`links`) |`links` of a record or catalog
|===

include::../recommendations/stac-extensions/PER_summaries.adoc[]

[[sc_stac-extensions_assets]]
=== Assets

STAC Items and STAC Collections reference their data files through <<def_asset,assets>>. Records reference the resources they describe through links, for example with the link relation type `describes` or `enclosure`. Many STAC extensions define members for assets, and some extension schemas expect an `assets` member (see <<sc_stac-extensions_known-issues>>). This requirements class therefore allows assets in records and catalogs.

include::../recommendations/stac-extensions/PER_assets.adoc[]

include::../requirements/stac-extensions/REQ_assets.adoc[]

include::../recommendations/stac-extensions/REC_assets.adoc[]

[[sc_stac-extensions_known-issues]]
=== Known issues with STAC extension schemas

Several STAC extension schemas were written for STAC entities only. The following issues affect records that use such extensions. Whether an extension is affected depends on its schema. For the extensions registered at https://stac-extensions.github.io/[stac-extensions.github.io], the issues are tracked in https://github.com/radiantearth/stac-spec/issues/1397[stac-spec#1397], and extensions based on the current https://github.com/stac-extensions/template[STAC extension template] are not affected. Extensions hosted elsewhere do not necessarily follow the template, and any JSON Schema can be listed in `stac_extensions`. Implementers therefore check the schema of each extension they use.

[#known-extension-issues,reftext='{table-caption} {counter:table-num}']
.Known issues with STAC extension schemas and workarounds
[cols="50,50",options="header"]
|===
|Issue |Workaround
|The schema requires an `assets` member in every GeoJSON Feature, even if no member of the extension is used in an asset. Records without `assets` fail validation. This affects, for example, https://github.com/stac-extensions/projection/tree/v2.0.0[Projection v2.0.0] and https://github.com/stac-extensions/file/tree/v2.1.0[File Info v2.1.0]. |Include an empty `assets` object, see <<rec_stac-extensions_assets,/rec/stac-extensions/assets>>. This does not help for extensions that actually depend on assets, for example the Machine Learning Model extension, which requires an asset with a model role. Such records need these assets.
|The schema does not validate members in links, or only some of them. There is no general correspondence between the validation of assets and of links: each extension decides which of its members it validates in links. Members that an extension defines for assets can be placed in links, but invalid values are not always detected. |Place the members in assets, see <<per_stac-extensions_assets,/per/stac-extensions/assets>>.
|The schema requires at least one of its members in `properties` or in an asset, for example https://github.com/stac-extensions/raster/tree/v2.0.0[Raster v2.0.0]. A record that only uses these members in links fails validation. |Place the members in assets, see <<per_stac-extensions_assets,/per/stac-extensions/assets>>.
|===

Once the affected extensions are updated, the workarounds are no longer needed, but they remain valid.

[[sc_stac-extensions_declaring-conformance]]
=== Declaring conformance

include::../requirements/stac-extensions/REQ_conformance.adoc[]

include::../requirements/stac-extensions/REQ_crawlable-catalog.adoc[]

include::../recommendations/stac-extensions/REC_conformsto.adoc[]

[[sc_stac-extensions_extensions-aligned-with-ogc-api-records]]
=== Extensions aligned with OGC API - Records

Several STAC extensions were written to match members that OGC API - Records - Part 1: Core defines. Listing these extensions in `stac_extensions` is optional, because OGC API - Records already allows the members. Listing an extension enables validation against its schema. Once listed, the member is mandatory in records, because each of these extensions requires its member to be present. <<overlapping-extensions>> lists the remaining differences.

[#overlapping-extensions,reftext='{table-caption} {counter:table-num}']
.STAC extensions aligned with OGC API - Records
[cols="22,26,52",options="header"]
|===
|Record member |STAC extension |Differences
|`contacts` |https://github.com/stac-extensions/contacts/tree/v1.0.1[Contacts v1.0.1] |STAC adds `description`. OGC API - Records adds `hoursOfService`. STAC requires `rel` in the links of a contact.
|`externalIds` |https://github.com/stac-extensions/external-ids/tree/v1.0.0[External IDs v1.0.0] |None.
|`themes` |https://github.com/stac-extensions/themes/tree/v1.0.0[Themes v1.0.0] |None.
|`language`, `languages` |https://github.com/stac-extensions/language/tree/v1.0.0[Language v1.0.0] |STAC validates `code` against the pattern of RFC 5646 and only allows `ltr` and `rtl` as `dir`. The extension adds `hreflang` for assets and links.
|`resourceLanguages` |None |The Language extension derives the languages of the resource from the `hreflang` members of the assets.
|`linkTemplates` |https://github.com/stac-extensions/link-templates/tree/v1.0.0[Link Templates v1.0.0] |STAC requires `rel`, does not allow `href`, and adds `method`, `headers`, and `body`.
|===

[[sc_stac-extensions_stac-common-metadata]]
=== STAC common metadata

The https://github.com/radiantearth/stac-spec/blob/v1.1.0/commons/common-metadata.md[STAC common metadata] defines members that are not part of any extension, for example `gsd`, `platform`, `instruments`, `constellation`, `mission`, and `bands`. Records can use these members as well. The STAC specification publishes JSON Schemas for them, for example `instrument.json`, but these are not STAC extensions and are not listed in `stac_extensions`. They are fragments that validate the members at the top level of the object they are applied to. Listed in `stac_extensions`, they would be applied to the whole record and would not check the members in `properties` or in assets. A validator can apply them to `properties`, to each asset, and to the top level of a catalog. In STAC Items and STAC Collections, the STAC JSON Schemas apply them automatically, see the <<clause_stac,Requirements Class "STAC">>.

[[sc_stac-extensions_example]]
=== Example

The following record uses five STAC extensions. It lists the schema URIs in `stac_extensions` and declares the "STAC Extensions" conformance class in `conformsTo`. The record is not a STAC Item: it has no `stac_version`, `bbox`, `properties.datetime`, or `collection` member. `proj:code` gives the coordinate reference system of the described dataset. The `file:size` and `file:checksum` members describe the GeoTIFF file referenced by the `enclosure` link, where the https://github.com/stac-extensions/file/tree/v2.1.0[File Info v2.1.0] schema validates them. The empty `assets` member is needed because the Projection and File Info schemas require it (see <<sc_stac-extensions_known-issues>>). The `profile` link identifies the document as a record, as required by OGC API - Records - Part 1: Core for records in JSON if the "JSON" conformance class is declared.

.A record using STAC extensions
====
[source,json]
----
{
  "id": "b7d2fd24-8cd8-4965-a997-69eb1a987b5a",
  "type": "Feature",
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core",
    "http://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac-extensions"
  ],
  "stac_extensions": [
    "https://stac-extensions.github.io/contacts/v1.0.1/schema.json",
    "https://stac-extensions.github.io/external-ids/v1.0.0/schema.json",
    "https://stac-extensions.github.io/themes/v1.0.0/schema.json",
    "https://stac-extensions.github.io/projection/v2.0.0/schema.json",
    "https://stac-extensions.github.io/file/v2.1.0/schema.json"
  ],
  "time": {
    "date": "2019-04-16"
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [3.37087, 50.7539],
        [3.37087, 53.4658],
        [7.21097, 53.4658],
        [7.21097, 50.7539],
        [3.37087, 50.7539]
      ]
    ]
  },
  "properties": {
    "created": "2019-04-16T00:00:00Z",
    "updated": "2025-06-16T12:39:58Z",
    "type": "dataset",
    "title": "Zonpotentie velden",
    "description": "Solar energy potential of agricultural fields in the Netherlands.",
    "proj:code": "EPSG:28992",
    "contacts": [
      {
        "organization": "Atlas Leefomgeving",
        "emails": [
          {
            "value": "atlasleefomgeving@rivm.nl"
          }
        ],
        "roles": ["resourceProvider"]
      }
    ],
    "externalIds": [
      {
        "scheme": "default",
        "value": "b7d2fd24-8cd8-4965-a997-69eb1a987b5a"
      }
    ],
    "themes": [
      {
        "concepts": [
          {
            "id": "zonnepanelen"
          },
          {
            "id": "energie"
          }
        ],
        "scheme": "https://www.atlasleefomgeving.nl/thema"
      }
    ]
  },
  "links": [
    {
      "rel": "self",
      "type": "application/geo+json",
      "title": "This document as GeoJSON",
      "href": "https://demo.pygeoapi.io/master/collections/dutch-metadata/items/b7d2fd24-8cd8-4965-a997-69eb1a987b5a?f=json"
    },
    {
      "rel": "alternate",
      "type": "text/html",
      "title": "This document as HTML",
      "href": "https://demo.pygeoapi.io/master/collections/dutch-metadata/items/b7d2fd24-8cd8-4965-a997-69eb1a987b5a?f=html"
    },
    {
      "rel": "profile",
      "href": "http://www.opengis.net/def/profile/OGC/0/ogc-record"
    },
    {
      "rel": "collection",
      "type": "application/json",
      "title": "Dutch metadata",
      "href": "https://demo.pygeoapi.io/master/collections/dutch-metadata?f=json"
    },
    {
      "rel": "root",
      "type": "application/json",
      "title": "The landing page of this server as JSON",
      "href": "https://demo.pygeoapi.io/master?f=json"
    },
    {
      "rel": "enclosure",
      "type": "image/tiff; application=geotiff",
      "title": "The data as GeoTIFF",
      "href": "https://demo.pygeoapi.io/master/collections/dutch-metadata/items/b7d2fd24-8cd8-4965-a997-69eb1a987b5a/data?f=geotiff",
      "file:size": 123456789,
      "file:checksum": "12209cbc07c3f991725836a3aa2a581ca2029198aa420b9d99bc0e131d9f3e2cbe47"
    }
  ],
  "assets": {}
}
----
====
