== Conformance

=== Overview

This Standard defines two requirements classes:

* <<rc_stac-extensions,STAC Extensions>>, and
* <<rc_stac,STAC>>.

The standardization targets of both requirements classes are records and catalogs as defined in OGC API - Records - Part 1: Core. Conformance is declared in two places:

* A server that provides records through an API declares conformance at its `/conformance` endpoint.
* A record or catalog declares conformance in its `conformsTo` member. This is the only option for crawlable catalogs, which have no `/conformance` endpoint.

Records that conform to the "STAC Extensions" requirements class use members from one or more STAC extensions. They do not need to be STAC Items. This allows any implementation of OGC API - Records to use STAC extensions without adopting the rest of the STAC data model.

Records and catalogs that conform to the "STAC" requirements class are also valid STAC Items and STAC Collections. Clients of OGC API - Records and STAC clients can both use them without any conversion.

=== Conformance testing

Conformance with this Standard shall be checked using all the relevant tests specified in <<annex_ats,Annex A>> of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

[#deployment_conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
|Conformance class |URI
|<<ats_stac-extensions,STAC Extensions>> |http://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac-extensions
|<<ats_stac,STAC>> |http://www.opengis.net/spec/ogcapi-records-5/1.0/conf/stac
|===
